### ISSUE TITLE
Issue with decimal and thousands separators 

### ISSUE THREAD

**Issue by ncampuzano** [BobKnothe/autoNumeric#110]
When the decimal separator is set to be ',' and the thousands separator is set to '.' there's a weird behaviour when the number is 6 digits or less. The directive ends up removing the last three digits assuming they are decimals. 

The following gif shows it: 

![um4imnhs3d](https://cloud.githubusercontent.com/assets/5368137/5631998/0b84e502-9599-11e4-8634-7bbd35f48390.gif)

The options we're using are these:
````var options = { aSep: '.', aDec: ',', mDec: 0};````

**Comment by BobKnothe** [comment]
Nicolas,
 
Many questions.
 
 
+ What version of AN are you using? 
+ Is this desktop or mobile? 

 
 
Without the code it is hard for me to determine what is happening - can you post a working example?
 
Bob
 
--------- Original Message --------- Subject: [autoNumeric] Issue with decimal and thousands separators (#110)

**Comment by ncampuzano** [comment]
The version we are using is 1.9.27, that I think is the latest one. Also, this is happening in a desktop application. 
In this repository you can view the directive that we're using and the html where it is applied. 
https://github.com/ncampuzano/AutoNumericIssue110

**Comment by ncampuzano** [comment]
Bob, 

Actually, aparently 1.9.27 is not available from bower, when we try to call any version above 1.9.27 its response is: 
![image](https://cloud.githubusercontent.com/assets/5368137/5663584/e2363b90-9716-11e4-8e38-f4272ea5732e.png)

According to this, the version we had been using is 1.9.26. This is probably because there's no release in https://github.com/BobKnothe/autoNumeric/releases with the new version. What can we do to test it with the latest one?  

Line 819 in our version is: ````this.formatted = true;````

Thank you!

**Comment by BobKnothe** [comment]
Sounds like I have sinc issue - will try and fix tonight

 
Robert (Bob) Knothe

**Comment by BobKnothe** [comment]
Nicolas,

Please try now.

Bob

**Comment by ncampuzano** [comment]
Hello Bob,

I tried again, and created a working example on https://github.com/ncampuzano/AutoNumericIssue110 where you can see, in index, the problem shows when input have a ng-model. However when the input doesn't connect with model the problem doesn't appear.

**Comment by BobKnothe** [comment]
Nicolás,

Thank you - now I see the issue.

It's happening on focusout event but i need to track down what is 
causing this problem.

Give me a day or two to find the time to fix.

Bob

**Comment by BobKnothe** [comment]
Nicolás,

Just uploaded 1.9.28 which should fix the issue - thank you for being 
persistent.

Best regards,

Bob

**Comment by ncampuzano** [comment]
@BobKnothe 

Thank you, however only there is a error in Commit realized in realese 1.9.28. You put this code, 
````if (setValue &&  && $this[0].value === $this.prop('defaultValue'))````

It should be 
````if (setValue && $this[0].value === $this.prop('defaultValue'))  ````

**Comment by BobKnothe** [comment]
Nicolas,
 
Please let me know if 1.9.30 solves your issue.
 
Bob
 
--------- Original Message --------- Subject: Re: [autoNumeric] Issue with decimal and thousands separators (#110)

**Comment by ncampuzano** [comment]
Thank you @BobKnothe 

The issue is fixed. 

Best regards,
