### ISSUE TITLE
Regression from 1.9.26 to 1.9.27 (and 28)

### ISSUE THREAD

**Issue by phax** [BobKnothe/autoNumeric#111]
1.9.27 introduced a bug upon initialization of numeric values.
See http://jsfiddle.net/9rmug2dd/3/ for a working example.
Run it with 1.9.26 and everything works fine ("250,00" as expected).
Starting with 1.9.27 the value is initially not formatted correctly and when focusing and afterwards bluring, the value gets reformatted from "250.00" to "250000,00".

**Comment by BobKnothe** [comment]
Philip,

I see the issue and will try and fix shortly - thanks for the heads up.

Bob
