### ISSUE TITLE
Allow attaching to a container element and applying to any children that match a selector

### ISSUE THREAD

**Issue by danieldemus** [BobKnothe/autoNumeric#113]
Using autoNumeric with dynamically created elements is annoying, as you have to add init code everywhere you insert relevant elements into the DOM.

It would be much more convenient to attach autoNumeric to fx. a container element that isn't replaced and specify the elements to format via a selector. All matching elements would thus be formatted identically.

Fx. if the container was <div id="dynamic-content" />, you could say 
`$('#dynamic-content').autoNumeric('init',`**'.number-input.decimal',**`{aDec: ',', aSep: '.', mDec: 2 });` would attach to all current **and future** elements with `class="... number-input decimal ..."`, thus making it unnecessary to manage autoNumeric inits. With judicious use of the class attribute it would be possible to init once on page load and have everything work automagically.

The change would basically entail adding the value of the second parameter to any .on(...) calls in the init code, saving the options on the target of the on() method with some sort of key, fx. the selector, and using event.delegateTarget to read the numeric options when handling a relevant bubbly event.

**Comment by BobKnothe** [comment]
Daniel,
 
Interesting idea.
 
Does your suggestion assume that any dynamically added inputs would all have the same options?
 
Bob
 
--------- Original Message --------- Subject: [autoNumeric] Allow attaching to a container element and applying to any children that match a selector (#113)

**Comment by danieldemus** [comment]
Yes. For any given set of classes.

Fx. `<div id="container">
<input type="text" class="behave-as-autonumeric an-decimal" />
<input type="text" class="behave-as-autonumeric an-integer" />
<input type="text" class="behave-as-autonumeric an-percentage" />
</div>`
would have 3 inits thusly:
`$('#container').autoNumeric('init', '#container .behave-as-autonumeric.an-decimal', { mDec: '2' };
$('#container').autoNumeric('init', '#container .behave-as-autonumeric.an-integer', { mDec: '0' };
$('#container').autoNumeric('init', '#container .behave-as-autonumeric.an-percentage', { mDec: '2', aSign: '%', pSign: 's' };`
which would result in 3 data()s on #container containing the selector and the options. When container receives a keypress event, you can test whether event.target.is(saved_selector), (you might need to sort the selectors by specificity, if you only want one match, otherwise combine the matched options) and use the resulting options.

As I understand the jQuery event system, even newly added elements that match the selector in the .on('event', selector) will trigger the relevant event, so dynamically added elements will not need to be manually init'ed.

**Comment by danieldemus** [comment]
Ah. 'get' and 'set' would of course also need to search up the tree for the first element with a compatible data.

**Comment by BobKnothe** [comment]
Daniel,

While I like the concept this needs to be thoroughly thought through and the follow needs to be considered:

Backwards compatibility 

HTML5 data that is consistent with current autoNumeric standards.

Will the new inputs be automatically formatted?

While each container will have its own options - what if there are many different options required. While having a single option tmay be your your situation this is not necessarily true with all of my users which I need to consider. 

Others ????

While you are not the first to enquire about how to handle dynamically added elements you at the first to offer suggestions which is appreciated. 

 What I need to consider the 1,000s of users I have and how it may impact them.

I hope you understand. This is not me saying no I just want to make sure the goal is accomplished without tearing down the foundation. 

I am always willing to review code that is contributed. 

Best regards,

Bob

Robert (Bob) Knothe

**Comment by danieldemus** [comment]
The goal is to not change current functionality at all. The main gist is to separate the storage of options and event handlers from the input fields they should be applied to. 

The 'data' I was thinking of is the jQuery .data(), not HTML5 although the data method tries to be transparent, AFAIK. Maybe HTML5 data attributes would be used to configure individual input elements, while one would have to use js to use delegated formatting?

I have seperate options for each *selector* not container. One could also attach to the document root if it doesn't impact performance too much. The options attached to a container would be keyed on the selector, so you can have as many options as you have selectors. Options with an empty or null selector refer to the attachee element itself. As the key in .data(key/name, value) is a string you could add extra options with an extended key. The main question regarding the options is what to do if multiple selectors match: take the first one, merge all options, throw an exception, weep, make it configurable. (I would tend to go for merge matching options myself, becsue then you can have a set of descriptive classes that each contribute some part of the format without as much repetition, but YMMV).

Again 'set', 'get', 'destroy', etc. would need the same overloads with selectors to retain consistency.

**Comment by AlexandreBonneau** [comment]
I do not think it's autoNumeric role to select DOM elements.
Specially with all the corner cases that would need to be managed.

We strive to keep autoNumeric as light as possible, and to efficiently autoformat a single input.
This would mostly only increase its size and complexity.

On the other hand, autoNumeric also tries to be as transparent as possible and not interfere with other libraries and framework. Hence, the user should be able to use whatever framework (Vue.js, d3.js, jQuery...) or even pure JS to select the elements he wants to initialize.

You could create a simple `container.querySelectorAll('.autoNumInputOptionOne')` query that would do what you want to achieve, for instance.

**Comment by Techiejaat** [comment]
$('.addcommas').autoNumeric('destroy');
$('.addcommas').autoNumeric('init',{aSep: ',', mDec: 2});
