### ISSUE TITLE
cursor at the end when clicking into (empty) element

### ISSUE THREAD

**Issue by j-schumann** [BobKnothe/autoNumeric#115]
Test: http://jsfiddle.net/33fsykqz/1/

Using a suffix sign, when the input is empty and we click into it, the cursor is (correctly) placed before the sign in Firefox, but placed *after* the sign in Chrome + IE.

While this is not a big problem because pressing any key moves the cursor to the right position, entering a number correctly puts it in front of the sign it irritates user and makes them think they have to move the cursor or remove the sign before entering a value.

Can this be fixed so the cursor is always positioned in front of the sign in all browsers?

Additionally: When there is already a value entered with a suffix sign present and we click into the input, on the right side of the sign, the cursor is placed after the sign in every (tested) browser. Can this be enhanced so the cursor is before the sign, after the value, in this cases?

Thanks in advance,
JS

**Comment by avalanche1** [comment]
Don't understand why this been closed - it's still not resolved as of now.

**Comment by BobKnothe** [comment]
Unfortunately you cannot reliably get or set the caret position on the "focusin" event and I do not want to add a "click" event.

**Comment by avalanche1** [comment]
Have you tried smth like this? Why shouldnt it work?
```js
//SET CURSOR POSITION
$.fn.setCursorPosition = function(pos) {
  this.each(function(index, elem) {
    if (elem.setSelectionRange) {
      elem.setSelectionRange(pos, pos);
    } else if (elem.createTextRange) {
      var range = elem.createTextRange();
      range.collapse(true);
      range.moveEnd('character', pos);
      range.moveStart('character', pos);
      range.select();
    }
  });
  return this;
};
```

**Comment by BobKnothe** [comment]
There is a set cursor function built into autoNumeric - look at the top 
of the code.

I have tried setting the caret position on the "focusin" event but the 
"click" event occurs after the "focusin" so if the mouse is over a 
different position the caret is moved to that position.

**Comment by BobKnothe** [comment]
You as developer can set caret position with a separate function that 
uses the click event that is executed after autoNumeric.

**Comment by avalanche1** [comment]
I tried this and it worked:
```js
                    $this.on('focusin.autoNumeric', function () {
                        $this.setCursorPosition(1);
                        //holder = getHolder($this);
                        //var $settings = holder.settingsClone;
                        //$settings.hasFocus = true;
                        //if ($settings.nBracket !== null) {
                        //    var checkVal = $this.val();
                        //    $this.val(negativeBracket(checkVal, $settings));
                        //}
                        //holder.inVal = $this.val();
                        //var onEmpty = checkEmpty(holder.inVal, $settings, true);
                        //if (onEmpty !== null && onEmpty !== '') {
                        //    $this.val(onEmpty);
                        //}
                    });
```
Yes, it doesn't change 'click' event behaviour, but it's not needed. As you can see from topic subject, we need the cursor to be on position 1 on **the initial activation**  of input field)

**Comment by BobKnothe** [comment]
The original issue was not on page load or autoNumeric initialization but when a user clicks into the input.

Your method may work on tab in if there is not value and just the currency sign. What happens if a user clicks into the field? Or if there is a value and a currency sign?

In my opinion there are too many variables to properly to code without knowing the users intent.

**Comment by avalanche1** [comment]
well, suit urself. this override works for me and I'm happy.

**Comment by BobKnothe** [comment]
That's the beauty of open software - you can modify to meet your needs.

Thanks for using autoNumeric.
