### ISSUE TITLE
feature request: change style depending on the values

### ISSUE THREAD

**Issue by sk29110** [BobKnothe/autoNumeric#116]
I like to extend this plugin so that depending on the value I like to set the css style to current 
element or parent element. Could this be done with the current implementation?

**Comment by peterboccia** [comment]
I don't undestand why, but you can simply implement a widget or plugin to call on ready and on "change events" (keyup change etc...).
It's the simply way that I see after a while.

**Comment by BobKnothe** [comment]
Of course it is possible but as Peter said the best way to accomplish this is to create a widget or plugin to handle the css styling based on the value of the input.

If you have a specific task i would be glad to listen.

**Comment by sk29110** [comment]
Thanks

**Comment by AlexandreBonneau** [comment]
For info @sk29110 , you can now change the style of the input using the `styleRules` option.
