### ISSUE TITLE
If update on focus, brackets doesn't go away for negative amount

### ISSUE THREAD

**Issue by sk29110** [BobKnothe/autoNumeric#117]
I want to update the format on focus. Seems like there is some trouble when specifying the negative amount with brackets. If I use 'init' instead of 'update' it works. Is this bug or this is what it supposed to do?

http://jsfiddle.net/h5zm7geb/

**Comment by BobKnothe** [comment]
Thanks for the example on fiddle.
 
The 'init' method must always be used first. I am curious why you are using the 'update' method and the passing the dollar sign aSign: '$' again which is redundant because you already already passed it via the 'init' method.
 
If you remove the 'update' method every thing works as design.
 
I never anticipated or tested your scenario when adding this feature. Not sure if I should modify AN to prevent users from doing this or just warn in the documentation.    
 
--------- Original Message --------- Subject: [autoNumeric] If update on focus, brackets doesn't go away for negative amount (#117)

**Comment by sk29110** [comment]
Well maybe my case is rare. I use AN for three fields. A(esimate),B(budget),C(budget gross margin). There are all related. When changing A C value is calculated. The same thing happen when changing B. All three values can be huge amount except if you are manually entering. That's why I need to update the format on focus. 

better example here.
http://jsfiddle.net/h5zm7geb/12/

**Comment by sk29110** [comment]
I used AN for estimate budget calculation. I have estimate amount, budget amount, and budget GM.
When changing estimate or budget amount are changing, the budget gm should get updated. If budget gm is changing only budget amount get recalculated. budget gm can become huge number depending on the budget amount and estimate amount. However if user is typing into the budget gm I want to limit to 0 - 100%. That's why I have to update on focus. 

Here is the better example.
http://jsfiddle.net/h5zm7geb/12/

Currently I made workaround to destory and init on focus.

**Comment by Raylehnhoff** [comment]
I did a similar thing (triggering updates on other fields based on a particular field) when I built this calculator:

http://money.cnn.com/calculator/retirement/retirement-need/

I did it on blur(), and had a common method that would re-do the calculations (getCalc())

The data was bound to a page view model. getCalc() would do some calculation, set the view model properties, which would update the underlying values via autoNumeric('set').

An example of this is:
````Javascript
	$("#retirement-age").on('blur', function () {
		//make sure the item is within the range specified
		_self.ValidateAge();
		
		//perform calculations (in this case, on the server, but ultimately it's:
		//perform calc, update view model, call autoNumeric('set', value) on the textboxes
		_self.GetCalc();
	});
````
There is no need to destroy/init on focus. You have the workflow backwards.

**Comment by Raylehnhoff** [comment]
Here's a fiddle of an example where the value from one text box will update the second textbox (and perform a calculation on it, just for good measure).

http://jsfiddle.net/h5zm7geb/13/

**Comment by BobKnothe** [comment]
Ray,
 
Hope all is well.
 
Thanks for your input - it is always great when AN users contribute.
 
Bob
 
--------- Original Message --------- Subject: Re: [autoNumeric] If update on focus, brackets doesn't go away for negative amount (#117)

**Comment by sk29110** [comment]
Thanks Ray,

Yes I did that similar stuff for recalculation but what I also want to do is change the limit on the input box.
So in your example if second input box(b) is generated by first input box(a) x 2. What I want to do is if you are typing into the second input box I want to set the limit so that it doesn't go over the certain number. But no limit on second input box if you are typing in the first input box.

**Comment by BobKnothe** [comment]
I am on other paid projects and hope to check the issue sometime in the next next.
 
 
--------- Original Message --------- Subject: Re: [autoNumeric] If update on focus, brackets doesn't go away for negative amount (#117)

**Comment by Raylehnhoff** [comment]
Let me think your problem over and see if I can come up with a solution
that doesn't involve destroying the dom object.

I think the easiest way would be to have some sort of validation method on
blur, but that may get to be complicated. If you're not using a data
binding library (like knockout).

**Comment by sk29110** [comment]
Thanks Bob and Ray,

I think the problem is negativeBracket function is called twice once for focusin and 'update'.
For now I am ok with destroying & reinit it. Looking forward for update(whenever you have time).

**Comment by BobKnothe** [comment]
Basically what is happening is autoNumeric's focusin event fires first and the brackets are removed.
 
Then your bind script calls the 'update' method and the last things the update method does is call the "set" method to format the value to the new settings that is why the brackets are re-set and visible.
 
This might involve testing if the element has focus in the "set" method then assigning "oEvent" setting to 'focus which is used in the negativeBracket private function. I have done no testing to see if this is possible and do not know if this might break other pasts of AN.
 
I open to help and ideas.
 
--------- Original Message --------- Subject: Re: [autoNumeric] If update on focus, brackets doesn't go away for negative amount (#117)

**Comment by Raylehnhoff** [comment]
I set this up with Knockout using a few observables.

It's not particularly great, since I don't know what you exact case is. I setup a limit on "value1", so when it's changed it cannot be greater than "value2". All of this is done with the context of autoNumeric gets/sets.

You could do similar subscriptions and change the values up/down as necessary. If you were more clear on what your business problem is I could try to tailor this solution a bit more.

Doing this without knockout would be pretty gross. If you're someone that's working with javascript a LOT, especially around manipulation, I highly suggest using a data-binding library for it.

http://jsfiddle.net/h5zm7geb/21/

Let me know if this is way off base (and describe your problem more fully), and I could try to assist.

Thanks,
Ray

**Comment by BobKnothe** [comment]
sk29110,

I just uploaded version 1.9.31 as a separate file. This should fix your issue when calling the "update" method on focus.

Before I officially update the master could you test and get back to me.

Thanks,

Bob

**Comment by sk29110** [comment]
Thanks I can look into this on this weekend :)

**Comment by sk29110** [comment]
Thanks for adding the support for setting constraint on focus event. Now when I focus into the negative amount, bracket becomes negative sign even I set different constraint on focus :)

I tested around focus event but after updating the constraint with 'update' the constraint doesn't really work.

In the following example, 
http://jsfiddle.net/wx2h922o/27/

1. type 111 in the first input box - it can't input the the forth digit from the constraint
2. focus out and enter 1111 again in the same input box - this time I can type in 4 digits

Let me know if you have question.
Shinya

**Comment by BobKnothe** [comment]
Shinya,

Just uploaded a mod but there are issues with your code:

1) When you update on focus the existing value falls outside the new min/max range so now the result will be zero. If you change the existing  -999.99 it will work.

2) it is not necessary update options that already exist - this should accomplish the same: $(this).autoNumeric('update', { vMax: MONEYMAXVALUE, vMin: -1 * MONEYMAXVALUE });

3) Not sure what  "Sign: 's'" is - are you trying to update pSign: 's'?

Bob

**Comment by sk29110** [comment]
Bod,

I tested and now all the stuff works. 

For 1) case it sets to zero as you mention, but I am not sure if developers using AN is expecting to catch the exception there.

**Comment by BobKnothe** [comment]
Shinya,

Glad AN is now working for you.

I am open to suggestions on how AN should function and would like to hear your ideas.

Bob
