### ISSUE TITLE
Problem with multiple fields with same name in a single form

### ISSUE THREAD

**Issue by retromax** [BobKnothe/autoNumeric#118]
Hi,
first of all I want to thank you guys for this greate peace of software!
Unfortunately I am suffering a problem. When having a single formular with multiple input fields using the same name the getString Method returns for every input field the value of the first one.

```html
<form>
<input type="text" name="input" value="3.4">
<input type="text" name="input" value="8.5">
</form>
```
leads to:
```getString
input=3.4&input=3.4
```

Here my attempt for a workaround.

```javascript
** method to get the unformatted value from multiple fields */
        getString: function () {
            var isAutoNumeric = false,
                $this = autoGet($(this)),
                str = $this.serialize(),
                parts = str.split('&'),
                formIndex = $('form').index($this),
                //addition:
                inputIndex = new Array(),
            	//end addition
                i = 0;
            for (i; i < parts.length; i += 1) {
                var miniParts = parts[i].split('='),
                    $field = $('form:eq(' + formIndex + ') input[name="' + decodeURIComponent(miniParts[0]) + '"]'),
                    settings = $field.data('autoNumeric');
                //addition
                if($field.length > 1) {
                	if(inputIndex[decodeURIComponent(miniParts[0])] === undefined) {
                		inputIndex[decodeURIComponent(miniParts[0])] = 0 
                	} else {
                		inputIndex[decodeURIComponent(miniParts[0])]++
                	}
                	$field = $field.eq(inputIndex[decodeURIComponent(miniParts[0])]);
                }
            	//end addition
                if (typeof settings === 'object') {
                    if (miniParts[1] !== null) {
                        miniParts[1] = $field.autoNumeric('get');
                        parts[i] = miniParts.join('=');
                        isAutoNumeric = true;
                    }
                }
            }
            if (isAutoNumeric === true) {
                return parts.join('&');
            }
            return str;
        },
```

I have not tested but maybe the toArray Method suffers the same problem.

Greetings Max

**Comment by Raylehnhoff** [comment]
This isn't a bug with AutoNumeric, this is an issue with your HTML. If they need the same name, you're supposed to tag them with an array identifier: 
````HTML
name="myName[]"
````

Please see this article:

http://stackoverflow.com/questions/7880619/multiple-inputs-with-same-name-through-post-in-php

**Comment by retromax** [comment]
Hi Raylehnhoff,
I don't think my html is wrong i've checked it with http://validator.w3.org/ and checkt the HTML5 specification (http://www.w3.org/TR/html5/forms.html#naming-form-controls:-the-name-attribute).

Nevertheless I tried your suggestion using the squared brackets to indicate an array but there is no difference with my initial example (tested with chrome and IE11 and Chrome39)

Greetings Max

**Comment by BobKnothe** [comment]
Max,

Currently my plugin requires a unique name to have the "getString" and "getArray" methods to function properly.

This is the first time in three years this issue has been brought to light. I will look at modifying AN to address this but as Ray mentioned if the same name is used it will require an array passed as follows:  name="myName[]".

The offending line(s) below creates a name selector that grabs the data from the element.

$field = $('form:eq(' + formIndex + ') input[name="' + decodeURIComponent(miniParts[0]) + '"]')

Not sure how I will fix  this! It may require loop within a loop testing if the same name is used and how many times. 

If you have any suggestions it would be appreciated.

Bob

**Comment by BobKnothe** [comment]
Maybe rather then create a name selector it could be accessed by it's index?

**Comment by Raylehnhoff** [comment]
You could also check out jQuery's way of handling form serialization. It's
open source after all :)

**Comment by BobKnothe** [comment]
Max,

The more I study your code the more I like it! 

You can have multiple shared names, they do not need to be adjacent to each other and the shared names can work with (name="myName[]") and without name="myName" the array addition.

I will test this on the "getArray" method and let you know the outcome but I suspect it will work.

Thanks for your contribution.

Bob

**Comment by BobKnothe** [comment]
Max,

I just uploaded version 1.9.31 to github as a separate file. This includes your mod to the "getString" method as well as a similar mod to the "getArray" method.

Before I officially update the master could you test and get back to me.

Thanks again for your help.

Bob

**Comment by BobKnothe** [comment]
Max,

Again thanks for your help.

Just updated to 1.9.32 which includes your mods.

Bob

**Comment by BobKnothe** [comment]
Max,

Just posted version 1.9.34.

I found an error with you mod if the last input was not under autoNumeric control.

Rather then use the name selector i changed it to the input index selector 
"var $field = $('form:eq(' + formIndex + ') input:eq(' + i + ')'),"

Again thanks for bringing the issue to my attention.

Bob
