### ISSUE TITLE
wrong rounding

### ISSUE THREAD

**Issue by tkapler** [BobKnothe/autoNumeric#120]
I have tried to paste there "124434.5567€" and with default settings it rounded it wrong as "124434.55€"

**Comment by BobKnothe** [comment]
What rounding method are you using?

Please post a example on jsfiddle

 
Robert (Bob) Knothe

**Comment by BobKnothe** [comment]
Tomas,

When using the right click mouse it works but but "ctrl + v" does not.

Will dig deeper and get back to you.

Bob

**Comment by BobKnothe** [comment]
Tomas,

Just uploaded version 1.9.32 which should fix the "ctrl + v" paste rounding issue

Bob
