### ISSUE TITLE
Can I turn off thousands seperator? aDec : ''

### ISSUE THREAD

**Issue by haldiggs** [BobKnothe/autoNumeric#121]
I need to pass the money values off to a service where money is seen as a decimal value. The thousands separator breaks the decimal value.

**Comment by haldiggs** [comment]
never mind. I'll do it differently

**Comment by BobKnothe** [comment]
Use the 'get' method


$(selector).autoNumeric('get'); // ########.## numbers without signs of 
thousand separator.

**Comment by BobKnothe** [comment]
You can pass an option the no thousand separator is used aSep: ''
