### ISSUE TITLE
Shift+Ins in FireFox doesn't work

### ISSUE THREAD

**Issue by arwyl** [BobKnothe/autoNumeric#122]
In checkPaste function this.valuePartsBeforePaste seems to be undefined in FireFox, when user tries to paste values with Shift+Ins hot key
I checked versions  1.9.24,  1.9.34 and 2.0-BETA - this error remains in all of them

**Comment by BobKnothe** [comment]
What error message are you getting?



 
Robert (Bob) Knothe

**Comment by arwyl** [comment]
There is none. Pasting just doesn't work

**Comment by BobKnothe** [comment]
Currently the pasting event is not supported because when I started this five years ago the event was support was spotty.  

In the keyup I have a function (check paste) the takes the input and tries check it meets the input limit and the format. This is when "ctrl" + "v" is pressed in windows. 

If you are you are using a different key combination its possible but I would need to test for key codes. 

Even so the first key event after should take the input and properly format.  

If it dose not please post a fiddle and give me details so I can investigate. 





 
Robert (Bob) Knothe

**Comment by arwyl** [comment]
I'll try to do it first thing Monday and give you proper reply. Thanks for
being so fast with you replies!

**Comment by arwyl** [comment]
Unfortunally, it didn't work.
What is my use case: windows 8, browser FireFox 36.0.1 (latest)
empty field, I try to paste some number using shift+ins - nothing happens, no errors. After that I tried to input some number manually - it works, but pasting doesn't.

**Comment by BobKnothe** [comment]
Are you using windows 8 desktop or mobile?
 
Unfortunately I do not have a win8 test machine. 
 
--------- Original Message --------- Subject: Re: [autoNumeric] Shift+Ins in FireFox doesn't work (#122)

**Comment by arwyl** [comment]
desktop
maybe it can also be reproduced in linux version of firefox..

**Comment by BobKnothe** [comment]
I use FF on win7 and it works with ctrl & v 
 
Right click requires another event to (key or focusout) to format.
 
 
--------- Original Message --------- Subject: Re: [autoNumeric] Shift+Ins in FireFox doesn't work (#122)

**Comment by arwyl** [comment]
ctrl+v works for me as well, but one of my oldfashioned users wants to use shift+ins for pasting

**Comment by BobKnothe** [comment]
will check to see if I can add support without breaking something else.
 
 
 
--------- Original Message --------- Subject: Re: [autoNumeric] Shift+Ins in FireFox doesn't work (#122)

**Comment by arwyl** [comment]
thanks a lot!

**Comment by BobKnothe** [comment]
Arwyl,

I can build the support for shift & inserts but unfortunately it does 
not function in FF.

The problem is FF throws the keypress event on the insert key while IE, 
Chrome & Opera do not.

I created this page for testing keyevents 
http://www.decorplanit.com/plugin/beta/keyevents.html

Bob

**Comment by arwyl** [comment]
As I wrote before. Can you tell me if it would be fixed sometimes? Maybe change the handling of pasting or some other way? Or you are not going to include this feature in your future plans?

**Comment by BobKnothe** [comment]
I am trying other solutions I just cannot give you a time frame - hope 
by the end of the month.

**Comment by arwyl** [comment]
Thanks a lot!

**Comment by BobKnothe** [comment]
Here is a possible temporary fix try this - in version 1.9.34 replace 
line 681 with the following

             if ((ctrlKey || cmdKey) && (kdCode === 67 || kdCode === 86 
|| kdCode === 88) || kdCode === 16 && kdCode === 45  || kdCode === 16 && 
kdCode === 0) { /** if copy (c=67) paste (v=86) or cut (x=88) */

let  me know if that works

**Comment by arwyl** [comment]
unfortunately, it didn't help

**Comment by BobKnothe** [comment]
insert these three line just below the keypress event line 980

                    $this.on('keypress.autoNumeric', function (e) { //line 980
						if (e.keyCode === 45) { // new insert
							return; //new insert
						} // new insert

**Comment by arwyl** [comment]
Great, that helped!
Thanks a lot, I'll test this a little bit more later this week - just in case it broke something else, but at first sight everything works fine

**Comment by BobKnothe** [comment]
Please note this is for key events.

right click paste menu is not supported
