### ISSUE TITLE
Positive Integrs only

### ISSUE THREAD

**Issue by jersingh** [BobKnothe/autoNumeric#124]
Can someone posit a configuration that allows positive non-zero interger input only?

Thanks

**Comment by peterboccia** [comment]
Simply set the vMin to 0 and set the number of decimals to 0 with mDec = 0.
you can assign it with html5 attribute data-v-min="0" and data-m-dec="0"

Have fun!

**Comment by jersingh** [comment]
Thanks for the quick reply!

This still allows me to enter a single "0" in the input. I would like to prevent a zero from being entered. Maybe my config is wrong:

$('.positive-integer').autoNumeric('init', {mDec: '0',  vMin: '0', vMax:'999', lZero: 'deny'});

**Comment by peterboccia** [comment]
You're right,
you can validate the input after or you can set the vMin to 1 (it's integer so it's start from 1).
Remember that if you want a double number you need to specify a vMin 0.0000001 (obviously with the decimal places that you allow).

**Comment by BobKnothe** [comment]
Please note that setting vMin: "1"  once you enter a number that the input cannot be blank. If there is a single digit the user will need to highlight the digit to overwrite.
 
 
 
--------- Original Message --------- Subject: Re: [autoNumeric] Positive Integrs only (#124)

**Comment by jersingh** [comment]
Ah, didn't realize you needed to highlight to back out. That will definitaly confuse users.

Feature request:
You guys would have a complete solution if the plugin could configure a min value and max value and on foucs out, force the input to either end based on the initial input beign high or low.

**Comment by BobKnothe** [comment]
Joe,
 
Currently if you want the min / max both to be greater than 0 "zero" you need to hi-light and replace.
 
Are you suggesting a option that allows the client to violate the min / max rules while the input has "focus" but on "focusout" the the developer can set a "default / new" value if the current value violates the min / max settings?
 
If so could that be accomplished by developer by setting vMin: '0' to zero and validating on the "focusout" event?
 
Bob  

 
--------- Original Message --------- Subject: Re: [autoNumeric] Positive Integrs only (#124)
