### ISSUE TITLE
Issue with european thousand separator

### ISSUE THREAD

**Issue by MojoDK** [BobKnothe/autoNumeric#127]
In europe we use dot as thousand separator and comma as decimal separator.

This code makes my input show 1,00 instead of 1.000 - it should show 1.000...

```html
<input id="test" value="1.000" />
```

```javascript
$(document).ready(function ($) {
    $.extend($.fn.autoNumeric.defaults, {
        aSep: '.',
        aDec: ','
    });
    $("#test").autoNumeric('init');   
});
```

Here's a jsfiddle:
https://jsfiddle.net/ssx3usre/

What do I do wrong?

Thanks!

:)

**Comment by BobKnothe** [comment]
Mojo,

autoNumeric accepts values with only one decimal separator (either '.' 
or ',' depending on locale) and no thousand separator.

  Example(s) value="1.000" or value="1,000" both are treated as 1.

<input  id="test"  value="1000"  /> will give you the desired results.

Hope this helps.

Bob
