### ISSUE TITLE
Zeroes in hundredths decimal place are getting deleted

### ISSUE THREAD

**Issue by luisnicg** [BobKnothe/autoNumeric#128]
hundredths decimal are being deleted if it is a 0 with aPad: false
I need a currency format, something like this:
$1,000.10
If I set aPad: false I get this:
$1,000.1
Also I should omit decimals if the user doesn't type, the user just can type
$1,000
$1,000.10 and $1,000 both should be valid in the field

$(this).autoNumeric('init',{aSep: ',', aDec: '.', aSign: '$', aPad: false});

**Comment by BobKnothe** [comment]
Please post a jsfiddle and I can see the details



 
Robert (Bob) Knothe

**Comment by luisnicg** [comment]
I need these valid formats for a currency in the field
$1,000.10
$1,000
$1,000.11

https://jsfiddle.net/unoqa1mh/

Thanks for your time

**Comment by BobKnothe** [comment]
Currently aN does support that but there maybe a work around. 

Untested but try testing the value on keyup and use the update method to change the padding option. 

Let me know if that works. 

Bob

 
Robert (Bob) Knothe

**Comment by luisnicg** [comment]
It is not recommended, but I have to change the regex:

var regex = (rDec === 0) ? (/(\.(?:\d*[1-9])?)0*$/) : rDec === 1 ? (/(\.\d(?:\d*[1-9])?)0*$/) : new RegExp('(\\.\\d{' + rDec + '}(?:\\d*[1-9])?)0*$');

to this

var regex = (rDec === 0) ? (/(\.(?:\d*[1-9])?0*)$/) : rDec === 1 ? (/(\.\d(?:\d*[1-9])?)0*$/) : new RegExp('(\\.\\d{' + rDec + '}(?:\\d*[1-9])?)0*$');

I will try to use the update method.

Thanks

**Comment by BobKnothe** [comment]
You may consider the focusin an focusout events for the update method. 



 
Robert (Bob) Knothe

**Comment by luisnicg** [comment]
```
$(selector).focusout(function(){
                if($(this).val().match(/(\.[1-9])0*$/g) != null){
                    $(this).autoNumeric('update', {aSep: ',', aDec: '.', aSign: '$', aPad: true});
                }
                else{
                    $(this).autoNumeric('update',{aSep: ',', aDec: '.', aSign: '$', aPad: false});
                }
});
```

**Comment by BobKnothe** [comment]
Glad this worked - FYI - you only need to pass options that are changing
 
 
$(selector).focusout(function(){ if($(this).val().match(/(\.[1-9])0*$/g) != null){   $(this).autoNumeric('update', {aPad: true});  } else{   $(this).autoNumeric('update',{aPad: false});  }  });  
 
 
--------- Original Message --------- Subject: Re: [autoNumeric] Zeroes in hundredths decimal place are getting deleted (#128)
