### ISSUE TITLE
Using placeholders

### ISSUE THREAD

**Issue by sabarasaba** [BobKnothe/autoNumeric#129]
Is it possible in any way to use placeholders along with autoNumeric ? I tried with the input placeholder attribute but it doesn't seem to work:

```html
<input type="text" class="input__price  js-price" placeholder="123" />
```

**Comment by BobKnothe** [comment]
It might be possible with a small modification. 



 
Robert (Bob) Knothe

**Comment by sabarasaba** [comment]
What do you mean ? Would you mind pointing me to somewhere in the code in which this behaviour could be modified ? 

Cheers.

**Comment by BobKnothe** [comment]
Try line 943
 
if (setValue && $this[0].value === $this.prop('defaultValue')) {
     $this.autoNumeric('set', $this.val());
 }
 to 
 if (setValue !== "" && setValue && $this[0].value === $this.prop('defaultValue')) {
    $this.autoNumeric('set', $this.val());
 }
 I have not tried - please let me know if that works.
  
  
 
--------- Original Message --------- Subject: Re: [autoNumeric] Using placeholders (#129)

**Comment by sabarasaba** [comment]
That did the job ! thanks bro :)

**Comment by jbadilla** [comment]
Why was this never implemented into the npm library?

**Comment by AlexandreBonneau** [comment]
Well, `placeholders` are currently working as expected in the latest stable version.
What do you mean?
