### ISSUE TITLE
Questioin about set function

### ISSUE THREAD

**Issue by alberr** [BobKnothe/autoNumeric#131]
I recently upgraded from version 1.9.8 to version 1.9.35 - thus causing some issues that I am trying to work through.  In previous versions you could initialize fields with formatting already set in the input for example `<input value="$100.00" />` could be run through as long as the field allowed dollar signs.

But in the new code the *set* function is not stripping out the preset dollar sign before checking the validity of the value - causing a $.error on line 1139.

I noticed that the autostrip was being called just above but I had to comment the testValue !== $this.attr('value') check to make it work...

Line 1130 - 1133:
```javascript
if (/*testValue !== $this.attr('value') &&*/ $this.prop('tagName').toLowerCase() === 'input' && settings.runOnce === false) {
    value = (settings.nBracket !== null) ? negativeBracket($this.val(), settings) : value;
    value = autoStrip(value, settings);
}
```
Is this check really necessary?

**Comment by BobKnothe** [comment]
The option "aForm" controls formatting of default values - if you set  "aForm: false" it should accomplish what you require.
 
I am out of the office for a week but will look at this in detail when i return. 
 
--------- Original Message --------- Subject: [autoNumeric] Questioin about set function (#131)
