### ISSUE TITLE
Hide the decimals

### ISSUE THREAD

**Issue by FoxDanger** [BobKnothe/autoNumeric#132]
The plugin automatic shows the decimals after u change the focus of the field.

There's a way to didn't show the decimals?

What I did to resolve the issue was this:

$( "#inputText" ).focusout( function( event ) {
		$( "#inputText" ).val( $( "#inputText" ).autoNumeric('get') );
	});

**Comment by BobKnothe** [comment]
Can you post a fiddle and let me see the settings?

**Comment by FoxDanger** [comment]
<div class="col-md-12 form-group">
			<label>Text/label>
			<input id='inputText' class="form-control"></input>
		</div>

$( "#inputText" ).autoNumeric( "init" , { aSep: "." , aDec: "," , vMax: "999999" } );


everything works fine, but when u focus out, the decimals apear. So I did this code to get out with the decimals :D

$( "#inputText" ).focusout( function( event ) {
$( "#inputText" ).val( $( "#inputText" ).autoNumeric('get') );
});

**Comment by FoxDanger** [comment]
< di v class="col-md-12 form-group">
			<labe l>Text</ l abel>
			< inpu t> id='inputText' class="form-control">< / i nput>
		< / di v>

$( "#inputText" ).autoNumeric( "init" , { aSep: "." , aDec: "," , vMax: "999999" } );


everything works fine, but when u focus out, the decimals apear. So I did this code to get out with the decimals :D

$( "#inputText" ).focusout( function( event ) {
$( "#inputText" ).val( $( "#inputText" ).autoNumeric('get') );
});

PS: I put the spaces so u can see the code here...

**Comment by BobKnothe** [comment]
With these settings you still have 2 decimal placed - try adding mDec: 
'0' to the options

**Comment by FoxDanger** [comment]
Ok, I'll try it tomorrow, not in work anymore today.


Em qua, 29 de abr de 2015 às 17:02, Bob Knothe <notifications@github.com>
escreveu:

**Comment by FoxDanger** [comment]
Perfect, that was what I looking for :D

Em qua, 29 de abr de 2015 às 17:33, André Luiz <foxdanger@gmail.com>
escreveu:
