### ISSUE TITLE
autonumeric rounding the value on re rendering

### ISSUE THREAD

**Issue by rathnamvemula** [BobKnothe/autoNumeric#133]
Bob,
I am using 1.9.30 version of autonumeric and having issue while re rendering the page.
If the value has one comma (one thousand separator) it is rounding the value on re rendering.
Eg: 4,777 -> 5
48,7777->49.

I have used as follows in aspx page.
$(function () {
            $("#<%=txtAmount.ClientID %>").autoNumeric('init', { mDec: 0 });        
 });

**Comment by BobKnothe** [comment]
to handle different locales autoNumeric handles the ',' comma as a 
decimal point.

4,7777 -> 5
4.7777 -> 5

You should not use a thousand separator

47777 -> 47,777 with the comma being the thousand separator

Let me know if that works

Bob

**Comment by rathnamvemula** [comment]
Bob,
I am using a text box, which I am typing in some numbers and getting thousand separator automatically. If I type 4777 in text box, it converts to 4,777 which is working fine. When I save it is getting rounded.
Is it possible to use locale where  comma is thousand separator?

**Comment by BobKnothe** [comment]
You mention save - can you explain. 

I would be very helpful to post a fiddle 

 
Robert (Bob) Knothe

**Comment by rathnamvemula** [comment]
The Save button will cause a server side post back (ASP.NET) which is saving the data from textbox to database.
In the ready function I have the code. After postback it is causing the rounding problem.
  $(function () {
            $("#<%=txtAmount.ClientID %>").autoNumeric('init', { mDec: 0 });
        });

**Comment by BobKnothe** [comment]
What is your rounding problem?
 
 
--------- Original Message --------- Subject: Re: [autoNumeric] autonumeric rounding the value on re rendering (#133)
