### ISSUE TITLE
altDec when comma is not the separator

### ISSUE THREAD

**Issue by jVmw** [BobKnothe/autoNumeric#135]
I'm not sure what the intent is with the altDec code below:
/** set alternative decimal separator key */
        if (settings.altDec === null && settings.mDec > 0) {
            if (settings.aDec === '.' && settings.aSep !== ',') {
                settings.altDec = ',';
            } else if (settings.aDec === ',' && settings.aSep !== '.') {
                settings.altDec = '.';
            }
        }

When the aDec is '.' and the aSep is not ',', the second if condition sets ',' as the altDec. Some of our amount fields don't need the comma or any separator. When we set aSep:'', the comma is entering '.' when pushed. Of course our testers are complaining.

Is the assignment altDec = ',' needed?'

**Comment by BobKnothe** [comment]
Josh,
 
I did a quick check and you should be able to change altDec: ''.
 
Change and let me know if you run into any issues and I can dig deeper.
 
Thanks for using AN.
 
Bob 
 
--------- Original Message --------- Subject: [autoNumeric] altDec when comma is not the separator (#135)
