### ISSUE TITLE
Currency without decimal part

### ISSUE THREAD

**Issue by seongreen** [BobKnothe/autoNumeric#136]
Hi, thank for this great code.

I sorry if my problem is already discussed, but I not found issue.
I have problem with JPY or BYR currency. This currency has no decimal part.
I use in config {aDec: null} but when I move focus from field, JS automatically add additional '00' to the end as omitted decimal part.

Can I configure, that currency need only aSep and ignore decimal part ? 

Thanks.

**Comment by BobKnothe** [comment]
Try {mDec: '0'}


 
Robert (Bob) Knothe

**Comment by seongreen** [comment]
Sorry, but I have jet another question. 
Could I set up, what units (cents or dollars) now in field when I init mask?
Code work perfectly when I create product. Than I save info and convert money to minimal units to prevent collisions.
And when I want to update this product I set field value in cents and this code add additional '00' because it expect big unit as default.

**Comment by BobKnothe** [comment]
I am not sure I understand what you are trying to accomplish. Can you describe another way or show me you need when the following events occur:

Init :
Focus in:
Focus out:



 
Robert (Bob) Knothe

**Comment by seongreen** [comment]
Ok
I store all amount in minimal units. Ex. 2$ I store as 200
When I draw edit form with set up field value - 200 and do $('field').init() And script show '200.00' because think that value is dollars but not in cents.

So I think that It's was cool feature to has init option like {value_in_minimal_unit: true}
So 
without this options 200 will 200.00
with this option 200 will 2.00

**Comment by BobKnothe** [comment]
I think what you are looking for is scaling 

No focus displays as $1

With focus $1,000 with no cents

This is not available in 1.9.34 but I am considering for version 2.0. 



 
Robert (Bob) Knothe
