### ISSUE TITLE
Check MaxLength from field

### ISSUE THREAD

**Issue by neyestrabelli** [BobKnothe/autoNumeric#138]
Hi, I added a function to check if field has maxlength and respect the size.

If you like to check is on my fork: https://github.com/neyestrabelli/autoNumeric/commit/224016d4148a0ad389869df6d494fbc3c3ab0afb

This helped me to limit the field.

Sorry my bad english.

**Comment by BobKnothe** [comment]
Ney,

Thank you - I will try an look over the week end. 

Bob

 
Robert (Bob) Knothe

**Comment by BobKnothe** [comment]
Ney,

Question - theoretically check max length could be less digits than the vMax / vMin settings?

Shouldn't the developer set the input length based on the max number of characters from the min/max settings?

Bob

**Comment by neyestrabelli** [comment]
Hi Bob, I made a mistake. 
I don't tried this option and really works.

Thanks for your time.

**Comment by BobKnothe** [comment]
Glad it worked
