### ISSUE TITLE
Accept date separation

### ISSUE THREAD

**Issue by sp90** [BobKnothe/autoNumeric#140]
Nice feature would be to support dates like: 22/05/90

**Comment by BobKnothe** [comment]
There are many mask plugins that can format dates. I have tried to keep autoNumeric focused on currency formatting.

I will keep this in mind on future versions.

Thanks

**Comment by sp90** [comment]
But its already solved, it done loose any value its just an extra functionality in 2 lines? :(

**Comment by BobKnothe** [comment]
While the regular expression allows dates like: 22/05/9015/ it does not 
limit the input and would allow 99/99/9999. This would require 
validation on focus out to ensure proper dates are entered.

**Comment by sp90** [comment]
Or just accept that people aren't stupid and make the able to make their own validation, depending on their own formatting

**Comment by BobKnothe** [comment]
I share your sentiment but you would be surprised by some of the 
questions I get.

**Comment by Raylehnhoff** [comment]
I personally think that if someone wants date masks they should look at
specialized libraries built for that purpose, such as moment. Autonumeric
does currency formatting exceptionally well. Don't dilute the pool or focus
on something that isn't core to currency handling. Excellent options exists
for date handling - this isn't one of them.

**Comment by BobKnothe** [comment]
Well said - thank you.

**Comment by sp90** [comment]
haven't found any librarys that mask input fields as good as this one, thats why i use it for multiple things, i also use moment.js for validation the date :+1:

**Comment by BobKnothe** [comment]
Robin Herbots input mask 
(http://robinherbots.github.io/jquery.inputmask/) does a good job on 
mask besides currency.
