### ISSUE TITLE
page reload when the thousand separator is a period "." and decimal is not present

### ISSUE THREAD

**Issue by diegosilvestri** [BobKnothe/autoNumeric#141]
The problem was solved in 1.9,27 version but it was recreated in 1.9.29 and 1.9.30 and in the 1.9.36
Regards 
Diego

**Comment by BobKnothe** [comment]
Diego,

I just tried and can not duplicate - can you post a jsFiddle

Thanks

Bob

**Comment by diegosilvestri** [comment]
Attach sample.

Regards

Diego

 

Da: Bob Knothe [mailto:notifications@github.com] 
Inviato: giovedì 14 maggio 2015 13:33
A: BobKnothe/autoNumeric
Cc: diegosilvestri
Oggetto: Re: [autoNumeric] page reload when the thousand separator is a period "." and decimal is not present (#141)

 

Diego,

I just tried and can not duplicate - can you post a jsFiddle

Thanks

Bob

**Comment by BobKnothe** [comment]
Diego,

The attachment did not come through.

Please send to bob{@}decorplanit.com - remove the brackets,

Thanks

**Comment by BobKnothe** [comment]
Diego,

The cause is ASPX postback re-renders the input tag and adds or updates the value attribute. autoNumeric tests for page reload by comparing the input value and the value attribute so it is not possible to test via that method.

I am not familiar enough ASP to know if there is a way of preventing the default value from being overwritten. Please let me know if that is possible.

Two possible approaches:

1) Change to aForm: false // all values including default values would need to be "set" 

2) I could add a session cookie routine but some might object.

Any suggestions are appreciated.

Bob

**Comment by diegosilvestri** [comment]
Sorry Bob,

the problem is only in number range 1.000 to 999.999.

If in the input I set 1.000.000 or more all it’s ok.

Regards

Diego

 

Da: Bob Knothe [mailto:notifications@github.com] 
Inviato: venerdì 15 maggio 2015 14:57
A: BobKnothe/autoNumeric
Cc: diegosilvestri
Oggetto: Re: [autoNumeric] page reload when the thousand separator is a period "." and decimal is not present (#141)

 

Diego,

The cause is ASPX postback re-renders the input tag and adds or updates the value attribute. autoNumeric tests for page reload by comparing the input value and the value attribute so it is not possible to test via that method.

I am not familiar enough ASP to know if there is a way of preventing the default value from being overwritten. Please let me know if that is possible.

Two possible approaches:

1) Change to aForm: false // all values including default values would need to be "set" 

2) I could add a session cookie routine but some might object.

Any suggestions are appreciated.

Bob

**Comment by BobKnothe** [comment]
Diego,

Not with version 1.9.36

Bob

**Comment by BobKnothe** [comment]
Diego,

Try setting the aForm option to false.

Bob

**Comment by diegosilvestri** [comment]
With aForm to false its ok.

Thanks

 

 

Da: Bob Knothe [mailto:notifications@github.com] 
Inviato: venerdì 15 maggio 2015 16:59
A: BobKnothe/autoNumeric
Cc: diegosilvestri
Oggetto: Re: [autoNumeric] page reload when the thousand separator is a period "." and decimal is not present (#141)

 

Diego,

Try setting the aForm option to false.

Bob

**Comment by BobKnothe** [comment]
Diego,

I just posted version 1.9.39 that has new new option "anDefault" - please see the readme.md on github.

if you could test it would be apprciated.
