### ISSUE TITLE
get with negatives includes thousands separator

### ISSUE THREAD

**Issue by craig-at-rsg** [BobKnothe/autoNumeric#142]
I have 2 cell values that should cancel each other:
14,675.56 and (14,675.56)

cell.autoNumeric('get') with these return
"14675.56" and "-14,675.56"

... calling parseFloat on these return:
14675.56 and -14

The issue is that the get call on a negative value is returning a string which includes the thousands separator, so it's in a different format than the positive value and isn't ready to be parsed.

**Comment by craig-at-rsg** [comment]
I tried reproducing this on jsFiddle, but it didn't reproduce, so I upgraded my js libs and I no longer see the issue...

**Comment by BobKnothe** [comment]
Glad you have it working.

Let me know if any other issues come up.
