### ISSUE TITLE
Incorrect separators

### ISSUE THREAD

**Issue by adamroof** [BobKnothe/autoNumeric#143]
Sql2008 datatype money: 12875.19
Expected results: 12,875.19

Options: none
Initializer: $(".jqNumeric").autoNumeric('init');

Error:
The value (12.875.19) being 'set' is not numeric and has caused a error to be thrown

No error for values without a thousands separator. Looks like it is trying to use non US currency defaults, but I've confirmed the defaults should be comma for thousands and decimal for cents. I am not displaying any currency symbols.

Source of error. I don't want to allow locale decimal to be a comma
                /** allows locale decimal separator to be a comma */
                if ((testValue === $this.attr('value') || testValue === $this.text()) && settings.runOnce === false) {
                    value = value.replace(',', '.');
                }
                if (!$.isNumeric(+value)) {
                    $.error("The value (" + value + ") being 'set' is not numeric and has caused a error to be thrown");
                }

**Comment by BobKnothe** [comment]
Adam,

autoNumeric is designed to take the first period '.' or comma ',' and 
treat as the decimal character. So the following the following occurs:

12875.19 => 12875.19 OK
12875,19 => 12875.19 OK
12,875.19 => 12.875.19 fails

Is this occurring on page load, page re-load or with the 'set' method? 
Also let me know the version you are using.

Can you duplicate this on jsFiddle?

Thanks,

Bob

**Comment by adamroof** [comment]
Thanks for your reply.
I expect 12.875.19 to fail, but that is not the data being presented.
It looks to be converting my correct value of 12,875.19 into 12.875.19

its occurring at this line: value = value.replace(',', '.');
its occurring on page load

**Comment by BobKnothe** [comment]
Adam

Is this run under ASP.net?

Bob

**Comment by adamroof** [comment]
Yes

**Comment by adamroof** [comment]
here is the fiddle http://jsfiddle.net/gxfLuxLL/

**Comment by BobKnothe** [comment]
Adam

<input id="testBox2" type="text" class="jqNumeric" value="12,875.19" />

The value you have shows both a decimal point and a thousand separator 
so autoNumeric which will can an error.

There are two way to approach

<input id="testBox2" type="text" class="jqNumeric" value="12875.19" /> 
remove the comma

or

change the aForm option to falsewhich will prevent the value from being 
formatted.

<input id="testBox2" type="text" class="jqNumeric" data-aform=false 
value="12,875.19" />

let me know if your issues is resolved.

Bob

**Comment by adamroof** [comment]
Right, dollars and cents. $12,875.99
Some will enter the comma, some will not. All will enter a cents value.
The autoNumeric code should not attempt to replace my comma with a decimal point.
I would rather the code handle this appropriately.
Not sure why you are having the code replace the comma with a decimal, maybe if US currency, don't?

**Comment by BobKnothe** [comment]
Adam,

autoNumeric is used throughout the world including locales where the 
decimal point is a comma and this was my attempt to accommodate for 
locale values on input. In addition there are even more thousand 
separators used.

Regardless my documentation states the following:*

Default values*

The option "aForm" controls how default values are handled on page 
ready. When "aForm: true" is true the defaults values of the the 
supported elements that are controlled by autoNumeric are formatted on 
page ready. When "aForm: false" is false the values are not formatted on 
page ready, but input fields will be formatted when they have focus on 
the first keypress event is fired.

So when aForm is set to true "aForm: true" the defaults value should be 
un-formulated as follows:
<input type="text" value="99999.99"> or <span>9999.99</span>. Have a 
single decimal point and numeric characters only.

When aForm is set to false "aForm: False" the defaults values should be 
pre-formatted as follows:
<input type="text" value="€ 99.999,99">.


I am open to suggestions on modifications if they are not locale 
specific. If you need a custom mod let me know and we can discuss the 
details.

Best regards,

Bob

**Comment by adamroof** [comment]
ok, I see what you are saying on the aForm.

**Comment by adamroof** [comment]
I am now getting the same error on the same line with percent fields. This was not an issue in 1.9.26 on another site that I am utilizing in the exact same approach. Is aForm going to be required on all future releases? This is a bug. Errors are not being completely handled and the reason for the errors are not attempted to be resolved internally. If I have to go unformatted I don't see the point in using the plugin. Don't get me wrong I LOVE what you have done with this. This is an issue across IE and Chrome, and I can recreate in jsFiddle so it is unrelated to being an "ASP.Net" issue.

New error on same line as previous error:
The value (0.00 %) being 'set' is not numeric and has caused a error to be thrown

Again, I understand that 0.00 % is NOT numeric due to the percentage sign. To resolve for now, I have added the following:

    /** allows locale decimal separator to be a comma */
    if ((testValue === $this.attr('value') || testValue === $this.text()) && settings.runOnce === false) {
        value = value.replace(',', '.');
    }
    //attempt to repair a percentage sign or dollar sign error
    if (!$.isNumeric(+value)) { value = value.replace("$","").replace("%","").replace(" ",""); }
    if (!$.isNumeric(+value)) {
        $.error("The value (" + value + ") being 'set' is not numeric and has caused a error to be thrown");
    }

This was to resolve my current issues, I realize you have other variables to handle, just letting you know what I did to have it respond like the previous version.

Thanks for your time.

**Comment by BobKnothe** [comment]
Adam,

Please create the fiddle in non- ASP.Net.

 From what I saw this is a post back issue when the original value is 
overwritten with the new value. If I missed something then the fiddle 
will indicate what is wrong.

Regardless I will be posting a mod, hopefully tomorrow that will allow 
the ASP.Net developer to check the original default.

Best regards,

Bob

**Comment by BobKnothe** [comment]
Adam,

I have a update that I would like to send to you for testing. It will require you to use html5 data attribute named data-an-default="" that has the same value as the value attribute like in the below example.

<asp:TextBox runat="server" ID="someID" value="1234.56" data-an-default="1234.56">

Please send me an email address at bob{@}decorplanit.com

Bob

**Comment by BobKnothe** [comment]
sorry did not show the example

```HTML
<asp:TextBox runat="server" ID="someID" value="1234.56" data-an-default="1234.56"/>
```

**Comment by TuyNguyen** [comment]
you only set aForm : false
