### ISSUE TITLE
Issue with browser formatting validations

### ISSUE THREAD

**Issue by jorgechoypernia** [BobKnothe/autoNumeric#144]
Hi,

Wondering whether you can help me. My users are reporting an issue with the formatting that I was not aware of.

I am initialising the formatting of some inputs as follow:

jQuery(document).ready(function() { $('.decimal9FormatCssClass').autoNumeric({ mNum: 10, mDec: 2, vMin: '-9999999.99', vMax: '9999999.99' }); });

So you can see that the quantity of digits are 10. However, this is not the case with modern browsers like IE11 where apparently the length is validated with the localisation formats.

The browser automatically add the thousand commas separators according to the regional settings of the client machine. For example, 999,999.99. So the maximum value the users can add is 999,999.99 instead of 9,999,999.99 as defined in the above initialization.

If I add 9,999,999.99, then I get a hint over the input: "You must enter text with 10 or few characters"

Also, for negative numbers, a significant reduction as the minimum that they can add is only -99,999.99 instead of -9,999,999.99 .

I do apologise if I am missing something really obvious. Can you suggest how can we omit the commas being counted???

**Comment by BobKnothe** [comment]
Jorge,

What version of autoNumeric are you using? I do not recognize the "mNum" 
option?

Is the max length of the input define to 10?

Please post a jsFiddle so I can review.

Bob

**Comment by BobKnothe** [comment]
Jorge,

This sounds like your length on the input is set a ten!

As I said in my earlier email I am not sure what this mNum is - if you 
are using the latest version 1.9.36 you could change the following:

jQuery(document).ready(function() { 
$('.decimal9FormatCssClass').autoNumeric({vMin: '-9999999.99', vMax: 
'9999999.99' }); });

mNum: 10 ??
mDec: 2 - redundant the min/max 2 decimal places is already define

I am not aware of any browser that automatically inserts commas. The 
comma is the default thousand separator in autoNumeric and will be 
inserted unless you change the "aSep: ',' to "aSep: ''. if you want 
comma's then the following is true:

vMin: '-9999999.99' =>    -9,999,999.99     character length is 13
vMax: '9999999.99' =>    9,999,999.00       character length is 12

So you maxlength attribute needs to be 13 - smaller will not let the 
user enter the max amount

<input type="text" name="someName" maxlength="13">

Bob

**Comment by jorgechoypernia** [comment]
Hi Bob,

Thanks very much for the quick response.

I took the mNum parameter from a very old example/system developed years ago developed from one of my collegues. Maybe it was withdrawn in the new releases of autonumeric??? 

My fault, I should be following the most recent documentation. I had also a look of this parameter from the follwoing site: http://prgassist.blogspot.de/2011/04/jquery-plugin-autonumeric.html.

You are right... The browser does not add the commas, I think is the default from the autonumeric library. I am going to increase the vMax and vMin values as suggested.

Thanks Bob.

**Comment by BobKnothe** [comment]
Jorge,

Wow that post is 4 years old and covered version 1.6.2

Major updates on version 1.7 & 1.8. 

Just make sure the input max length is equal to or greater than the formatted min/max value including currency sign.

Good luck. 

Bob


 
Robert (Bob) Knothe
