### ISSUE TITLE
adding dollar sign to comma separated number

### ISSUE THREAD

**Issue by sk29110** [BobKnothe/autoNumeric#146]
Is it possible to add dollar sign it the number is pre formatted with comma ( 222,111.00 )?
I am using the plugin with salesforce and by default currency fields are formatted like this in the input field but want to add dollar sign and constrain on those input field

**Comment by BobKnothe** [comment]
Not currently supported but could be accomplished with a small modification. 

Might  be easier to strip the value before sending to auto numeric



 
Robert (Bob) Knothe

**Comment by sk29110** [comment]
the value is bind to the form element so I can't change on the server side.
I can certainly do each(removing commas) to fix this, but it will be nice to to support this.

**Comment by BobKnothe** [comment]
The issue for me is that AutoNumeric would need to support this with different formats used around the world. 

I can consider for future updates but not at this time. 

A couple lines in the "set" method should do the trick. 

Bob



 
Robert (Bob) Knothe

**Comment by sk29110** [comment]
OK it makes sense. In terms of work around the below code didn't work.

var fields = $j('.currencyField');
for( var i = 0; i < fields.length - 1; i++){
   fields[i].value = fields[i].value.replace(/,/g,'');
}
$j('.currencyField').autoNumeric('init', {aSign: '$', vMax: Number.MAX_VALUE, vMin:0, mDec:2 });

**Comment by BobKnothe** [comment]
On version 1.9.37 on line 1155 try this:
 
value = value.replace(/,/g,''); 
That should replace on the comma's with ""
 
Hope this helps
 
let me know it that does the trick
 
--------- Original Message --------- Subject: Re: [autoNumeric] adding dollar sign to comma separated number (#146)
