### ISSUE TITLE
autoNumeric doesn't seem to monitor .text() changes on init'd element

### ISSUE THREAD

**Issue by PinballTO** [BobKnothe/autoNumeric#148]
I have a form with an HTML5 input of type=number which needs thousands separators to help avoid data-entry errors. Since autoNumeric doesn't handle that type, I created a *scoreFormatted* span underneath, processed by autoNumeric, which mirrors the current value in *scoreVal* on every keystroke.

Problem is, autoNumeric only formats *scoreFormatted* on initialization; as the user changes the value in *scoreVal*, *scoreFormatted* shows the new value as raw text, without autoNumeric's formatting.

This may be a simple problem, but I'm not that well-versed in JS. It seems `autoNumeric("init")` fires since the initial display is formatted; why wouldn't it monitor *scoreFormatted* for changes afterwards?

Here's the script I placed in my document's head. Thanks for your help.
```
	$(document).ready(function(){
		// Autoformat score verification field (here, with thousands separators)
		jQuery(function($) {
			$("#scoreFormatted").text($("#scoreVal").val());	// Initial value
			$("#scoreFormatted").autoNumeric("init");    
		});
		// Constantly duplicate user-entered value into score verification
		$("#scoreVal").keyup(function() {
			$("#scoreFormatted").text($("#scoreVal").val());
		});
	});
```

**Comment by BobKnothe** [comment]
Thanks for your interest in autoNumeric.

You are almost there - the below change should work - please let me know.
 
Bob
 
--------- Original Message --------- Subject: [autoNumeric] autoNumeric doesn't seem to monitor .text() changes on init'd element (#148)

**Comment by BobKnothe** [comment]
Did my answer work? If so please close the issue. 



 
Robert (Bob) Knothe

**Comment by PinballTO** [comment]
Thanks, Bob! It worked like a charm.
