### ISSUE TITLE
Please publish to npm

### ISSUE THREAD

**Issue by leider** [BobKnothe/autoNumeric#149]
would love to see that! :)

**Comment by BobKnothe** [comment]
I have been working on a major upgrade and was looking at npm at that time. 



 
Robert (Bob) Knothe

**Comment by leider** [comment]
Hi again, so what does that mean? :) - Will you publish it some day? Shall I publish it? - Your project is the last one in my stack to be available only via bower. https://github.com/softwerkskammer/Agora

**Comment by BobKnothe** [comment]
I will be publishing within the next couple days.

Just about done with version 2.0.0 with has many new features and a 
couple small breaking changes.

Bob

**Comment by leider** [comment]
\o/

**Comment by BobKnothe** [comment]
I published version 1.9.38.

Still working on version 2.0

**Comment by leider** [comment]
Great. See it in action on https://www.socrates-conference.de/payment! :8ball:

**Comment by BobKnothe** [comment]
Thanks,

I rarely get to see a finished product

 
Robert (Bob) Knothe
