### ISSUE TITLE
Create a validation error callback

### ISSUE THREAD

**Issue by danieltartarottisobrosa** [BobKnothe/autoNumeric#15]
Creates a new parameter that enables monitoring whether there an invalid insertion.

**Comment by AlexandreBonneau** [comment]
@danieltartarottisobrosa Hi, could you please give more details about your feature request?

Right now I'm not sure what you is your use case.

Given this is an old issue, if this message last unanswered for 1 month, we'll close the issue.
Feel free to re-open it if needed.

**Comment by AlexandreBonneau** [comment]
Also, what's your use case?

If I'm guessing ok, you'd want to know when the user type something if the key is dropped, right?

**Comment by AlexandreBonneau** [comment]
I'll close this for now. Feel free to re-open it if needed.
