### ISSUE TITLE
Delay sign visibility until user input

### ISSUE THREAD

**Issue by yemi** [BobKnothe/autoNumeric#150]
I would like to only show the sign (e.g. EUR) only when the user starts typing and not when just focusing the field. 

In other words, i would like to only show the sign when the input actually has a value, any ideas?

**Comment by BobKnothe** [comment]
That feature is currently not supported - may consider for future versions.

**Comment by yemi** [comment]
It would be nice since its kind of an opinionated feature. Im working on a form solution that includes floating labels like this: http://codepen.io/lbebber/pen/uEHzD

Right now when i click on an input the currency is visible behind the actual placeholder/label which makes it very hard to use autonumeric together with "floating labels". I really like the library and it would be sad to use another lib just because of this..

**Comment by BobKnothe** [comment]
Fabian,

I believe you can accomplish the desired effect by commenting our a few 
line of code.

In the "focusin" event near the bottom comment our the following lines.

                         if (onEmpty !== null || onEmpty !== '') {
                             $this.val(onEmpty);
                         }

Please let me know if that does the trick.

Bob
