### ISSUE TITLE
auto set to max value

### ISSUE THREAD

**Issue by avalanche1** [BobKnothe/autoNumeric#152]
Hey, @BobKnothe !
Q: I have `vMax = 100`. When I type `222` I would like autoNumeric to automatically set value to 100. Is it possible? (Currently it only allows to set `22`)

**Comment by BobKnothe** [comment]
Not without a modification - couple hours of work to mod and test. 

Would consider custom but not sure it would be part of the api


 
Robert (Bob) Knothe
