### ISSUE TITLE
Latest Version Ignores Setting Value From 'On Change' Event

### ISSUE THREAD

**Issue by henweigh** [BobKnothe/autoNumeric#154]
Hello,
First of all, I'm a huge fan of autoNumeric and I think you've done an amazing job with it!

I believe I discovered a bug in 1.9.38 which prevents updating the value of a form field when looking for a 'change' event on the target field.  This issue didn't exist in the last version I was using (1.9.22)

Here's a fiddle to re-create the issue:
http://jsfiddle.net/zoaxxxef/8/

The above fiddle looks for a 'change' on an input field and then tries to force the value of the field to '100.00'.  However when you change the field and click out of it nothing happens.

To further test this issue I created a second field which when changed will set the value of the first field to '100,00'.  This method works.

Please let me know if you need any more code samples or information.  Keep up the great work!

**Comment by BobKnothe** [comment]
When setting new values to an input that is controlled by autoNumeric you should use the "set" method.
 
$('input.dollars').on('change', function() {
 
 console.log('set the value to 100');
 
 // force the value to 100
//$('input[name="price1"]').val('100');
    $('input[name="price1"]').autoNumericl('set', '100');
 });
 
Let me know if that works.
 
Bob
 
--------- Original Message --------- Subject: [autoNumeric] Latest Version Ignores Setting Value From 'On Change' Event (#154)

**Comment by henweigh** [comment]
Thanks for getting back to me. :)

I attempted using the 'set' method as well and it didn't for me either.  Here's the updated fiddle:
http://jsfiddle.net/zoaxxxef/10/

On a side note: while I think having a 'set' method is nice, I think having a fallback to allow jQuery's native val() to function makes the autoNumeric library more portable.

**Comment by BobKnothe** [comment]
I see autoNumeric returning the 100.00 value!
 
So with a little digging I found what is happening is the "change" event fires before the "focusout" so autoNumeric still has the value from the 'keyup' event and sets that on "focusout" overwriting your "change" event.
 
My suggestion is to modify your event from "change" to "focusout" then test if the values changed and if needed use the "set" method.
 
Hope this helps. FYI - you are the first in 5+ years to bring this to my attention.
 
I am working on version 2.0 that handles values differently and would function they way you want - I can post to github this Friday.  
 
Bob
 
--------- Original Message --------- Subject: Re: [autoNumeric] Latest Version Ignores Setting Value From 'On Change' Event (#154)

**Comment by BobKnothe** [comment]
While digging deeper i found a simple change that fixes your issue.
 
In autoNumeric focus out event near the bottom change the following
 
from:
$this.change();
 $this.val(groupedValue);
 to:
 $this.val(groupedValue);
 $this.change();
 
I will update github friday.
 
Thanks for bring this to my attention.
 
--------- Original Message --------- Subject: Re: [autoNumeric] Latest Version Ignores Setting Value From 'On Change' Event (#154)

**Comment by henweigh** [comment]
Thanks for the update. :)

That's odd that you were able to get the value '100' from the first text box my initial fiddle.  It must have been a race condition of some type since I couldn't get it to work on any of my browsers (Chrome, FF, IE 11) on Windows 7.

I tried adding an additional change() event to the textbox after it updates and I do see the field updating now:

$('input[name="price1"]').autoNumeric('set', '100').change();

For my purposes I didn't want to trigger a second change() so I started experimenting with using blur and that also seems to work:

$('input[name="price1"]').autoNumeric('set', '100').blur();

I was also able to get it to work by using jQuery's native val() method too as long as I included blur() afterwards.

$('input[name="price1"]').val('100').blur();

What still makes me curious is how version 1.9.22 was able to set the value without having to use another input event like change() or blur().  I know there were a lot of changes from 1.9.22 to 1.9.38 so perhaps this feature got lost in the attempt to update something else?  I love the idea of autoNumeric working in the background keeping my text fields properly formatted without having to provide extra input events to trigger the functionality. 

Thanks also for the update on version 2.0.  I'll be happy to play around with it and provide you with feedback.

**Comment by BobKnothe** [comment]
Just uploaded version 1.9.39 which should fix your issue.

**Comment by henweigh** [comment]
I just attempted my jsFiddle with the updated veresion 1.9.39 but the number formatting still doesn't seem to be taking effect when an input field is set via the val() method:

http://jsfiddle.net/kzdjc706/2/

I can trick the script to format the number by appending blur() like the old version, however with the recent changes in 1.9.39 causes the change() trigger to fire infinitely until the javascript call stack is exceeded.  See this fiddle:

http://jsfiddle.net/kzdjc706/3/

**Comment by BobKnothe** [comment]
Please do not use jQuery's val() does not format the values.

I created autoNumeric "set" method to accomplish this and is all 
documented here http://www.decorplanit.com/plugin/.

Change:     $('input[name="price1"]').val('100');
to this:        $('input[name="price1"]').autoNumeric('set', '100');

The blur method will not be required.

If this works please close the issue.

Bob

**Comment by henweigh** [comment]
You are correct. I apologize as I seem to have misunderstood your message from July 17 and thought the recent change you made would make setting the value via val() would be the same as setting it through autoNumeric('set').

Switching from val() to autoNumeric('set') does indeed work. (http://jsfiddle.net/kzdjc706/4/)  The only downside of this method that I can see is that if for some reason autoNumeric fails to load or is blocked by the client you won't be able to set the value of form fields.

**Comment by BobKnothe** [comment]
Well if autoNumeric is blocked more than likely all JavaScript is blocked including jquery. 





 
Robert (Bob) Knothe
