### ISSUE TITLE
text not formatting on init

### ISSUE THREAD

**Issue by rajankapila** [BobKnothe/autoNumeric#155]
$(selector).find(".currency_format").each(function() {
                            $(this).autoNumeric('init', {aSign: '$', mDec: '0', aForm: true});
                        });

I have this code running to init with un-formatted numbers but on init the number is not formatted. What am I doing wrong?

**Comment by BobKnothe** [comment]
I just upload version 1.9.39 - I accidentally deleted the aForm option - should work now
