### ISSUE TITLE
first time by document ready, second time by click... weird

### ISSUE THREAD

**Issue by 7starsone** [BobKnothe/autoNumeric#156]
hello,
there is a strange behavior or I didn't understand how to use it in my case...

i'm on a tpl file
```
<script src="{$js_dir}autoNumeric.js" type="text/javascript"></script> //OK, it loads correctly
<span id="total_price_carteuro" style="color:red;font-weight: bold;">{($total_price*$currencies[0].conversion_rate*1.03)|round:2}</span>
<script type="text/javascript">
			var conversion = "{$currencies[0].conversion_rate}";
    </script>
```
eg. this returns 1000.00

then, if I do: (PART 2)
```
<script type="text/javascript">
	{literal}
	$( document ).ready(function() {
	$('#total_price_carteuro').autoNumeric('init',{
        aSep: '.',
        aDec: ',', 
        aSign: '€ '
          });
	});  
	{/literal}
</script>
```
first time it works as expected.

Then, ... on external js, this is done when values has been updated by click, cart quantity update, choosing another carrier with different price and so on...
```
var sd = $('#total_price_cart').text(); //i get a needed value from another div
	var number = Number(sd.replace(/[^0-9\.]+/g,""));
	sd = number * conversion; //the conversion var works good from the smarty tpl, this is not the problem
	sd = sd.toFixed(2); //the sd number is set correctly eg. 1000.00
	$('#total_price_carteuro').html(sd).autoNumeric("init",{
        aSep: '.',
        aDec: ',', 
        aSign: '€ '
    });
```

here it doesn't work... doesn't put the euro sign and the separators correctly.
1000.00 remains 1000.00 instead of € 1.000,00
IF i remove the PART 2 entirely, the update on the span id works, instead.
Do you know why? thanks
p.s. OR can I directly format the number to euro within Smarty, to avoid the PART 2?

eg. If I have 1000.00 on the tpl
can I transform it to 1.000,00 directly on smarty? do you know?

**Comment by 7starsone** [comment]
OK, I solved with this http://smarty.incutio.com/?page=commify
```
<span id="total_price_carteuro" style="color:red;font-weight: bold;">{$currencies[0].sign} {($total_price*$currencies[0].conversion_rate*1.03)|round:2|commify:-1:',':'.'}</span>
```

**Comment by BobKnothe** [comment]
Glad you found a solution.

Thanks for using autoNumeric
