### ISSUE TITLE
Not working with $(this).parents('.databaris').find('.harga')

### ISSUE THREAD

**Issue by benyaminl** [BobKnothe/autoNumeric#157]
Hello, I read your docs about set, I tried using this selector, $(this).parents('.databaris').find('.harga').autoNumeric('set', harga);

it shows this.

Please check it, thanks before

![image](https://cloud.githubusercontent.com/assets/2817332/9007726/5bee589e-37be-11e5-9127-50666f096c5a.png)

**Comment by BobKnothe** [comment]
This error is thrown when the calling the "set" method prior to using 
the "init" method.

If you did not please try the following:

$(this).parents('.databaris').find('.harga').autoNumeric('init');

$(this).parents('.databaris').find('.harga').autoNumeric('set', harga);

Bob

**Comment by benyaminl** [comment]
Okay, that kind helping anyway, thanks for fast reply! I like this code, I'm newbie programmer anyway, so your lib quite helping allot!
Sent from BlackBerry®

-----Original Message-----
