### ISSUE TITLE
jQuery .serializeArray() receives formatted string instead of raw value

### ISSUE THREAD

**Issue by vercotux** [BobKnothe/autoNumeric#158]
[serializeArray](https://api.jquery.com/serializeArray/) (EDIT: and form submission) should be returning the raw value instead of the formatted string.

This reasoning is based on W3C rules. Following the example of the ["password" input type](http://www.w3.org/TR/html401/interact/forms.html#h-17.4.1), we would expect to get the unformatted value, not the formatted string:

>**password**
>Like "text", but the input text is rendered in such a way as to hide the characters (e.g., a series of asterisks). This control type is often used for sensitive input such as passwords. **Note that the current value is the text entered by the user, not the text rendered by the user agent.** 

At the very least this should be configurable, but by default we should always get the unformatted number.

In fact this problem is even deeper. Not only serializeArray() but on form submit the value sent to the server should be unformatted by default.

Another argument for this is that submitting a formatted string causes all sorts of problems on the backend. The backend needs to first "un-format" the string and parse the value (a risky operation because it has to depend on regular expressions). But the worst part is that it actually needs to **guess** what the commas and periods mean which is just asking for problems in any kind of multi-locale environment.

**Comment by BobKnothe** [comment]
Thanks for your interest in autonumeric. Unfortunately I am not clear as to what issues you're having can you please give an example. AutoNumeric uses jQuery's serializeArray() method but does not alter in any way, it's simply loops through array and replaces the formatted of values with unformatted on inputs controlled by autoNumeric. Attend an example would help me understand your issue. Bob


-------- Original Message --------
Subject: [autoNumeric] jQuery .serializeArray() receives formatted
string instead of raw value (#158)

**Comment by vercotux** [comment]
If AutoNumeric is showing something like: "$ 123.45", when we submit the form, this exact value is sent through POST or GET to the backend. Here's the problem. We don't want "$ 123.45" on the backend. Why not?

Because it is useless. First of all we need to get rid of the currency symbol, which could be anything (even text or numbers) and it could be anywhere (prefix or suffix) or it could not be there at all. That alone is problematic enough and prone to issues. But even if we do all of that, the backend still does not know what the number is. What does "$ 123.45" mean? Is it 123.45? or Is it 12345.00? It is impossible to know.

This is why the widget should not be sending the formatted value on submit. It should supply the raw value (both on form submit and when being read by serializeArray).

**Comment by BobKnothe** [comment]
Are you using autoNumeric's "getArray" method?

**Comment by vercotux** [comment]
No. I am using $(formObject).serializeArray(). All widgets return the correct value, except AutoNumeric.

**Comment by BobKnothe** [comment]
autoNumeric's getArray method "$(selector).autoNumeric('getArray');" was created exactly for this purpose.There is a working example on http://www.decorplanit.com/plugin/, scroll down until you get to the getArray method and open the console to see the results.

All the documentation needed is there..

Bob

**Comment by vercotux** [comment]
So I should modify the underlying framework which relies on serializeArray()?
Just to accomodate for AutoNumeric because it doesn't properly follow standards?
You cannot be serious..

**Comment by BobKnothe** [comment]
AutoNumeric does not modify jQuery's serializeArray method but uses it. What  framework are you using?


-------- Original Message --------
Subject: Re: [autoNumeric] jQuery .serializeArray() receives formatted
string instead of raw value (#158)

**Comment by vercotux** [comment]
Of course it should not modify jQuery's serializeArray.

A proper solution would to store the raw value in a hidden input field and then display an auxiliary "front-end" field with all the fancy formatting that the user can mess with as they please. Plenty of widgets do this. One example is the [jQueryUI DatePicker](https://api.jqueryui.com/datepicker/#option-altField) through its 'altField' option.

**Comment by BobKnothe** [comment]
Rather then using $(formObject).serializeArray() try $(formObject).autoNumeric('getArray'); which should return the unformatted values. 


-------- Original Message --------
Subject: Re: [autoNumeric] jQuery .serializeArray() receives formatted
string instead of raw value (#158)

**Comment by vercotux** [comment]
First of all *formObject* is not AutoNumeric. It is an object representing the <form>. That piece of code would fail badly. I would need to .each() loop every form input element, and check whether it is an AutoNumeric field, and if it is apply this dumb hack just to get the right value. I would then need to repeat this horrible hack in about 30 other forms where AutoNumeric would be used. EVEN if I did all of that, which I won't, because I do not write ugly code, it solves nothing, because the moment a user presses SUBMIT the meaningless formatted value is sent to the backend.

**Comment by BobKnothe** [comment]
autoNumeric will not meet every developer's needs. It's open source so please feel free to fork and modify to your needs. There are also other good plugins available that may be better suited for your requirements. Hope you find what you need. 


-------- Original Message --------
Subject: Re: [autoNumeric] jQuery .serializeArray() receives formatted
string instead of raw value (#158)

**Comment by vercotux** [comment]
I'm not sure whose needs it meets. I guess people who just store currency values in a text column without any intention to ever use it. Thanks for trying anyway. I'll try to find a better alternative and report here if I do.

**Comment by BobKnothe** [comment]
Not sure how you are submitting your forms but you could try something 
like this

|  $(function(){
         $("#form1").click(function(event){
             event.preventDefault();

             $.ajax({
                     url:'submit.php',
                     type:'GET',
                     data:$(this).autoNumeric('getAarry'), // this uses .serialize() and iterates through the form and replaces formatted with un-formatted
                     success:function(result){
                         $("#response").text(result);

                     }

             });
         });
     });

|


Bob

**Comment by vercotux** [comment]
That is yet another workaround which creates more problems than it solves. It would work for a very basic form but it is difficult to maintain and requires all forms to be submitted through AJAX, which creates a million other problems (for example image uploading with 'multipart/form-data' type forms.

**Comment by vercotux** [comment]
Anyway for anyone looking for a real solution to this fundamental design flaw, have a look at 
[https://github.com/RobinHerbots/jquery.inputmask](jquery.inputmask).

1. Along with a tonne of other masks It supports currency formatting through a *currency* alias.
2. It ensures .serializeArray() gets an unformatted value by setting the *autoUnmask* option to true.
3. It ensures the form submits an unformatted value by setting the *removeMaskOnSubmit* to true.

Problem solved.

**Comment by BobKnothe** [comment]
Robin is a good person and he has a great plugin. Glad you found your solution. 


-------- Original Message --------
Subject: Re: [autoNumeric] jQuery .serializeArray() receives formatted
string instead of raw value (#158)

**Comment by veyselozdemir** [comment]
What a conversation ! I definitely agree vercotux has some point here. 
Autonumeric is a great tool, but must have two more settings : 
"removeFormattingOnSubmit" to send unformatted values on form submit 
"autoUnFormat" : to give unformatted values when html element's value is requested by any javascript code

**Comment by BobKnothe** [comment]
Please look on version 2.0 and you will find there



 
Robert (Bob) Knothe
TFM manager
Cell:       (678) 986-6749
Ph.:        (952) 914-9483
Email:    bknothe@tia.toppan .com
 
Toppan Interamerica, Inc.  1131 Highway 155 South, McDonough GA 30253

**Comment by veyselozdemir** [comment]
I saw now. You mean the unSetOnSubmit option.

**Comment by BobKnothe** [comment]
Yes that is the option. 

There is also multiple ways of getting the raw value before submitting.

 Either the "get" method or the raw value is stored in the settings selector.autoNumeric.settings.rawValue. 

AN2.0 has some other new features that improve the formatting flexibility. 

Let me know if you have any questions.





Robert (Bob) Knothe
TFM manager
Cell:       (678) 986-6749
Ph.:        (952) 914-9483
Email:    bknothe@tia.toppan .com
 
Toppan Interamerica, Inc.  1131 Highway 155 South, McDonough GA 30253

**Comment by zenzei** [comment]
Looking at this old thread i can't believe how rude a person could be just because something doesn't work as he pretends, and without event recognize the great work and effort done on this plugin for free. Clearly this guy has never contribute anything to the community.

Congratulations @BobKnothe, this plugin is really awesome.
