### ISSUE TITLE
if the number is to long ,something happend

### ISSUE THREAD

**Issue by ilovezy** [BobKnothe/autoNumeric#159]
hello there, I got a little problem here
some value is too large, maybe like 32,991,000,000.00
The value in input value attribute is  32,991,000,000.00
![qq 20150807105244](https://cloud.githubusercontent.com/assets/8774988/9127780/71bf5586-3cf2-11e5-8e01-9fdb89117cd9.jpg)
but in console it popup this 
![qq 20150807105923](https://cloud.githubusercontent.com/assets/8774988/9127884/a643ca5c-3cf3-11e5-9081-afb2eb34cdee.jpg)

it says the value became 32.991,000,000.00
the first ' , ' after 32 became a ' . '

why did this happend, is that the javascript can't support such big number?

**Comment by BobKnothe** [comment]
misCC,

I just posted an update for autoNumeric-2.0 beta 
(https://github.com/BobKnothe/autoNumeric/tree/master/autoNumeric-2.0) 
that has support arbitrary-precision decimal arithmetic that should 
solve your issue. While it says beta it should be stability. There are a 
couple minor breaking changes so please review the readme.md file.

Please let me know if this solves your issue.

Bob

**Comment by BobKnothe** [comment]
Checking to see if version 2.0 solved your issue. 

If so please close this issue.

**Comment by vemv** [comment]
Personally I'd just close this issue, abandoned issues just keep the issue count high (bad!), and cannot be possibly addressed.

Cheers - Victor

**Comment by BobKnothe** [comment]
Victor,

Not quite true - please look at version 2.0.

This supports Big.JS with arbitrary-precision decimal arithmetic support.

Best regards,

Bob

**Comment by vemv** [comment]
Personally I'd advise to rely on unit tests rather than feedback that doesn't look like it's going to come.

Cheers - Victor

**Comment by BobKnothe** [comment]
Victor,

I agree - it's a matter of time management with so little free time.

Bob

**Comment by BobKnothe** [comment]
My test samples shows that it works just have not not done unit testing 
with an outside test library.
