### ISSUE TITLE
EDGE /CLASSIC IE11 in WIN 10 does not allow more than 3 digits to enter

### ISSUE THREAD

**Issue by Teja510** [BobKnothe/autoNumeric#161]
Edge and IE 11 browser are facing the issue with not allowing to enter more than 3 digits in a text box that is linked with autonumeric.js

**Comment by BobKnothe** [comment]
Thanks for your interest in autoNumeric.What input type are you using?


-------- Original Message --------
Subject: [autoNumeric] EDGE /CLASSIC IE11 in WIN 10 does not allow more
than 3 digits to enter (#161)

**Comment by BobKnothe** [comment]
Can you post an example on jsfiddle?


-------- Original Message --------
Subject: [autoNumeric] EDGE /CLASSIC IE11 in WIN 10 does not allow more
than 3 digits to enter (#161)

**Comment by BobKnothe** [comment]
I just tested Edge in Windows 10 and did not experience your issue so I am going to close this.

If you continue the have problems please send me the settings and or post an examples so can see first hand.
