### ISSUE TITLE
add package.json

### ISSUE THREAD

**Issue by maruilian11** [BobKnothe/autoNumeric#166]
would you please consider adding package.json for each tags(version) so that we can add your lib on https://cdnjs.com with **git auto-update**.
thank you very much!
https://github.com/cdnjs/cdnjs/issues/5515

**Comment by maruilian11** [comment]
sorry, duplicated with #164

**Comment by BobKnothe** [comment]
Yes I can add - please give me a day or two.

**Comment by BobKnothe** [comment]
completed

thanks for your patience
