### ISSUE TITLE
Auto Unmask

### ISSUE THREAD

**Issue by Godrules500** [BobKnothe/autoNumeric#167]
Could you somehow add an autoUnmask for when we call .val()? (or add a callback event that we can do it ourselves)

It would be nice to do something like $("#Credit").val() + $("#Debit").val(); instead of RemoveCurrency($("#Credit").val() + RemoveCurrency($"#Debit").val);

**Comment by BobKnothe** [comment]
Actually I created the 'get' method that removes the formatting and 
should be used as follows:

$("#Credit").autoNumeric('get') + $("#Debit").autoNumeric('get');

autoNumeric is required to read the element data to determine the format.

Hope this helps.
