### ISSUE TITLE
vMin and vMax options result in unusable inputs

### ISSUE THREAD

**Issue by vemv** [BobKnothe/autoNumeric#169]
Given a reasonable range (vMin: 150, vMax: 1000; which for example models the possible price of a product), one cannot increase a value _by one_.

Example:

* Input has a value of 150
* User wants to change it to 250 (or 151...)
* For that, a character has to be deleted (the _2_, the _5_ or the _0_)
* Either of those deletions aare forbidden because of the vMin mechanism.
* In practice the value cannot be changed at all, for this example.

That's a unusable experience.

Not sure what the proper fix should be. I'd give a time window of N milliseconds (1500?) within vMax and vMin rules are not applied, and previous state is stored. When the window finishes, keep the value only if it satisfies the rules, else rollback to the previous value.

In my particular project I just dropped vMin - validation is applied server-side anyway.

Thoughts?

Cheers - Victor

**Comment by BobKnothe** [comment]
Victor,

Thanks for your input - it is appreciated.

This has always been a issue without a clear path to a easy solution. 
Another way is to vMin: "0" & vMax: "1000" and then validate on focusout.

Your suggestion is new and I will consider.

Bob

**Comment by vemv** [comment]
Yes, validating on focusout (or similar events) seems robust.

Time-window approach would be previsibly a bit fragile in comparison, especially on mobile where one types more slowly.

**Comment by vemv** [comment]
So... there's a fix on the way?

**Comment by BobKnothe** [comment]
Unfortunately no - after considering multiple alternatives I believe the 
best way to approach this is to validate on focusout event
