### ISSUE TITLE
initOrUpdate and/or destroyIfSet methods

### ISSUE THREAD

**Issue by zakius** [BobKnothe/autoNumeric#170]
It would be really nice to have at least one of two:
- ability to use update as init if not set already and update if initialized (or does init overwrite current settings if initialised already?)
- foolproof destroy that would just silently finish if not initialized on given element
as I don't want to init absolutely everything on page load I tend to init modals when they are needed, but I don't want multiple copies of event attached to my elements

**Comment by BobKnothe** [comment]
Jarosław,

Thanks for your input. 

I am not sure what you are requesting on the second point. Can you clarify?

Bob


 
Robert (Bob) Knothe

**Comment by zakius** [comment]
currently if you call destroy on element without initialized autoNumeric it just crashes, I'd like to be able to re-initialize my subview without worrying about things like that, just call init to overwrite settings if any, or to destroy without having to check if I can (now I should check if data('autoNumeric') related to that element exists I think, haven't tested that idea yet)
I know I should just destroy on hiding my subview, but users are sly beasts and can mess-up this anyway, that's why I always detach events before attaching them on view init

**Comment by BobKnothe** [comment]
Which version of autoNumeric are you using?In version 1.9.39 the destroy method does not throw and error but does in 2.0 which I can fix.


-------- Original Message --------
Subject: Re: [autoNumeric] initOrUpdate and/or destroyIfSet methods
(#170)

**Comment by zakius** [comment]
I use 2.0 it seems, I was sure that it wasn't there when I first downloaded it
thanks for your support

**Comment by BobKnothe** [comment]
I will post a fix to 2.0 this weekend when i get back to my office.


-------- Original Message --------
Subject: Re: [autoNumeric] initOrUpdate and/or destroyIfSet methods
(#170)

**Comment by BobKnothe** [comment]
If you replace the destroy function with the following it should do the trick - will post the official fix this weekend - thanks        /**         * method to remove settings and stop autoNumeric() - does not remove the formatting         * $(someSelector).autoNumeric('destroy'); // destroys autoNumeric         * no parameters accepted         */        destroy: function () {            return $(this).each(function () {                var $this = autoGet($(this)),                      settings = $this.data('autoNumeric');                      if (typeof settings === 'object') {                            $this.val('');                            autoSave($this, settings, 'wipe');                            $this.off('.autoNumeric');                           $this.removeData('autoNumeric');                     }            });        },


-------- Original Message --------
Subject: Re: [autoNumeric] initOrUpdate and/or destroyIfSet methods
(#170)

**Comment by zakius** [comment]
and thank you too

**Comment by BobKnothe** [comment]
fixed and released
