### ISSUE TITLE
wrong format when set aSep: ' ', aDec: ','

### ISSUE THREAD

**Issue by gribos** [BobKnothe/autoNumeric#171]
Hi, I found a bug.

When you use ctrl+v to past value (for example 2000) to the input field and the the autonumeric configuration looks like this :

$('#input').autoNumeric('init', {aSep: ' ', aDec: ',', pSign: 's', vMin: '0', vMax: '999999999.99'});

the output value is 200 000,00. Please fix this asap !

the issue is probably in checkPaste or setValueParts function.

**Comment by BobKnothe** [comment]
Can you please post an example of jsfiddle?


-------- Original Message --------
Subject: [autoNumeric] wrong format when set aSep: ' ', aDec: ',' (#171)

**Comment by gribos** [comment]
here you go: http://jsfiddle.net/4zyc2x28/2/
please try past (ctrl+v) 2000 into input field

**Comment by gribos** [comment]
the issue is prabably in this function:
function autoRound(iv, settings) 
when you call autoRound from :
    function truncateDecimal(s, settings, paste) {
        var aDec = settings.aDec,
            mDec = settings.mDec;
        s = (paste === 'paste') ? autoRound(s, settings) : s;

**Comment by BobKnothe** [comment]
Pawel,Thanks for catching the bug.The actual spot is when function autoGroup function calls the autoStrip.if you replace this:function autoGroup(iv, settings) {    iv = autoStrip(iv, settings);with:function autoGroup(iv, settings) {    if (Number(iv) !== NaN && settings.aDec === '.' || Number(iv) === NaN && settings.aDec === ',') {        iv = autoStrip(iv, settings);    }it should solve the issueI am traveling and will post an official update this weekend - so in the meantime please try the above and let me know if you run into any other issues.Bob 


-------- Original Message --------
Subject: Re: [autoNumeric] wrong format when set aSep: ' ', aDec: ','
(#171)

**Comment by gribos** [comment]
> Pawel,Thanks for catching the bug.The actual spot is when function autoGroup function calls the autoStrip.if you replace this:function autoGroup(iv, settings) {    iv = autoStrip(iv, settings);with:function autoGroup(iv, settings) {    if (Number(iv) !== NaN && settings.aDec === '.' || Number(iv) === NaN && settings.aDec === ',') {        iv = autoStrip(iv, settings);    }it should solve the issueI am traveling and will post an official update this weekend - so in the meantime please try the above and let me know if you run into any other issues.Bob

Your solution works. Thank you Can you prepare new release of autonumeric with this fix ?

btw. great library.

**Comment by BobKnothe** [comment]
will update this weekend


-------- Original Message --------
Subject: Re: [autoNumeric] wrong format when set aSep: ' ', aDec: ','
(#171)

**Comment by gribos** [comment]
Cool thx

**Comment by gribos** [comment]
hello @BobKnothe when You will update the library ?

**Comment by BobKnothe** [comment]
Yes - ran out of time. Will update this weekend


 
Robert (Bob) Knothe

**Comment by BobKnothe** [comment]
updated and released

**Comment by Decadence** [comment]
The bug is still actual if I paste number without decimal part.
Tested in latest Chrome and Firefox.

Init code:
 $(".decimal").autoNumeric('init', {
        aSep: ' ',
        aDec: ',',
        mDec: 2
    });

version: 2.0-beta - 2015-11-2 GMT 3:00 PM / 15:00

Copy: 20000
Pasted: 2 000 000,00

**Comment by Decadence** [comment]
And if I paste via right click menu - value is ok after input lost focus

**Comment by BobKnothe** [comment]
Victor,

Thanks - will dig into the issue - it appears to happen when ctrl + v 
and not the mouse paste.

Bob

**Comment by BobKnothe** [comment]
Victor,

Should be corrected

Thanks again.

Bob

**Comment by Decadence** [comment]
@BobKnothe 
Thanks for quick response and great plugin.
It seems like it works fine now.
