### ISSUE TITLE
autoNumeric in asp.net MVC 5

### ISSUE THREAD

**Issue by sinestro** [BobKnothe/autoNumeric#172]
Hi, I'm currently using autoNumeric in my application. 
It works great. 
However, in edit mode, JQuery is showing this error message:

The value ($ 100.000.00) being 'set' is not numeric and has caused a error to be thrown

I've something like this:

 public string Amount { get; set; }

@Html.TextBoxFor(model => model.Amount, new { @class = "form-control", @placeholder = ModelMetadata.FromLambdaExpression(x => x.Amount, ViewData).Watermark })

 $.extend($.fn.autoNumeric.defaults, {
                aSep: '@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberGroupSeparator',
                aDec: '@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberDecimalSeparator'
            });

$("#Amount").autoNumeric('init', { aSign: "$ " });

**Comment by BobKnothe** [comment]
Multiple reason's autoNumeric could be throwing this error:
 
1) If in fact you are trying to use this string "$ 100.000.00" as the value being set  an error will be thrown.
 
2) Maybe it's a typo but it looks like the thousand separator and the decimal 
 
Try the following values:
 
 
+ "100000.00" 
+ "100000,00" autoNumeric treats the comma  

  
Good luck and let me know if you run into and other issues
 
Bob
 

--------- Original Message --------- Subject: [autoNumeric] autoNumeric in asp.net MVC 5 (#172)

**Comment by BobKnothe** [comment]
One other question - is this error occurring on postback?
 
Bob
 
--------- Original Message --------- Subject: [autoNumeric] autoNumeric in asp.net MVC 5 (#172)

**Comment by sinestro** [comment]
it occurs on page load.

**Comment by sinestro** [comment]
When I enter the value, during creation it is entered as $ 100,000.00
and that is save to the database just like that.

However, I have updated my code to remove the symbols before saving.

var amount = String.Join("", model.Amount.Split('$', ','));

So if $ 100,000.00 is entered, it is saved as 100000.00

and that fixed the issue.

**Comment by Raylehnhoff** [comment]
Unrelated to this problem specifically, but SQL Sever provides a "money"
format. You should not be storing currency in the database as a varchar,
especially since your MVC code implies that you're trying to render money
in a culture-aware manner. Storing the currency value in SQL as varchar but
doing culture aware formatting in MVC is a huge code smell. AutoNumeric
plays nicely with "money" formatted data, as well as other traditional
currency formats (float/decimal/int).
