### ISSUE TITLE
autoNumeric can't set values with the current format already applied

### ISSUE THREAD

**Issue by edgedemon** [BobKnothe/autoNumeric#173]
Hey there.

While working with limeSurvey, i found out that if you try to apply autoNumeric, using the "init" function on a text field, which already has formatted text compatible with your current settings, autoNumeric will throw an error.

the problem comes from the set Function expecting one single separator char in either "." or "," regardless on the settings applied. example with default config :

> $(DEMOFIELD).autoNumeric('set','1,500');    

will convert to 1.5 instead of 1500

and both

> $(DEMOFIELD).autoNumeric('set','1,000,000');
and 
> $(DEMOFIELD).autoNumeric('set','1,000,000.00');    

will throw errors.

also if you set befere starting autoNumeric it will still fail.

> $(DEMOFIELD).val('1,000,000');
> $(DEMOFIELD).autoNumeric('init');

also throws errors.

to work around this i replaced line 1139, change this:

>  value = value.replace(',', '.');

for this:

> value = value.replace(settings.aSep,"");
> value = value.replace(settings.aDec, '.');

or 

> value = value.replace(settings.aSep,"");
> value = value.replace(',', '.');

that way autoNumeric will first remove its own thousand separator before trying to format.

**Comment by BobKnothe** [comment]
Thanks for you interest in autoNumeric (AN):

  * Yes AN does throw and error if you call the "init" method twice on
    the same element. If you need to change settings use the "update"
    method after you call "init"

  * Concerning $(DEMOFIELD).autoNumeric('set','1,500'); if you want
    1,500.00 then you should change to this
    $(DEMOFIELD).autoNumeric('set','1500');.


  *   AN treats the first "." period or "," as the decimal separator, so
    "1,500" is treated as "1.5", this is to accommodate locale's that
    use a "," as their decimal separator. Please use this table as a
    guide as to what is valid.

value / text 	valid?
"123456" 	true
"-123456" 	true
"123456.78" 	true
"-123456.78" 	true
"123456,78" 	true
"-123456,78" 	true
"123,456.78" 	false
"123.456.78" 	false
"$ 123,456.78" 	false

Hope this helps.

Bob

**Comment by BobKnothe** [comment]
If you are satisfied with me answer please close the issue.
