### ISSUE TITLE
Double sign when editing

### ISSUE THREAD

**Issue by fernandoval** [BobKnothe/autoNumeric#176]
The ```iv = autoStrip(iv, settings);``` on line __297__ is not executed because ```Number(iv)``` ever returns 'NaN' when aSign property is not empty and currency sign is not removed from _iv_ variable before concatenate it again on line __333__.

This causes aSign added two times to value.

Sorry my poor English.

**Comment by BobKnothe** [comment]
fixed in version 1.9.41
