### ISSUE TITLE
Maintaining format when delete (ctrl-D on mac) is pressed

### ISSUE THREAD

**Issue by fabiogelbcke** [BobKnothe/autoNumeric#179]
When deleting number with backspace, the plugin maintains formatting and won't allow you to delete dots or the money signs, but when using ctrl-d on mac, the characters are deleted normally.

**Comment by BobKnothe** [comment]
Fabio,
 
Do you want me to try and disable the ctrl-d on a mac?
 
Bob
 
--------- Original Message --------- Subject: [autoNumeric] Maintaining format when delete (ctrl-D on mac) is pressed (#179)

**Comment by fabiogelbcke** [comment]
Hey,

I don't mind all that much, I'm using your plugin regardless, I just thought I'd let you know.

thanks for the great work btw :)

**Comment by BobKnothe** [comment]
Thanks

I will look at this when i have more time.

**Comment by AlexandreBonneau** [comment]
Unfortunately I do not have a mac to test this.
Could you please tell us if the issue is still present in the latest version in the `next` branch @fabiogelbcke ?

Thanks!

**Comment by AlexandreBonneau** [comment]
Due to inactivity, I'm closing this issue considering it resolved.

If that's not the case, feel free to re-open it!
