### ISSUE TITLE
Show error message for min/max

### ISSUE THREAD

**Issue by torisoft** [BobKnothe/autoNumeric#181]
How can show error message for min and max number if exceeded ?

**Comment by BobKnothe** [comment]
Please let me understand - are you requesting a feature that would allow a validation message? Example if a client tries to enter a a number that is larger than vMax setting some message would be displayed?
 
I have been considering adding hooks in version 2.0 that would  work with popular validation plugins. 
--------- Original Message --------- Subject: [autoNumeric] Show error message for min/max (#181)

**Comment by torisoft** [comment]
yes, that's it

**Comment by BobKnothe** [comment]
I have been looking at this recently and I am still undecided how to handle. There are a multiple plugin's that handle form validation but there is no industry standard or leading candidate so moving forward needs to be done cautiously. 

So if there are going to be validation thresholds (points) these need to be defined before proceeding. Examples might be but not limited to the following:

'low' - attempting to enter or delete a value that violates "vMin" value 
"high" - attempting to enter or delete a number that violates the "vMax" value
"multipleDecimal" - only one decimal point allowed
"sansDecimal" - no decimal values allowed
"alpha" - attempting to enter a non-numeric character

I am not committing on moving forward, I just need to understand the scope before deciding if and how to proceed.

Hope you understand.

**Comment by AlexandreBonneau** [comment]
@torisoft the current beta version (see the `next` branch) throws an error when you try to set a number outside the `vMin`/`vMax` range.
ie. *Error: The value [17999999999999998] being set falls outside of the vMin [-999999999999.999] and vMax [999999999999.999] range set for this element*

**Comment by coder007** [comment]
Hi,

How do I go about showing the error message when the user tries to enter a greater value than max for the latest version? 

I tried with the demo and it just seems to not allow the user to type a greater value than the max in the first place. I think the fact that it silently does it, can be confusing for some users. How do I go about showing the error/warning message that they are trying to enter a value greater than allowed and thus is not able to -- as per the orignal poster?

http://autonumeric.org/guide#maximumValue 

![image](https://user-images.githubusercontent.com/1185589/63920228-9106d900-ca6a-11e9-8f4a-e64ea424c449.png)

**Comment by AlexandreBonneau** [comment]
Well, this is related somehow to issue #543 .
As of now, AutoNumeric only allow valid values at all times.
