### ISSUE TITLE
jquery error when value prepopulated

### ISSUE THREAD

**Issue by jlaustill** [BobKnothe/autoNumeric#182]
I'm getting a weird error.  jquery throws this

Uncaught Error: The value ($29.999.99) being 'set' is not numeric and has caused a error to be thrown

When I load a decimal value into my input as 29999.99.  The weird thing is that it properly updates the form, like so

 `<input class="" data-val="true" data-val-required="*Name is required." id="Name" name="Name" type="text" value="$29,999.99" />`

And displays on the screen properly, but because of this error it blocks everything else on my page.  I'm really confused trying to track this down, any suggestions?

Further info that may help, my app is an MVC 5 c# app, the field I'm passing is in a text property converted from a decimal backing field, as such

     private decimal _money;

        [Required(ErrorMessage = "Money is required.")]
        public string Money
        {
            get { return _money.ToString(CultureInfo.InvariantCulture); }
            set { _money = decimal.Parse(value, NumberStyles.Currency); }
        }

This is my simple javascript init call(this is just a test, I'm playing around, I'd really like to use this plugin if I can make it work for me :) )

     $(document).ready(function() {

            //$('#Description').summernote();

            $('#Name').autoNumeric('init', { aSign: '$', aPad: false, wEmpty: 'sign', lZero: 'deny' });

            $('#Description').summernote(
            {
                onImageUpload: function(files) {
                    sendFile(files);
                }
            });

        });

If I'm leaving anything important out just ask, I'm kind of stumped.

UPDATE:

Apparently this has something to do with the way Razor views work, because it works fine it I replace the razor syntax with a standard html 5 input, like so.

    @Html.TextBoxFor(model => model.Name, new {@class = ""})

changed to 
    
     <input class="" data-val="true" data-val-required="*Name is required." id="Name" name="Name" type="text" value="@(Model != null ? Model.Name :"0")">

And everything works, now I'm just not sure why :)

**Comment by BobKnothe** [comment]
Joshua,

Did you close because you found a solution?

Bob


 
Robert (Bob) Knothe

**Comment by jlaustill** [comment]
No, I closed because I concluded that it was an issue with MVC/Razor not with your library.  I could be wrong...

**Comment by BobKnothe** [comment]
Joshua,

I have not used MVC Razor but I created a option to handle asp.net issued on postback

Look at "anDefault" and set that to the default value -example anDefault: "1234.56"

Bob

 
Robert (Bob) Knothe

**Comment by jlaustill** [comment]
Learn something new everyday!  This works as well, which I guess confirms that it is an asp issue, I didn't put to and two together looking through the doc page, so thank you for pointing that out!  Now I have at least 5 ways to work around this issue :)

**Comment by BobKnothe** [comment]
Joshua,

If you do not have default values you can also make aForm: false. 

Anyway glad you found a workaround. 

Best regards,

Bob


 
Robert (Bob) Knothe

**Comment by jlaustill** [comment]
So another issue with this.  If I use a class = "an" and have multiple labels on one page, then initialize with anDefault, it only seems to work for the first one, then throws the same error on the second one.  This isn't a HUGE deal since I can just format for labels in my controller easily enough, and I'm only using one input on the input screens I really need this for.  Just more of an FYI.

**Comment by BobKnothe** [comment]
Will check on this over the weekend
 
 
--------- Original Message --------- Subject: Re: [autoNumeric] jquery error when value prepopulated (#182)

**Comment by BobKnothe** [comment]
Joshua,

Can you please replace line 953 to 955 with the following and let me know if that solves your label issue.

Thanks,

Bob

```javascript
if ($.inArray($this.prop('tagName').toLowerCase(), settings.tagList) !== -1 && $this.text() !== '') {
	if (settings.anDefault !== null) {
		if (settings.anDefault === $this.text()) {
			$this.autoNumeric('set', $this.text());
		}
	} else {
		$this.autoNumeric('set', $this.text());
	}
}
```

**Comment by jlaustill** [comment]
Oh wow, you just made me realize I was doing this wrong.  I don't always catch on the fastest!  The issue is that I'm loading content dynamically with AJAX, then refreshing the labels.  So just bypassing the asp.net razor call seems to do the trick.  Before, I was setting it to the value of the first label, which must have been causing my issue?  Now I have this and it works

    .done(function (partialViewResult) {
                $("#items").append(partialViewResult);
                $('.an').autoNumeric('init', { aSign: '$', aPad: true, wEmpty: 'sign', lZero: 'deny', mDec: '2' });
                $('img').on('error', function () {
                    this.src = '/Content/missing.jpg';
                });
            $('#loading').hide();
        });

My label is now 
    <span class="an">@Model.Items[i].Price</span>

Before it was 
    @Html.LabelFor(m => m.Items[i].Price)

So by just not using razor it seems to solve the issue.  I'm getting to the point that I only use the razor calls when I HAVE to, the rest of the time they just seem to break perfectly good code...

Replacing likes 953 to 955 and using razor still seems to break this because an anDefault can only be set once unless I give each label a dynamic id and loop for each one.  Otherwise they would never match $this.text()?  This really is STUPID how asp.net does this.  So I think I'll just stick with not using it. 

And now I feel like I have wasted your time, I'm sorry :(

**Comment by jlaustill** [comment]
Also, to see how I'm using this you can browse to http://pennypincher.ninja .  I've only been working on this site for a few weeks, so it's pretty rough :)

**Comment by BobKnothe** [comment]
Joshua,

Thanks for testing.

ASP has caused me many headaches and mods because they want to do things 
differently.

I do not develop in ASP and my knowledge is limited so it good when 
developers "you" to catch these issues - thanks.

Best regards,

Bob

**Comment by TuyNguyen** [comment]
I had set aForm:false. It's work

**Comment by BobKnothe** [comment]
Glad you found your solution

Please close the issue if you are satisfied
