### ISSUE TITLE
Manage invalid results when trying to paste any number

### ISSUE THREAD

**Issue by deepaknarayanan** [BobKnothe/autoNumeric#183]
I know this is not a issue, where paste event is poorly supported across browsers.

But I have a suggestion. I was wondering if you think this would be a better solution:

If I have set the vMax to 999 and the user is trying to paste say 1234, could you make sure that when paste is complete, it will only show the value as just 123 (since you know that field max is 999, you could strip out the 4)?

I also use phone number masking provided by Igor (https://igorescobar.github.io/jQuery-Mask-Plugin/). Here when I try to paste a phone number as 12345678901 (using Control-V or Shift-Insert or Mouse paste), the value that gets displayed is just 123-456-7890.

I am currently testing this on Chrome: Version 46.0.2490.86 m

Please share your thoughts. As always, I sincerely appreciate the effort you put in for autoNumeric. It works like a charm!

**Comment by BobKnothe** [comment]
Thanks for your interest in autoNumeric. 

I have not considered truncating. While it is interesting and possible I have questions. Pasting and truncating into an empty input is straight forward. What should happen if the value being pasted is at the beginning or middle of an input that already has a value? Truncate or void the paste?

Bob

 
Robert (Bob) Knothe

**Comment by jlaustill** [comment]
I view this as a VERY useful feature as well.  My suggestion would be to always truncate the end to fit the space.  if max is 9999, and the field contains 56, and they try to paste 1234 in the middle, take the 12 and paste it to get 5126.  if they paste at the begging, 1256, at the end 5612. 

This would be great!

**Comment by deepaknarayanan** [comment]
I would agree to that as well.
 
 
  On Wed, Dec 9, 2015 at 5:42 PM, Joshua Austill<notifications@github.com> wrote:   
I view this as a VERY useful feature as well. My suggestion would be to always truncate the end to fit the space. if max is 9999, and the field contains 56, and they try to paste 1234 in the middle, take the 12 and paste it to get 5126. if they paste at the begging, 1256, at the end 5612. 

This would be great!

**Comment by BobKnothe** [comment]
You are piling on the work;-)

Should there be an option that give you the choice on how to handle the pasting?

I if move forward I may add to version 2.0 rather than update 1.9.nn. 

Have either of you looked at the new features in 2.0?

Bob


Robert (Bob) Knothe

**Comment by BobKnothe** [comment]
Should it always be truncated or the max value placed?
 
In either case how does the client easily understand what has occurred?
 
 
--------- Original Message --------- Subject: Re: [autoNumeric] Mouse paste or Shift-Insert (#183)

**Comment by deepaknarayanan** [comment]
Hi Bob, I did not follow what you meant by "Should it always be truncated or the max value placed?"

Based on @jlaustill comment, I think that would make the client easily understand since they are deliberately pasting from the middle. If it gets confusing to the user, they would remove all of the content and then paste what they have.

**Comment by BobKnothe** [comment]
Let say vMax is set to 1234.56 and the user tries pasting 9999 should it be truncated to 999 or replaced with the max 1234.56?
 
 
--------- Original Message --------- Subject: Re: [autoNumeric] Mouse paste or Shift-Insert (#183)

**Comment by jlaustill** [comment]
Would it be possible to set that in the init?  Something like { paste : [ round | truncate | error] }?  I can see uses where rounding to max would be useful, and also uses that truncating to fit would be useful the more I think about this.  I can also see times when I would just want it to silently fail, much like it currently does when you try to type text into it :)  

I would say default it to error, but allow round and truncate to be set?  I dunno, I have no strong opinions on this, it just seems useful more than a deal breaker.

**Comment by deepaknarayanan** [comment]
I would think the easiest solution would be to truncate: if vMax is set to 1234.56 and the user tries pasting 9999 should it be truncated to 999.
In future releases when you introduce errors then you would let the use add options.  
 
  On Thu, Dec 10, 2015 at 7:28 AM, Joshua Austill<notifications@github.com> wrote:   
Would it be possible to set that in the init? Something like { paste : [ round | truncate | error] }? I can see uses where rounding to max would be useful, and also uses that truncating to fit would be useful the more I think about this. I can also see times when I would just want it to silently fail, much like it currently does when you try to type text into it :) 

I would say default it to error, but allow round and truncate to be set? I dunno, I have no strong opinions on this, it just seems useful more than a deal breaker.

**Comment by deepaknarayanan** [comment]
Hi Robert,

Not trying to put pressure :-) but do you think you would be able to put in a fix for this in the near future?

**Comment by deepaknarayanan** [comment]
Hi Robert,
Not trying to put pressure :-) do you think you can put in a fix for this in the near future?

**Comment by BobKnothe** [comment]
I am very business at my job that pays the rent.Maybe I can add this feature by early next year.


-------- Original Message --------
Subject: Re: [autoNumeric] Mouse paste or Shift-Insert (#183)

**Comment by AlexandreBonneau** [comment]
I'm currently working on a feature that would allow you to specify what happens when a paste results in an invalid value (ie. out of minimum and maximum range).

The `onInvalidPaste` option will accepts one of those values : 
- `error`
- `ignore`
- `clamp`
- `truncate`

Those options modify the paste behavior :
- If 'error' (this is the default) :
     - Normal paste behavior.
     - Try to set the new value, if it fails, then throw an error in the console.
     - Do not change the input value, do not change the current selection.
- If 'ignore' :
     - Normal paste behavior.
     - Try to set the new value, if it fails, do nothing more.
     - Do not change the input value, do not change the current selection.
- If 'clamp' :
     - Normal paste behavior.
     - Try to set the new value, if it fails, set the value to the minimum or maximum limit, whichever is closest to the paste result.
     - Change the caret position to be positioned on the left hand side of the decimal character.
- If 'truncate' :
     - Truncate paste behavior.
     - Try to set the new value, if it fails (if the result is out of the min and max value limits), then clamp the result.
     - Change the caret position to be positioned on the right hand side of the pasted text.

Would you have any comments on that?

**Comment by AlexandreBonneau** [comment]
Ok, I pushed a pull request (#304) that implements the following options (I modified how `truncate` was working, and added an additional `replace` option.

Here is the excerpt detailing how that works :
```
    /*
     * Manage how autoNumeric react when the user tries to paste an invalid number.
     * - 'error'    : (This is the default behavior) The input value is not changed and an error is output in the console.
     * - 'ignore'   : idem than 'error', but fail silently without outputting any error/warning in the console.
     * - 'clamp'    : if the pasted value is either too small or too big regarding the minimumValue and maximumValue range, then the result is clamped to those limits.
     * - 'truncate' : autoNumeric will insert as many pasted numbers it can at the initial caret/selection, until everything is pasted, or the range limit is hit.
     *                The non-pasted numbers are dropped and therefore not used at all.
     * - 'replace'  : autoNumeric will first insert as many pasted numbers it can at the initial caret/selection, then if the range limit is hit, it will try
     *                to replace one by one the remaining initial numbers (on the right side of the caret) with the rest of the pasted numbers.
     *
     * Note 1 : A paste content starting with a negative sign '-' will be accepted anywhere in the input, and will set the resulting value as a negative number
     * Note 2 : A paste content starting with a number will be accepted, even if the rest is gibberish (ie. '123foobar456').
     *          Only the first number will be used (here '123').
     * Note 3 : The paste event works with the `decimalPlacesShownOnFocus` option too.
     */
    onInvalidPaste: 'error',
```

For more detailed info on how that works, please take a look at the 600 lines [commit](https://github.com/AlexandreBonneau/autoNumeric/commit/ef4caaa7b1d57ccc780e7aacf3bf9d0182ef4b95) ;)

**Comment by AlexandreBonneau** [comment]
This is merged into the `next` branch.

Enjoy!
