### ISSUE TITLE
Disable decimal

### ISSUE THREAD

**Issue by Epenjehem** [BobKnothe/autoNumeric#185]
How I can disable decimal?
I could not find it in documentation
If  aDec set to null it will trigger error vmin and vmax

**Comment by BobKnothe** [comment]
One of two ways

//Use whole numbers only on the min/max
vMax: "9999999999"
vMin: "0"

or

// assign 0 to the mDec option
mDec: "0"

**Comment by Epenjehem** [comment]
Gracias :)
