### ISSUE TITLE
Got the issue with autoNumeric-2.0

### ISSUE THREAD

**Issue by 5webvn** [BobKnothe/autoNumeric#189]
- Line 1701 :
 if (((!/\d/).test(getValue) || Number(getValue) === 0) && settings.wEmpty === 'focus') {
                return '';
            }
- Should be : 
if (!((/\d/).test(getValue) || Number(getValue) === 0) && settings.wEmpty === 'focus') {
                return '';
            }

**Comment by BobKnothe** [comment]
Harry,

Thank you for your contribution.

I will add this to a couple other changes.

Bob

**Comment by BobKnothe** [comment]
posted your fix - thanks again
