### ISSUE TITLE
[Question] About decimal format

### ISSUE THREAD

**Issue by djornada** [BobKnothe/autoNumeric#190]
Hello guys,
I think i dont understood how to do a thing.

Is possbile to fill the value from the right to left?

example: 

Input  | Show
--------|--------
1	 |1
0	|10
0	|1,00
2      | 10,02
Back space	|1,00
0	|10,00

**Comment by BobKnothe** [comment]
That can be accomplished via css. 

Try aligning left. 



 
Robert (Bob) Knothe

**Comment by BobKnothe** [comment]
use the align attribute on the input tag 
<input type="text" align="left" >

or add this to your css  

input[type="text"] {
	text-align:left;
}

**Comment by djornada** [comment]
Thanks for the answer, but it dosent work.

**Comment by BobKnothe** [comment]
After looking more closely at your example it looks like you want the decimal character (comma) to be inserted automatically.

If that is the case, unfortunately autoNumeric does not support that functionality.

**Comment by djornada** [comment]
Thanks for help!
