### ISSUE TITLE
Language specific issues.

### ISSUE THREAD

**Issue by suramah** [BobKnothe/autoNumeric#192]
Hello,

We are using autonumeric for input controls and using following code, it worked fine for all other language except "Polish" language.

$('#inputControl').autoNumeric('init');

While starts typing in the field, when he gets to the 4th digit, the text field gets filled with following format automatically.(with (&#)160 appending with the text). 

1111 changes to `1&#160;160&#160;111`
2222 changes  to `2&#160;160&#160;222`
3333 changes to  `3&#160;160&#160;333`

The above problem we are getting only for Polish language. We tried with the latest version of the plugin (2.0), still having the same issues. Please share your thoughts. 

Best Regards,
Surama.

**Comment by BobKnothe** [comment]
Interesting - I have multiple users from Poland.
 
Which is inserted '160' or ' 160 ' with spaces? From what you are describing the preceding characters are inserted as the thousand separator?
 
Have you tried changing the thousand separator?
 
 
--------- Original Message --------- Subject: [autoNumeric] Language specific issues. (#192)

**Comment by suramah** [comment]
Yes I tried with changing the thousand, still same problem I am getting, Attached a image with the changed text as soon as I type the 4th digit. Not sure in which format it's converting it, I am trying to enter 1111 in this case.

![autonumeric_input](https://cloud.githubusercontent.com/assets/9570510/12976757/6009fcfe-d0ec-11e5-9ce1-8ff916a55a8e.jpg)

**Comment by BobKnothe** [comment]
That is the html entity number for a space.
 
Can you send me your settings?
 
 
--------- Original Message --------- Subject: Re: [autoNumeric] Language specific issues. (#192)

**Comment by BobKnothe** [comment]
Can you post a fiddle?
 
 
 
--------- Original Message --------- Subject: Re: [autoNumeric] Language specific issues. (#192)

**Comment by suramah** [comment]
HTML: 
`<input id="txtAmount" class="txtClass" type="text" />`

JS:
```
<script src="jquery.js" type="text/javascript"></script>
<script src="autoNumeric.js" type="text/javascript"></script>

 $.extend($.fn.autoNumeric.defaults, {
        aSep: '@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberGroupSeparator',
        aDec: '@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberDecimalSeparator'
    });

$(document).ready(function(){
   $('#txtAmount').autoNumeric('init'); 
});
```

**Comment by BobKnothe** [comment]
ASP?


My guess this following = &#160
aSep: '@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberGroupSeparator

 Can you try manually assigning the space and see if you still get the same error. 




Robert (Bob) Knothe

**Comment by suramah** [comment]
With the above `aSep `and `aDec `settings, it's not allowing to manually enter any text in the input control.

**Comment by BobKnothe** [comment]
|I think what is happening the following line is returning "&#160;" and 
autoNumeric sees that as the decimal separator. |||

|aSep: 
'@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberGroupSeparator'|


if you are using a local copy of autoNumeric in the function autoCode 
please insert this line #157

         settings.aSep = (settings.aSep === "&#160;") ? " " : 
settings.aSep; // this new line above line 157
         if (settings.altDec === null && settings.mDec > 0) {

Please let me know if that works.

**Comment by suramah** [comment]
As per the above details, do I need to add the line in the plugin js itself. Following changes I did and now it's handled the 4 digit for polish language. Please suggest if it fine or not.

```
 settings.aSep = (settings.aSep === "&#160;") ? " " :settings.aSep // this is the new line I added now..
        if (settings.altDec === null && settings.mDec > 0) {
            if (settings.aDec === '.' && settings.aSep !== ',') {
                settings.altDec = ',';
            } else if (settings.aDec === ',' && settings.aSep !== '.') {
                settings.altDec = '.';
            }
        }
```

**Comment by BobKnothe** [comment]
One small change add ";" at the end of the line

|settings.aSep = (settings.aSep === "&#160;") ? " " :settings.aSep;|

**Comment by suramah** [comment]
Thank you for the updates. it's solving the mentioned issue with the above changes, but automatically why it's taking ` "&#160;"` in case of polish language after entering 4th digit.

Thanks and appreciate your help here @BobKnothe !

**Comment by BobKnothe** [comment]
My guess it's something to do with ASP

rather then change autoNumeric you could modify the extend function

|$.extend($.fn.autoNumeric.defaults, { aSep: 
'@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberGroupSeparator', 
aDec: 
'@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberDecimalSeparator' 
aSep = (aSep === '&#160;') ? ' ' : aSep; });|

**Comment by BobKnothe** [comment]
While this is the first time this issue has been brought to my attention i may try a mod that would would convert HTML entities to actual characters.

If you are satisfied please close the issue

Best of luck

**Comment by suramah** [comment]
Changed the extend method with following changes and it worked fine.

```
  $.extend($.fn.autoNumeric.defaults, { 
            aSep: (aSep === '&#160;') ? " " : aSep,
            aDec: '@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberDecimalSeparator',
        });

Thank You  @BobKnothe !
```

**Comment by BobKnothe** [comment]
I do not think this is correct.

I am not a ASP expert but i suggest you try this

|$.extend($.fn.autoNumeric.defaults, { aSep: (|||'@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberGroupSeparator'| 
=== '&#160;') ? " " : aSep, aDec: 
'@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberDecimalSeparator', 
});|

**Comment by suramah** [comment]
Hello BobKnothe,

One more problem I am getting after the above changes, the space issue solved after 4th digit entry, but the format for displaying the number is different than other languages which I mentioned above also.

Ex : `121.00 `in case of English, but `121,00 `in case of Polish.
`1, 111, 111.00` in case of English but `1 111 111,00` in case of Polish.

Please help here how to get the same format for Polish same as of English.

Best Regards,
Surama.
