### ISSUE TITLE
Paste problem with {aSep: '\'', aDec: ','}

### ISSUE THREAD

**Issue by Sm1thik** [BobKnothe/autoNumeric#193]
Hello!

I find a problem with pasting when we got options like '{aSep: '\'', aDec: ','}'.
After pasting numbers like 11.23, 4342.423 and so on (with . as separator) become 1'123, 4'342'423 and so on, w/o separators.

I am new in JS, so I didnt find the way to fix it myself.

Sry for my bad english:(

**Comment by BobKnothe** [comment]
Are you pasting with the mouse or keyboard?
 
Withe the string you are pasting what do you expect the outcome to look like?
 
 
 
--------- Original Message --------- Subject: [autoNumeric] Paste problem with {aSep: ''', aDec: ','} (#193)

**Comment by Sm1thik** [comment]
Thx for ur reply!

I tried to paste with mouse and with keyboard, result the same. But when I am pasting with mouse - converting coming after focusout.

What I am expecting
11.23 -> 11,23
4342.423 -> 4'342,42

Something like that, and it's working when I am not using pasting. But its very bad when I am losing data with pasting.

With debug I found, that converting failing here:
s = s.replace(settings.skipFirstAutoStrip, '$1$2'); /** first replace anything before digits */
s = s.replace(settings.skipLastAutoStrip, '$1'); /** then replace anything after digits */
s = s.replace(settings.allowedAutoStrip, ''); /** then remove any uninterested characters */

After this we losing our separator

Hope this helps u to find a problem.

**Comment by Sm1thik** [comment]
I swaped lines
"s = s.replace(settings.skipFirstAutoStrip, '$1$2'); /** first replace anything before digits /
s = s.replace(settings.skipLastAutoStrip, '$1'); /* then replace anything after digits /
s = s.replace(settings.allowedAutoStrip, ''); /* then remove any uninterested characters */"
and 
"if (settings.altDec) {
            s = s.replace(settings.altDec, settings.aDec);
        } /** get only number string */"

And now its working fine. Should i expect some problems after that move?

**Comment by zakius** [comment]
I have the same issue, Sm1thiks solution right or should we expect something else?

**Comment by BobKnothe** [comment]
No I do not believe Sm1thiks is the correct change.

Pasting formatted values into autoNumeric controlled input will cause a issue. This will require a change that is more involved then swapping a couple lines.

**Comment by zakius** [comment]
Yeah, I figured
Thanks for all the good work anyway!

**Comment by AlexandreBonneau** [comment]
A single quote was not allowed as a group separator. I fixed that by allowing it in the character pool (cf. PR #313).

However, pasting is a complicated thing and currently, if you want to paste a number and want its decimal character to be taking into account, you *must* paste a number while that decimal character is declared as the `decimalCharacter` option (this was named `aDec` before).

Hence, in your case, if you paste `11.23`, the `.` will be dropped and you'll obtain `1'123,00`.
If you paste `11,23`, you'll obtain `11,23`.
Lastly, if you paste `4342,423`, you'll obtain `4'342,42`.
