### ISSUE TITLE
Issue - version 2.0 Beta

### ISSUE THREAD

**Issue by alejandrodevs** [BobKnothe/autoNumeric#194]
When I write a 0 number in an autoNumeric input and I blur the input, the input content goes away :(.
version 2.0 Beta

**Comment by BobKnothe** [comment]
> Alejandro,

Please send me your settings and your expected out-come. 

Bob


 
Robert (Bob) Knothe

**Comment by alejandrogutierrez** [comment]
I think If I enter a 0 in an input and I blur it the expected content should be 0.00.
Am I right?

**Comment by TheNightFall** [comment]
I believe the problem relies in the function "function autoStrip(s, settings)"

The issue is in the following regex:

var strip_reg = '^' + settings.aNegRegAutoStrip + '0*(\\d|$)';

AFAICT, It should be:

var strip_reg = '^' + settings.aNegRegAutoStrip + '0*(\\d)';

**Comment by BobKnothe** [comment]
Thanks TheNightFall I will test and post.

**Comment by AlexandreBonneau** [comment]
I tested @TheNightFall solution and it works well, thank you.
I created a [pull request](https://github.com/BobKnothe/autoNumeric/pull/267) to merge that fix into `master`.
