### ISSUE TITLE
Provide a formatting API that is not requires element

### ISSUE THREAD

**Issue by ishaikovsky** [BobKnothe/autoNumeric#195]
Hi, 

This is more of an enhancement request but the one I feel might be beneficial for any such plugin. There are cases in our application where we need just to apply formatting and we don't have the element yet (or might not have it at all). And in this case - we need to create a "synthetic" element set value, initialize autoNumeric, use "get" and finally destroy it. 

I feel that it should not be very tough to provide a "format" method which will get the numerical value and set of formatting settings (same as "init" for the element accepts - and have them defaulted in the same way) and just return the formatted value.

WDYT?

**Comment by BobKnothe** [comment]
Thank you for your interest in autoNumeric.
 
I am not sure I fully understand your request. Are you looking for the ability to format a number that is not attached to an element? If so I had looked at this in the past and it could be accomplished  with some modification but some options (min/max) might be ignored. let me know more details so I can determine the extent of the modification required.
 
Bob
 
 
 
 
--------- Original Message --------- Subject: [autoNumeric] Provide a formatting API that is not bound to an element (#195)

**Comment by ishaikovsky** [comment]
Yeah,, you got it right. I feel that the autoNumeric is an excellent fit for the app I'm working on. 

However we have a very expensive table rendering use-case and so far we avoid initializing any plugins at cell level and in general rendering cells once and then just duplicating them across the table just modifying the values inside. So need the ability "to format a number that is not attached to an element" as you said to make it compatible with our approach.

If the changes aren't big as you say(and I feel they are too by looking at the plugin source) - I'd love to see it added or even help with that.

**Comment by Raylehnhoff** [comment]
I think it would be a good opportunity to split the formatting code away
from DOM manipulation code.

Doing so might be able to simplify code and give a pure formatting library
and a separate DOM manipulation library that would leverage the formatter
library. The biggest advantage is autoNumeric could exist in libraries that
do their own DOM manipulation particularly well, like knockout, react, or
angular without shimming autoNumeric in, if that makes sense.

**Comment by BobKnothe** [comment]
Ray,

Hope all is well. 

If all they need is to format a string that can be accomplish at a fraction of the size of autoNumeric. What other feature can you envision that would be needed?

"set" & "get" methods and???

Bob

 
Robert (Bob) Knothe

**Comment by ishaikovsky** [comment]
Robert, 

That is the thing. We do need all the power of autonumeric in forms. However when it comes to just to display in the cell table (non-editable) - we need this API.

And what we don't want to do - is to introduce another plugin just to format (with different options and so on) assuming we already have autonumeric. 

If I would need just format - yup - will take something more lightweight and task specific.

**Comment by BobKnothe** [comment]
Ilya,

Which version of autoNumeric are you using?

I can modify and send you a custom version.

At this time I am not sure I want to add this as a supported feature.

Bob

**Comment by ishaikovsky** [comment]
I use 

autoNumeric-1.9.43

thanks!

**Comment by BobKnothe** [comment]
After consideration I have decided not to mod autoNumeric to include your requested feature.

I would only take a few lines of code to format numeric strings that could easily be a stand alone script and adding the to AN would be overkill.

Again thanks for your interest in AN
