### ISSUE TITLE
autoNumeric('get') returns error

### ISSUE THREAD

**Issue by gigallo** [BobKnothe/autoNumeric#197]
Hi

I've got a simple input for the price but when I execute the code
$('#price').autoNumeric('get');

an error is thrown:
autoNumeric-min.js:35 Uncaught TypeError: false.test is not a function(…)

**Comment by BobKnothe** [comment]
Please try using the unminified version.

It is also very help to post a jsfiddle so i can see first hand.

Thanks,

Bob

**Comment by gigallo** [comment]
I've solved with the 2.0 version. When will it be definitive?
