### ISSUE TITLE
Windows 10 Mobile - double clicked number

### ISSUE THREAD

**Issue by jirkae** [BobKnothe/autoNumeric#198]
Hello,

please I have following problem: When I click on number, for example 5, it write 55. Backspace works fine. Withou this plugin it works.

Thanks for help.

**Comment by BobKnothe** [comment]
Can you try both 1.9.43 * version 2 and let me know the results.

**Comment by jirkae** [comment]
Same behauvior

**Comment by jirkae** [comment]
Find out the probblem probably. You are stopping default browser behauvior of inserting chars and you insert it your own way, right? Problem is, that the stopping dont work on WM. When I stop calling processKeypress function, it works like a charm (but it doesnt work on all other devices :D )

**Comment by AlexandreBonneau** [comment]
Hello @jirkae , since issue #292 has been fixed, `input` and `change` events are now correctly sent.

Could you please test again with the latest version found in the `next` branch?

Thanks!

**Comment by AlexandreBonneau** [comment]
Due to inactivity, I'm closing this issue considering it resolved.

If that's not the case, feel free to re-open it!
