### ISSUE TITLE
autoNumeric prefixes 0 to the amount

### ISSUE THREAD

**Issue by vandamon** [BobKnothe/autoNumeric#200]
autoNumeric prefixes 0 to the amount in some instances.

All the amount values have the same class that is being used to init autoNumeric from JS.

```
$(".dollar_value").autoNumeric('init', { aSign: '$' })
```

![autonumeric prefixes 0](https://cloud.githubusercontent.com/assets/1415261/14402166/81a99916-fe49-11e5-8f9d-a9a76f3b5f61.png)

**Comment by BobKnothe** [comment]
need to see a jsFiddle so I can see under what circumstances this is happening.

**Comment by Raylehnhoff** [comment]
@vandamon,

I attempted to create a jsbin for your issue using what i could infer. I'm not seeing this happening using the current stable version of autoNumeric:

It does seem that in the latest stable version, trying to call autoNumeric.init on a HTML node with the text "$490.00" throws an autoNumeric exception.

Please see: http://jsbin.com/wobugoduru/edit?html,js,console,output

**Comment by vandamon** [comment]
@Raylehnhoff 

Thanks a lot for that jsbin. I was trying hard to get time and do it myself.

Anyway, I tweaked your HTML code, and the result is the same as I have reported.

Here is the modified jsbin: http://jsbin.com/suheweloba/edit?html,js,console,output

**Comment by Raylehnhoff** [comment]
Hi @vandamon,

What browser are you using? In Chrome-latest the formatting is what I'd expect:

http://imgur.com/vhdDYsR

**Comment by vandamon** [comment]
Okay I tried to replicate the way it is happening on my site with tables, it is working fine here. Not sure, why it is not working on my site.

http://jsbin.com/jugaguhace/1/edit?html,js,console,output

Might be because I am using autoNumeric-rails gem in my Rails app.

**Comment by Raylehnhoff** [comment]
It looks that version is quite behind:

https://github.com/randoum/autonumeric-rails

You could try doing it without that gem and seeing if it still happens. If it only happens when using aN via the gem, the issue should be opened with that fork.

**Comment by BobKnothe** [comment]
Thanks Ray for your help and answers

vandamon - I suggest that you contact randoum and see if he will update.
