### ISSUE TITLE
how set value (empty, '') version 2

### ISSUE THREAD

**Issue by renandegrandi** [BobKnothe/autoNumeric#205]
In AutoNumeric 1.9.41
exists the property  wEmpty: 'empty' which	allows input to be empty (no value) (default)

to clear the value I used (element.autoNumeric('set', '');

but in version 2.0
wEmpty don't have the  empty option and in the specification it appears that the property is no longer used for this.

In version 2.0 i used element.autoNumeric('set', ''), in my screen value is empty, but, in element, (element.val()), the value is equals to oldValue. 
I looked at the code and found this line.

Method: set:

if(value != '') {  //code } else { return '' } 

it clears the screen, but doesn't reflect to the element, it's  needed apply $(this).val('') to update the value.

is this correct or not ?,Is there something prepared for this situation?

**Comment by BobKnothe** [comment]
Yes I modified wEmpty on version 2.0.

Please note the following changes in version 2 that may effect how you 
clear the field:

In version 2.0 autoNumeric saves the value in jQuery data attached to 
that element. So i created a new method "wipe" that clears the input as 
well as the data.

So rather then use element.autoNumeric('set', '') try the new method 
element.autoNumeric('wipe') which should clear the element and attached 
data.

Please let me know if I correctly understood your issue.

Bob
