### ISSUE TITLE
Keypress problem

### ISSUE THREAD

**Issue by jirkae** [BobKnothe/autoNumeric#206]
Hi,

I find out, that you use event "keypress". It is not best option to do that. Keypress is not triggered on some devices/browsers, For now it generate me problem on Android native browser when it is not formatting when I click on number.

Can you please consider using just keydown/keyup instead?

Thanks a lot

**Comment by AlexandreBonneau** [comment]
I just tested with Chrome 55.0.2883.91 under Android, and the formatting works ok.

Please re-open that issue if the latest version in the `next` branch does not solve your problem.
