### ISSUE TITLE
Error with dynamically created elements

### ISSUE THREAD

**Issue by wickedsp1d3r** [BobKnothe/autoNumeric#207]
Hello,

I get this error when I init the plugin to dynamically created elements:
`Uncaught TypeError: Cannot read property 'nodeName' of null`

I have tried:

- To perform a check if data attribute `autoNumeric` is `undefined`
- To destroy autoNumeric elements before creating them

Thank you in advance.

**Comment by Raylehnhoff** [comment]
Please attach a jsbin or fiddle of a situation that reproduces this,

**Comment by wickedsp1d3r** [comment]
I have a Handlebars template and after drawing it, I try to attach aN to all input elements with a specific class. This is when this particular errors comes in.

**Comment by BobKnothe** [comment]
What error are you receiving?



 
Robert (Bob) Knothe

**Comment by wickedsp1d3r** [comment]
![err](https://cloud.githubusercontent.com/assets/1852854/16089189/b2d54ef4-3332-11e6-87ca-83383f439108.png)

**Comment by BobKnothe** [comment]
From the error message it does not appear to because by aN

Can you post a fiddle so I can dig deeper?

 
Robert (Bob) Knothe

**Comment by BobKnothe** [comment]
Is it giving a line number with aN that is throwing this error?

 
Robert (Bob) Knothe
