### ISSUE TITLE
Formatting variable instead of input value?

### ISSUE THREAD

**Issue by zakius** [BobKnothe/autoNumeric#208]
I know it isn't exactly purpose of this library, but it's flexibility is great and I'd like to use this power a bit more.
I'd like to be able to format any strings containing numeric values as additional feature if it is possible

**Comment by BobKnothe** [comment]
It is possible to modify autoNumeric to accomplish your request but in the interest of size and focus I have decided not to incorporate that functionality into autoNumeric. 

Formatting a string is simple and would only take a couple few lines a code to accomplish.
