### ISSUE TITLE
autonumeric not working after cloning input elements

### ISSUE THREAD

**Issue by alexladerman** [BobKnothe/autoNumeric#209]
autonumeric not working after cloning input elements.Typing into duplicate input fields changes the values on the original. It seems as though the event.target on the new fields still point to the original elements. Table row is cloned using jquery.clone(withDataandEvents). I have tried invoking calling init and update after the cloning, both to no avail. See video of behaviour https://drive.google.com/open?id=0B0ppQTtnar5TblA3cHo5WF9tY1E

**Comment by BobKnothe** [comment]
Alex,
 
What selector are you using when calling the "init" method on the cloned input?
 
You will need to use a unique selector (#id or .eq()).
 
Bob
 
--------- Original Message --------- Subject: [BobKnothe/autoNumeric] autonumeric not working after cloning input elements (#209)

**Comment by alexladerman** [comment]
I thought about that, that your plugin is  storing references. But after a
glance at your code and seeing event.target.iv, I presumed the event just
passed through to the handler the element it had been triggered on.

I am using a class selector with init at page load. I have also been trying
this but doesn't work either
https://github.com/BobKnothe/autoNumeric/issues/201 The JSfiddle works if
you change init to update in the example.

How would I apply by ID? I'd have to assign every element in the clone an
ID then loop through them all calling $(#id).autoNumeric('init', options)
on each one? How does that differ from the solution above?

thanks


On 27 Apr 2016 03:13, "Bob Knothe" <notifications@github.com> wrote:

Alex,

What selector are you using when calling the "init" method on the cloned
input?

You will need to use a unique selector (#id or .eq()).

Bob

--------- Original Message --------- Subject: [BobKnothe/autoNumeric]
autonumeric not working after cloning input elements (#209)

**Comment by alexladerman** [comment]
I found the $(element).autoNumeric('destroy') method which finally did the trick. Here is what I did:

var init_input_masks = function(elem) {
    $(".input_decimal", elem).autoNumeric(input_decimal_options);
    $(".input_integer", elem).autoNumeric(input_integer_options);
};
//on load
init_input_masks(document);

//called when new line of input fields is added by cloning
var reset_input_masks_on_clone = function(newline) {
  $('.input_decimal', newline).each(function(){
    $(this).autoNumeric('destroy');
    $(this).autoNumeric('init', input_decimal_options);
  });
  $('.input_integer', newline).each(function(){
    $(this).autoNumeric('destroy');
    $(this).autoNumeric('init', input_integer_options);
  });
}

**Comment by AlexandreBonneau** [comment]
Hello @alexladerman , if you feel you solved your problem, please consider closing this issue.

Given this one is pretty old, I'll close it in a month if no other comments are made.
Feel free to re-open it if needed.
