### ISSUE TITLE
Error with autonumeric 1.9.25

### ISSUE THREAD

**Issue by Alexandre46** [BobKnothe/autoNumeric#211]
When I put price for example 1,500.99 he rounds 150.00 , is some function of autonumeric js?
I remove truncate decimals, remove string to real number...
and nothing works

Can anyone help me?

**Comment by BobKnothe** [comment]
Looks like you are using an old version - try autoNumeric 1.9.43https://github.com/BobKnothe/autoNumericAfter switching let me know if the issue is still present


-------- Original Message --------
Subject: [BobKnothe/autoNumeric] Error with autonumeric 1.9.25 (#211)

**Comment by Alexandre46** [comment]
I try minified 1.9.43 autonumeric.js but don't work.I'm trying to put 458,99€ and they give 458,00€I don't understand...

Alexandre Abreu


Date: Thu, 5 May 2016 05:16:29 -0700

**Comment by Raylehnhoff** [comment]
Please attach a jsbin or fiddle that reproduces this issue.

**Comment by BobKnothe** [comment]
Alex 

Try the un-minified version

Bob

 
Robert (Bob) Knothe

**Comment by Alexandre46** [comment]
I try everything... verson 2.0 BETA , and other versions too..

Maybe anything bugging in my wordpress? I use WP Adverts plugin

**Comment by Alexandre46** [comment]
250,000.00€ he convert to 250,00€

**Comment by BobKnothe** [comment]
posted new version
