### ISSUE TITLE
autoNumeric input field and accesskey doesn't work as expected

### ISSUE THREAD

**Issue by movalz** [BobKnothe/autoNumeric#212]
Normal behaviour of browser when jumping into an input field via accesskey (or tab key) is to select the current input so that the user can replace it by new input by just typing, and an autoNumeric field should behave in the same way, but it doesn't.

I have an HTML file where I use a label and an input field together and the label defines the accesskey for the input field:

&lt;label for='in1' accesskey='I'&gt;...&lt;/label&gt;
&lt;input id='in1' type='text' value='...'/&gt;

and autoNumberic('init', {options}) is called for 'in1'.

When I hit the access key 'I' the focus is set to the inputNumber (as expected) and for a very short time the current value of the inputNumber field is selected (as expected too) but this selection of the characters of the inputNumber is lost after some milliseconds.

I have searched for the reason and found following code in autoNumeric.js which causes this loosing of the text selection:

```
formatQuick: function () {
    ...
    this.that.value = value;
    this.setPosition(position);
    this.formatted = true;
}
```

A solution seems to be to check if the new value is the same as the current value and to omit this assignment and setPosition() call in that case. I have tested following fix:

```
if (this.that.value !== value) {
    this.that.value = value;
    this.setPosition(position);
}
this.formatted = true;
```

and it solved this issue.

Version of autoNumeric I use is 1.9.43

**Comment by BobKnothe** [comment]
movalz,

Sorry for the delay - I have implemented your mod.

Thanks,

Bob
