### ISSUE TITLE
Add the library to the jsDelivr CDN

### ISSUE THREAD

**Issue by saruman** [BobKnothe/autoNumeric#213]
Hello.
This is not an issue, but I don't know how to contact you.
Please add your project in http://www.jsdelivr.com. 

Thank you.

**Comment by AlexandreBonneau** [comment]
It's now in the todo list, thanks for pointing this to us @saruman .

For info for ourselves, the [steps](https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md) to add the project to jsdelivr.

**Comment by AlexandreBonneau** [comment]
A push request have been made to fix that issue, cf. https://github.com/jsdelivr/jsdelivr/pull/15571

**Comment by AlexandreBonneau** [comment]
Ok, https://github.com/jsdelivr/jsdelivr/pull/15571 is merged, and you can see the autoNumeric library on [that link](http://www.jsdelivr.com/?query=autonumeric).
