### ISSUE TITLE
Submit data via enter on keyboard not working

### ISSUE THREAD

**Issue by haifahrul** [BobKnothe/autoNumeric#214]
Hi @BobKnothe , i founded a bug.

When I am entry data form textInput and directly submit with press enter on keyboard ( I mean not go to submit button ), the data not saving in to database.

I hope this can be solved, thanks.

**Comment by BobKnothe** [comment]
Ahmad,

I would like to help but will need more detailed information too do so.

  * Which version of autoNumeric are you using?
  * Are you using a key event to submit the value to the data base? And
    if so which key?


Bob

**Comment by haifahrul** [comment]
Hai Bob,

* I using version 1.9.43, 
* I'm not using key event to submit data, i just using this code to mask money and Directly submit in that form, data not save
``` JAVASCRIPT
$(document).ready(function() {
    $(selector).autoNumeric("init",{
        'aForm' => true,
        'aSep' => '.',
        'aDec' => ',',
        'aPad' => false,
        'aSign' => ' IDR',
        'pSign' => 's',
    });
});
```

**Comment by BobKnothe** [comment]
Ahmad,

I autoNumeric working at all?

This is the format that options should be submitted

$(document).ready(function() {
     $(selector).autoNumeric("init",{
         aSep:  '.',
         aDec:  ',',
         aPad:  false,
         aSign:  ' IDR',
         pSign:  's'
     });
});


Bob

**Comment by haifahrul** [comment]
Sorry, i have do that,
but i founded **TypeError: e is undefined**
``` JAVASCRIPT
...);return t.eq(0).data("autoNumeric")}};e.fn.autoNumeric=function(t){return S[t]?...
```

**Comment by BobKnothe** [comment]
Ahmad,

I would really like to help but I need a lot more information and examples. Like this error message below that you sent. Was this in the browser console.

What I really need is a example posted on jsBin or jsFiddle - that way I can see the error.

Sorry, i have do that,
but i founded TypeError: e is undefined

...);return t.eq(0).data("autoNumeric")}};e.fn.autoNumeric=function(t){return S[t]?...

**Comment by haifahrul** [comment]
Hallo,
Sorry, this is my mistake.
I have made this one https://github.com/haifahrul/yii2-autonumeric, and forget to using keyup.

Thanks before for your attention.
Cheers :smile:

**Comment by Zsavajji** [comment]
Hi, i searched a bit on this issue, and i found no real solution working for me. 
The problem is not related to the autoNumeric version used, and throws no errors in console.
Simply, after including autoNumeric on page, submitting any kind of form on the site by pressing Enter gets disabled. Is this the intended behavior? 
I'm now testing the keydown event myself to let the forms submit, but i feel like it's more of a workaround.
Any idea?
