### ISSUE TITLE
Dynamically removing input

### ISSUE THREAD

**Issue by jreason** [BobKnothe/autoNumeric#215]
I have a form where i dynamically add and remove inputs.

When i dynamically add inputs and submit a form, everything works well as expected.

When i dynamically remove an input and try to submit the form i get the following javascript error:
Uncaught TypeError: Cannot read property 'settingsClose' of undefined

I have tried calling 'destroy' on the inputs before i remove them completely but i still get the error?

I am using version: autoNumeric-1.9.43
I am using the latest version of Chrome, i have also testing using Firefox and still have the same issue.

**Comment by BobKnothe** [comment]
Thanks for your interest in autoNumeric.

I do not have a item/property named "settingsClose" in 1.9.43 so not sure where the error is coming from.

Can you post an example on jsbin or jsfiddle?

**Comment by jreason** [comment]
Sorry that was a typo, it should have said settingsClone

**Comment by jreason** [comment]
Here is a JSBIN example: http://output.jsbin.com/xurayu

Using Chrome, F12 and look at console.
Press the Delete button to remove the column.
Press Save Pricebook Data.
You will have to be quick to see the error so best to print screen.

Effectively it stops the form from posting and tries to turn the post into a get request.

**Comment by Raylehnhoff** [comment]
You need to use the autoNumeric methods `$(target).autoNumeric('get')` and `$(target).autoNumeric('set', value)`

The way you're getting/setting the values is not valid for this plugin.

**Comment by jreason** [comment]
The input values are entered by the PHP code.
Once the page has been loaded, i am calling init to initialize the inputs. Is this not the way to do it?

It appears to be working ok like this, the only issue i am having is when a customer wants to remove inputs. What is the correct way to do this?

**Comment by BobKnothe** [comment]
Unfortunately the JSBIN page is not functioning for me (ICANN_NAME_COLLISION).

Can you try and use a local copy and change line 1116 from

 $this.off('.autoNumeric');
to this 
 $this.off('autoNumeric');

and let me know

**Comment by jreason** [comment]
Hi Bob,

I have made the change and all is now working as expected!

Thank you!

**Comment by BobKnothe** [comment]
uploaded v 1.9.44 that corrects this issue.
