### ISSUE TITLE
$('#number).val() returns formatted number

### ISSUE THREAD

**Issue by rui-ribeiro** [BobKnothe/autoNumeric#216]
Hi,

I´m having a problem with your plugin.

So this is a example scenario:

You have a input box initialized with autoNumeric and the text is the following:

**156.300.00**

So the raw number is **156300.00**

If we call $('#number).autoNumeric('getValue') 
returns 156300.00 

But...
 if we call $('#number).val()
returns 156.300.00 

My problem is I need to .val() to return the raw number so when I submit the form the value goes like a real number and not a string.

I created a valHook, and attached it to .val() so now it returns the raw number. But this gave me another problems, because autoNumeric uses .val() and it create a bug.

Can you make fields with autoNumeric hooked returns the raw number on .val()?

Thanks

**Comment by BobKnothe** [comment]
While I am sure it is possible changing at this point likely will effect many users and for this fact alone I am reluctant to make this mod.
