### ISSUE TITLE
[Feature request] Callback when input change

### ISSUE THREAD

**Issue by kouts** [BobKnothe/autoNumeric#217]
Hi, is there a callback available for when the input changes (ie after formatting takes place).
It would be usefull for data binding libraries.

Thanks.

**Comment by BobKnothe** [comment]
You already have the change event being thrown on focus out if the value has changed.

Other then a custom event what you you looking for in the callback?

**Comment by kouts** [comment]
I would like a callback to be fired essentially inside the autoGroup method just before it returns the formatted value. That way my data model will stay in sync with the value typed by the user. I have run into a situation that the form gets submitted without the input losing focus so the value didn't change.
I'm using [Ractive.js](http://www.ractivejs.org/) for two way data binding.

Thanks.

**Comment by kouts** [comment]
I've created a pull request for this #218 maybe you can take a look for a more elegant way?

**Comment by BobKnothe** [comment]
Have you looked at version 2.0?

I created a setting not too different from your idea that holds the raw value and can be accessed at any time via $(selector).autoNumeric('getSettings').rawValue;

It says beta but is widely used without issue.

**Comment by kouts** [comment]
That's nice, but I need to know when the value changed so that I can update my model with the new value.

**Comment by BobKnothe** [comment]
I am trying to use 1.9.xx as as a LTS and only release fixes and use 2.0 
for new features that way I am not doing double work.

Don't get me wrong I like the concept. in fact i could use something 
like this to allow developers the ability to tell a client they are 
trying to exceed the mim/max values/

Two things on your suggestion.

  * the autogroup function is used even when the value does not change
  * where you have placed the "settings.callbacks.afterConvert(iv);"
    negative value could be returned with brackets if specified.

Bob

**Comment by kouts** [comment]
Ok thanks, so I'm going to use v2, where do you think it is appropriate to put the afterConvert callback?
Do you have any plans to incorporate this functionality?

**Comment by BobKnothe** [comment]
I am not an expert on reactive and was hoping you could post and example on fiddle showing how you would use your suggested mod with reactive.

Thanks.

**Comment by eskawl** [comment]
I tried using the plugin in a react component.  https://jsfiddle.net/eskawl/nm60jzLr/4/

The change event doesn't fire when the input loses focus.
However the change event is fired normally on focus lost, when used outside react.

**Comment by BobKnothe** [comment]
I forked your fiddle and added embedded autoNumeric and can see your issue.

On focus out and added a console line where the change event is generated https://jsfiddle.net/KodeKutz/v1p2e2ak/ so I know it is being thrown but under react it appears to be suppressed.

Have you also contacted the React team?

**Comment by kouts** [comment]
Here is an example on jsfiddle: http://jsfiddle.net/ufwzyh9c/1/

**Comment by kouts** [comment]
So where would be a most suitable place to put the callback method in order to have indication that the value has been formatted? Either in v1 or v2 suits me fine!

**Comment by AlexandreBonneau** [comment]
As you can see, a new event `'autoNumeric:formatted'` is sent when the value is...formatted.

This has been introduced when fixing issue #187.

I'm closing this issue since this should solve your problem.
Feel free to re-open it if it does not.
