### ISSUE TITLE
Support .val() initialization

### ISSUE THREAD

**Issue by rstarkov** [BobKnothe/autoNumeric#220]
When I create an input element and initialize it using the `value` _attribute_, it starts out properly formatted:

    $('#txt3').attr('value', '2000').autoNumeric('init'); // works

But if I set the _property_, it doesn't:

    $('#txt2').val('2000').autoNumeric('init'); // initially unformatted

JsFiddle demonstrating this behavior: https://jsfiddle.net/a1h8kzkn/1/

Could autoNumeric support the `val` scenario?

**Comment by BobKnothe** [comment]
Roman,

Thanks for the fiddle makes it easy to track.

This is the "$this.prop('defaultValue')" causing your issue in line #980. This was put in to compare the default value with against a value that is entered or in your case place with jQuery val() method. This is important when the page looses focus and then regains.  

I am not sure how to change this without causing other issues.

This is the preferred way to set a value when using autoNumeric: 

"$('#txt2').autoNumeric('init').autoNumeric('set', '2000');" 

 Bob

**Comment by BobKnothe** [comment]
After looking at this I feel change would cause more issues than worth the change.

Hope you use my recommendation or find another solution.
