### ISSUE TITLE
Cursor Positioned At End of Input Field When Tabbing in Chrome

### ISSUE THREAD

**Issue by dennismsmith** [BobKnothe/autoNumeric#221]
When navigating between autoNumeric fields in Chrome, the cursor is always positioned at the end of the input field.  In all other browsers, the contents of the field is selected, allowing the user to start typing to overwrite the contents of the input field.

**Steps to Reproduce:**
1. Open the [attached example file](https://github.com/BobKnothe/autoNumeric/files/342185/autoNumeric_tab_test.zip) in Firefox or IE11

1. Click/tab into the first input field

1. Press Tab to navigate to the next input field

  * Note that the entire input field is highlighted (expected)

1. Type some numbers

  * Note that the numbers that you typed have replaced the text of the input field (expected)

1. Open the attached example file in Chrome

1. Click/tab into the first input field

1. Press Tab to navigate to the next input field

  * Note that the cursor is at the end of the input field and the contents are not highlighted (unexpected)

8. Type some numbers
  * Note that you can't type any numbers without deleting content first, presumably because the cursor is after the last supported decimal digit

**Test Environment**
* Windows 7 SP1
* Chrome 51.0.2704.106
* Firefox 47.0
* Internet Explorer 11.0.9600.17959, Update Versions: 11.0.22(KB3078071)

**Comment by BobKnothe** [comment]
it would really help if you post a fiddle or codepen so I can test quickly.

**Comment by dennismsmith** [comment]
I've created a post on jsfiddle based on the attachment: [https://jsfiddle.net/3t1tw7ap/1/](https://jsfiddle.net/3t1tw7ap/1/) .

**Comment by BobKnothe** [comment]
Dennis

Thank this make it easier.

Looks like to issue is associated when negative brackets are assigned regardless if the value is positive or negative. Please try and confirm.

I will see if there is a easy fix - i hope. Sometimes browsers specific issues can be very difficult.

Bob

**Comment by dennismsmith** [comment]
Yes, if I remove the negative brackets, this problem goes away.

**Comment by BobKnothe** [comment]
Dennis,

If you could test the follow it would be appreciates - replace the "keyup" event with the following and let me know:

Bob
                    $this.on('keyup.autoNumeric', function(e) {
                        holder = getHolder($this);
                        holder.init(e);
                        var skip = holder.skipAllways(e),
							tab = holder.kdCode;
                        holder.kdCode = 0;
                        delete holder.valuePartsBeforePaste;
                        if ($this[0].value === holder.settings.aSign) { /** added to properly place the caret when only the currency is present */
                            if (holder.settings.pSign === 's') {
                                setElementSelection(this, 0, 0);
                            } else {
                                setElementSelection(this, holder.settings.aSign.length, holder.settings.aSign.length);
                            }
                        } else if (tab === 9) {
							setElementSelection(this, 0, $this.val().length);	
						}
                        if (skip) {
                            return true;
                        }
                        if (this.value === '') {
                            return true;
                        }
                        if (!holder.formatted) {
                            holder.formatQuick();
                        }
                    });

**Comment by dennismsmith** [comment]
Hi Bob,

Patching in the code you attached appears to resolve the problem for me.  Thanks for your help.

Dennis

**Comment by BobKnothe** [comment]
Dennis,

I have used your patch - thanks for the contribution.

Bob

**Comment by BobKnothe** [comment]
Dennis,

Hope all is well.

FYI - your fix has created a minor issue that if you tab into the input with a single digit and then type the same digit the number stay selected - see http://jsfiddle.net/hzm9cLcj/5/

so I was trying the develop a solution while testing Chrome 54.0.2840.87 it appears they have corrected the issue you discover. Can you please test and confirm?

If chrome has been fixed and can reverse you fix and solve both issues.

your help is appreciated

Bob

**Comment by dennismsmith** [comment]
Hi Bob,

I tested again with Chrome 54.0.2840.87 and I’m still seeing the same problem with both my application and the jsfiddle from my original bug report (https://jsfiddle.net/3t1tw7ap/1/).  Your jsfiddle appears to work correctly for me.

That being said, I’m not sure what is really different between my jsfiddle and yours that would cause this difference, though, as they seem substantially similar.

Thanks for your help.

Dennis
