### ISSUE TITLE
Can't set input to Zero (issue with version exposed through bower)

### ISSUE THREAD

**Issue by TCattd** [BobKnothe/autoNumeric#224]
v1.9.42, the latest exposed in bower (greatest tagged version in the repo), has the following bug.

This is how my input is set up:

```
<input id="howmanycars" name="howmanycars" type="text" placeholder="0" required />
```

```
		$('#howmanycars').autoNumeric('init', {
			aSep: '.',
			aDec: ',',
			aSign: '',
			vMin: '0',
			vMax: '1000',
			mDec: 0,
		});
```

Wherever i put a 0 in that input, and the input loses focus, the 0 is cleared and the placeholder content is visible again.

If i manually update your lib to v1.9.45 from the repo, that same setup from before works without issues. 0 can be used and it won't be cleared out from the input on focus loss.

This also happens with the v2.0 BETA exposed with bower too.

PS: and thanks for this lib. Time saver. Thanks so much.

**Comment by BobKnothe** [comment]
Thank you for the heads up.

I will try and investigate sometime this weekend

**Comment by BobKnothe** [comment]
I tried ti duplicate your issue and could not - can you post an example on jsFiddle

**Comment by TCattd** [comment]
I neither can't reproduce it in a blank jsFiddle. Sorry.

Thanks for the time!
