### ISSUE TITLE
Symbols are truncated when user copy-past values into field

### ISSUE THREAD

**Issue by Aeliot-Tm** [BobKnothe/autoNumeric#226]
If we set parameter "vMax" as 2147483647 user can not insert velue 1234567890 into the field.
[http://screencast.com/t/gMd78qHPRPxo](url)

>  $('.foreman-report-quantity').autoNumeric('init', {
>        vMin: 0,
>        vMax: 2147483647,
>        mDec: 0,
>        aPad: false,
>        aForm: false,
>        lZero: 'deny'
>    });

The version of library is this: http://prntscr.com/c1y4oa

**Comment by BobKnothe** [comment]
I have tested this on version 1.9.45 and do not encounter the same issue.

Please post an example on fiddle so I can trace.

Please note that vMin, vMax & mDec should be placed as text

vMin: '0',
vMax: '2147483647',
mDec: '0',

**Comment by Aeliot-Tm** [comment]
> Please note that vMin, vMax & mDec should be placed as text

How intesting. Is it can not be fixed internally in plugin?
I tried your suggestion, but, unfortunately, it is does not helped to me.

**Comment by BobKnothe** [comment]
Please post a jsfiddle or codepen so i can see the issue first hand.

**Comment by Aeliot-Tm** [comment]
Unfortunately, this services not permit to use external sources like http instead of https.
And on our site i can not to show, because you need log in for it, but i have no permission to give it to you.
Perhaps, you can give me https link on this library, then i will try to reproduce issue on jsfiddle/codepen

**Comment by AlexandreBonneau** [comment]
@Aeliot-Tm you can use [rawgit](https://rawgit.com/) to reference code from Github.

**Comment by AlexandreBonneau** [comment]
I just tested on the `next` branch, and you can enter `1234567890`, which gets formatted to `1,234,567,890` when using the following options : `{ allowDecimalPadding: false, formatOnPageLoad: false, minimumValue: '0', leadingZero: 'deny', maximumValue: '2147483647', mDec: '0' }`.
