### ISSUE TITLE
Do not modify the current selection when trying to input an invalid character

### ISSUE THREAD

**Issue by jannunezz** [BobKnothe/autoNumeric#228]
Hello, first of all nice work!

An issue I encountered is when you select input text using CTRL+A and release "CTRL" just before the "A" the selection will be removed.  The following will only detect select all if the CTRL+A keys are released simultaneously:

```
if ((ctrlKey || cmdKey) && kdCode === 65) { /** if select all (a=65)*/
    return true;
}
```

A solution may be to replace this with something like : 
`if (getElementSelection(e.currentTarget).length > 0) {
                return true;
            }`

EDIT : Initial title : "CTRL+A selection removed"

**Comment by AlexandreBonneau** [comment]
@jannunezz Hello, and thank you for your feedback.

The behavior you are describing is the *normal* behavior you can observe in other inputs.
Using the `ctrl+a` keyboard shortcut means that you have to hit the keys in that order :
1. press `ctrl`
2. press `a`
3. release `a`
4. release `ctrl`

If you invert step `4` and `3`, you are really trying to input some `a` characters in the input, which is prevented, dropping the current selection.
You can test that behavior in any other input and you'll find that most of the time this will indeed input some `a` characters in those.

The way I see it is that we'd need either : 
- to create a small debounce to check when we get a `a` key pressed, if `ctrl` was pressed a few milliseconds ago. I'm not sure this level of complexity has its place in autoNumeric though, or
- do not drop the current selection if the input character does not change the input value.

@BobKnothe Would you see any drawback to trying to keep the current selection when dropping any invalid key input?

**Comment by AlexandreBonneau** [comment]
The last commit fixes that issue by preventing any 'bad' key to modify the current selection.
This can be found for now in the `next` branch.
