### ISSUE TITLE
$.fn.autoNumeric.defaults undefined

### ISSUE THREAD

**Issue by gayan85** [BobKnothe/autoNumeric#229]
$.fn.autoNumeric.defaults value undefined cannot extend as home page README shows

**Comment by BobKnothe** [comment]
Sorry I do not understand what your are trying to communicate.

Can you be more specific?

**Comment by gayan85** [comment]
Sorry
```
<script type="text/javascript">  

    $(document).ready(function () {          
        $.extend($.fn.autoNumeric.defaults, {              
            aSep: '@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberGroupSeparator',              
            aDec: '@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberDecimalSeparator',
            aSign: '@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.CurrencySymbol'
        });      
    });

  jQuery(function($) {
      $('selector').autoNumeric('init');    
  });

</script>
```

`$.fn.autoNumeric.defaults` is undefined cannot be extend or not update defaults

**Comment by BobKnothe** [comment]
That's odd - using .NET or just passing new defaults?

**Comment by gayan85** [comment]
i think it's not related to .NET i think there's no default values for `$.fn.autoNumeric.defaults`

**Comment by BobKnothe** [comment]
gayan85,

I have corrected the readme file to show you the proper $.extend method.

Thanks,

Bob
