### ISSUE TITLE
Feature request - option to have both prefix and suffix

### ISSUE THREAD

**Issue by avalanche1** [BobKnothe/autoNumeric#230]
Hi! I need an option to have both prefix and suffix in my input, eg: `not more than #{value} km`.

**Comment by BobKnothe** [comment]
Look at version 2.0 which supports both. While is says beta it is stable.

**Comment by avalanche1** [comment]
Readme says differently:
![image](https://cloud.githubusercontent.com/assets/10534563/18349253/12bd5b3e-75d9-11e6-83ce-06a4881f1a5a.png)

**Comment by BobKnothe** [comment]
You need to use two different options
pSign & aSuffix 

between the two they should accomplish what you require.
