### ISSUE TITLE
Limits number of allowed input characters

### ISSUE THREAD

**Issue by realityTorrent** [BobKnothe/autoNumeric#231]
I recently tried to use autoNumeric on some input fields I have. However I was unable to use this plugin for two reasons, perhaps we can solve them? I would really love to be able to use this plugin.

Issue 1: When I run autoNumeric on a input field it seems to limit the number of characters that a user is able to write in the input field. This happends both when I set values in vMin/vMax/mDec and when I leave them empy. Setting maxlength on the input field does not help either.  I have tried to just run input.autoNumeric('init') but this did not help either. The fields are always limited to 13 characters.

Issue 2: I am using the jquery plugin autoGrow on my input fields. But when I run autoNumeric on the input fields autoGrow is no longer able to increase the size of the input fields. Though I am pretty sure this is related to Issue 1.

Thank you for your help Bob!

**Comment by BobKnothe** [comment]
The defaults for vMin & vMax are as follows:

vMin: '-9999999999999.99' //13 signifcant digits and 2 decimal places
vMax: '9999999999999.99' // 13 signifcant digits and 2 decimal places

You can change the number of allowed digits by passing the options when initiating or using the update method:

$(selector).autoNumeric('init', {vMin: '0', vMax: '999999999999999999'}); // 18 significant digits and no decimal places.

The reason I has assigned is default values is the limits of JS numeric accuracy. If you plan on using very long strings I suggest you try version 2.0 which has support for Big.js 

Hope this helps.

**Comment by realityTorrent** [comment]
Thank you for your feedback Bob!
