### ISSUE TITLE
elem.autoNumeric('destroy') doesn't unbind all events

### ISSUE THREAD

**Issue by chteuchteu** [BobKnothe/autoNumeric#234]
When using `elem.autoNumeric('destroy')`, autoNumeric does not undind `focusout.autoNumeric` and `focusin.autoNumeric` (among others).

**Comment by BobKnothe** [comment]
I am in the process of publishing the fix - just having a GIT ssh issue

Look at issue #225

**Comment by chteuchteu** [comment]
My bad, should have read all the issues first, you can close my 2 PRs if you're not planning to use them.

**Comment by BobKnothe** [comment]
I just pushed the update - it would be great if you can test

**Comment by chteuchteu** [comment]
It works fine indeed! The fix hasn't been applied in v2.0 though: https://github.com/BobKnothe/autoNumeric/blob/master/autoNumeric-2.0/autoNumeric-2.0-BETA.js#L1549
