### ISSUE TITLE
readme.md and official website differ on the default value of vMin

### ISSUE THREAD

**Issue by IanKemp** [BobKnothe/autoNumeric#239]
[readme.md](https://github.com/BobKnothe/autoNumeric/blob/master/readme.md) says the default value is -9999999999999.99, [the website](http://www.decorplanit.com/plugin/) says it's 0.00. From my experience the latter seems to be correct.

**Comment by BobKnothe** [comment]
Ian,

You are absolutely correct.

On GitHub, Bower and CDNJS the actual value of vMin value = -9999999999999.99 so I will change my web page to reflect the negative value.

Thank you,

Bob
