### ISSUE TITLE
Cannot get autoNumeric to work with jquery 3.1.1

### ISSUE THREAD

**Issue by dreggas** [BobKnothe/autoNumeric#240]
I must be a complete noob, I followed the example on how to get auto numeric to work but It doesn't want to play nice with jQuery 3.1.1 returning the following error:

JavaScript runtime error: Object doesn't support property or method 'autoNumeric'

I have the following lines in my _layout.cshtml:

<script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/autoNumeric/autoNumeric.js"></script>

and the following in my main page:

$(document).ready(function () {
        $("#LoanAmount").autoNumeric("init", {
            aSep: ',',
            aDec: '.',
            aSign: '$ '
        });
    });

for the following textbox:

<input type="text" class="form-control" name="Loanamount" id="LoanAmount" value="0.00" data-an-default="0.00"/>

is there something I am missing? (sorry if this is the wrong place for this Question/Issue)

**Comment by BobKnothe** [comment]
Did you try other versions of jQuery?

**Comment by BobKnothe** [comment]
I have tested jquery 3.1.1 and found no problems so I am closing this issue.

If you have a particularly situation please post an example on jsFiddle or other so I can see this first hand.
