### ISSUE TITLE
Get formatted value without an element

### ISSUE THREAD

**Issue by jesperzach** [BobKnothe/autoNumeric#241]
Say I want to make a method that takes a number and autoNumeric options and returns a formatted number using autoNumeric and the provided. This is currently how I'd go about it:

```
format(input, options) {
    const element = $("<div></div>");
    element.autoNumeric("init", options);
    element.autoNumeric("set", input);

    const value = element.html();
    delete element;

    return value;
}
```

I would like to suggest that autoNumeric should support this without the creation of an element.

**Comment by BobKnothe** [comment]
Thank you for the suggestion - you are not the first.

It can be done by adding a public function but I have been reluctant to add this feature. 

Formatting a string to represent currency can be accomplished with a few lines of code. Using autoNumeric for this is overkill.

I am open to adding the feature but need a compelling argument why add the extra overhead.

Bob

**Comment by jesperzach** [comment]
The overhead is very little. The case here is I'm integrating autoNumeric with Angular. I've made a directive that binds autoNumeric on an element, and I also want to make a filter that formats some input using autoNumeric.

So, for example, when I write:
```
{{ someNumberVariable | autoNumeric : { *AutoNumericOptions go here* } }}
```

What happens behind the scenes currently is an element is created like I described in my original post. This is done every time the value of someNumberVariable changes. Other than being inefficient I find it to be bad practice and kind of a hack.

I see no reason to be concerned about creating a public method for this. I mean, I'm already using autoNumeric. Why would I want to implement an additional formatter to facilitate auch a filter, when autoNumeric already contains this implementation?

The overhead you mention I find insignificant, it's just a matter of making a public method exposing what's already implemented in autoNumeric. We're talking less than 1 KB to a script of 68.7 KB unminified. That's no overhead at all compared to what overhead those of us who have requested this feature will experience, either from having to maintain a fork or from having to apply the "hack" I mentioned.

What if we flip around your question... Do you have a compelling argument not to add this feature?

I can make a PR if that's the issue. Regardless thank you for the very good job on creating and maintaining autoNumeric :)

**Comment by BobKnothe** [comment]
This would be considered a new feature and would be added to version 2.0 if i move forward.

Version 1.9.nn updates will be fixes only

**Comment by AlexandreBonneau** [comment]
@jesperzach Take a look at the last version, it provides two `format` and `unFormat` methods that allows to do just that without having to first init an element.

**Comment by AlexandreBonneau** [comment]
Given those new functions, we'll close the issue.
Feel free to re-open it if needed.
