### ISSUE TITLE
NuGet Version - Bug on destroy

### ISSUE THREAD

**Issue by levisk** [BobKnothe/autoNumeric#242]
The version (1.9.45) i m using i download from here:

https://www.nuget.org/packages/autoNumeric/

The method destroy of this version has this code:
    $this.off('autoNumeric');

And the destroy from your repo directly works like this
    $this.off('.autoNumeric');

It's missing the '.' on the off function.
When i destroy an element and initialize it again, it duplicates the number i type.
I changed it and it worked with no problems.

**Comment by AlexandreBonneau** [comment]
Hello @levisk, and thanks for pointing out this bug.

1.9.45 however is an old version, and while Github is the main code repository, we do not have control over all the numerous satellite site that copy the code from here, unfortunately.

Please use either the latest old stable [1.9.46](https://github.com/BobKnothe/autoNumeric/tree/1.9.x), or the newest not-ready-for-production-yet [2.0-beta](https://github.com/BobKnothe/autoNumeric/tree/next).

In any case, the nuget's user *RJK* is the one that could/should update to the last version.
