### ISSUE TITLE
Using `vMin` with autoNumeric 2.* output errors in the console

### ISSUE THREAD

**Issue by AlexandreBonneau** [BobKnothe/autoNumeric#243]
I put together a codepen [here](http://codepen.io/AnotherLinuxUser/pen/JRzbWK?editors=0010) that shows how using `vMin` in the option breaks autoNumeric.

On each input, an error `Uncaught TypeError: n.charAt is not a function` is output.

**Comment by BobKnothe** [comment]
Alexandre,

The issue is you are using a numeric value when setting the min/max value. My docs specifically say these should be enclosed in quotes "string"  as follows {vMin: '0'}.

Bob

**Comment by AlexandreBonneau** [comment]
Ah, I missed that apparently! Thanks for the hint.

Wouldn't it be logical to accept `String` and `Number` here, and just `.toString` that parameter?
Perhaps I'm missing a piece of information here.

**Comment by BobKnothe** [comment]
Alexandre,

Yes I will add that on the next update

Also trying to add the following features

•	Format numeric strings with no element
•	Bypass min & max values separately or both - unlimited length
•	Scaling - show full value on focus and scaled value on focus out
•	Custom callback when user tries and enter a value the exceeds the min/max

Bob
