### ISSUE TITLE
[Feature request] Add two 'format' and 'unformat' methods

### ISSUE THREAD

**Issue by AlexandreBonneau** [BobKnothe/autoNumeric#245]
I frequently need to test formatted/unformatted data against values from an autoNumeric managed input.

I wish I could do something like :
```javascript
let myOptions = { aSep: '.', aDec: ',', altDec: '.', aSign: ' €', pSign: 's', mRound: 'U' };
let autoNumInput = $(el).autoNumeric('init', myOptions);

let unformattedValueXXX = "2222.67";
let formattedValueXXX = autoNumInput.autoNumeric('format', unformattedValueXXX); //"2.222,67 €"

let formattedValueYYY = "678.000,32 €";
let unformattedValueYYY = autoNumInput.autoNumeric('unformat', formattedValueYYY); //678000.32
```
...using the autoNumericInput as a 'factory' to format/unformat given number/strings.

That would allow us to not have to code an unformat function to do that myself (and defeat the purpose of the multiple autoNumeric format options), and not reinventing the autoNumeric wheel.

**Comment by AlexandreBonneau** [comment]
Better yet, be kind with the IDE autocompletion feature and do that :
```javascript
let myOptions = { aSep: '.', aDec: ',', altDec: '.', aSign: ' €', pSign: 's', mRound: 'U' };
let autoNumInput = $(el).autoNumeric.init(myOptions);

let unformattedValueXXX = "2222.67";
let formattedValueXXX = autoNumInput.autoNumeric.format(unformattedValueXXX); //"2.222,67 €"

let formattedValueYYY = "678.000,32 €";
let unformattedValueYYY = autoNumInput.autoNumeric.unformat(formattedValueYYY); //678000.32
```

;)

**Comment by BobKnothe** [comment]
Would something like this work at least for the formatting portion?

let myOptions = { aSep: '.', aDec: ',', altDec: '.', aSign: ' €', pSign: 's', mRound: 'U' };
let unformattedValueXXX = "2222.67";
let autoNumInput = $fn.autoFormat(unformattedValueXXX, myOPtions ); //"2.222,67 €"

**Comment by AlexandreBonneau** [comment]
That would work yes.

The downside though would be to be able to keep a reference to the `myOptions` variable around in order to use that, while in most data-binding framework (like Angular or Vue.js), you usually have direct access only the DOM element from the components/directives.

The upside is that you would not need to initiate an input to get formatted output, and that's very good for some use cases!

What about unformatting though?

I think both approach would be a good addition to autoNumeric :
- use `$fn.autoFormat(unformattedValue, myOptions)` to get formatted strings without needing to have a DOM `<input>` element, and
- use the existing autoNumeric-managed `<input>` element to format/unformat any number/string.

**Comment by BobKnothe** [comment]
Name spacing would require a major re-write which I am not prepared to do at this time.

I just finished the $.fn.autoFormat("value", {options});  need to check for bugs.

Next will be $.fn.autoUnformat("value", {options});

You could always attach the options as data to some element - yes i know it's not elegant.

**Comment by AlexandreBonneau** [comment]
Those functions are calleb via the jQuery wrapper and directly when aN is imported as a module.
The work is done here, thanks @BobKnothe!

*note: the IDE autocompletion will be improved in the near future*
