### ISSUE TITLE
When focusing single value field with tab, input of same number is impossible

### ISSUE THREAD

**Issue by lovrozitnik** [BobKnothe/autoNumeric#246]
I have made a fiddle, when you can try the following scenario:
1. Focus in input with value 6
2. Press tab to focus input with value 7
3. Press 7 again - you cannot add another 7, but if you input any other number - no problem
--
4. If you press tab again to focus field with value 8, you cannot edit value 8 by pressing 8 again.

It is not a browser issue, tested in latest Chrome, Safari and Firefox and Internet Explorer 11 as well.

---

Not working on autoNumeric 1.9.46:
[Problematic fiddle](http://jsfiddle.net/hzm9cLcj/5/)

Working on autoNumeric 1.8.2:
[Working fiddle](http://jsfiddle.net/hzm9cLcj/6/)

---

I did not test in which version the problem arose.

**Comment by BobKnothe** [comment]
First I want to thank you for the fiddle - it really make my job much easier.

I will dig into this issue and getting back with you

**Comment by BobKnothe** [comment]
I just uploaded the fix - please test and close the issue if you are pleased.

**Comment by lovrozitnik** [comment]
I can confirm, issue is resolved. Thank you!

For confirmation see working example in fiddle fork: http://jsfiddle.net/4tLgwbpL/
