### ISSUE TITLE
Pressing delete adds unwanted zeros

### ISSUE THREAD

**Issue by ContextSwitch** [BobKnothe/autoNumeric#262]
Pressing the delete key adds unwanted zeros to the number we're displaying in a text field. The settings we are using are:

mDec:'2', 
mRound:'D', 
lZero:'deny'

**Comment by AlexandreBonneau** [comment]
Hi @ContextSwitch, could you please provide a live example (ie. codepen) of the problem, what you expect, what you get instead, and the steps to reproduce it?
Thanks!

**Comment by AlexandreBonneau** [comment]
Since I was not able to reproduce the *'bug'*, and there is no more activity on this issue, I'm closing it.

Feel free to reopen it if you feel we missed something.
