### ISSUE TITLE
Release v2 on NPM

### ISSUE THREAD

**Issue by BryanSD** [BobKnothe/autoNumeric#269]
I realize v2 was just recently completed, but just wondering what the plans were for pushing it to NPM? NPM still has v1.9.46 listed as the latest version. In particular I can't wait to use `$.fn.autoFormat` and `$.fn.autoUnformat`! Thanks!

**Comment by AlexandreBonneau** [comment]
Hello, @BryanSD , thanks for your interest in autoNumeric.

I think @BobKnothe will confirm it, but right now the v2 is in beta.
Some more work needs to be done on the ES6 conversion, as well as correcting a critical bug on Android.

As soon as those are finished/corrected, it will be released on `npm`!

**Comment by BobKnothe** [comment]
@BryanSD 

Yes @AlexandreBonneau is correct - hopefully in the near future

**Comment by AlexandreBonneau** [comment]
For info, `2.0.0-beta.23` has been published on the [npm registry](https://npmjs.org/package/autonumeric).

**Comment by AlexandreBonneau** [comment]
v2.0.0 has been published on https://www.npmjs.com/package/autonumeric
