### ISSUE TITLE
get method return add minus sign when vMin >= 0

### ISSUE THREAD

**Issue by MauroLuque** [BobKnothe/autoNumeric#284]
Look at this fiddle:

https://jsfiddle.net/wfzgb59y/

The alert show a negative value.

If you set vMin to a number < 0, then the alert shwo the correct number.

**Comment by BobKnothe** [comment]
Thanks - as you can see we are making many changes and apparently a bug got introduced

**Comment by AlexandreBonneau** [comment]
Thank you for reporting this bug, and creating a live example that shows the problem.
This really helped.

The fix is being merged as a hotfix to `master` and should soon be available.

**Comment by BobKnothe** [comment]
should be completed - thank you for your attention

**Comment by BobKnothe** [comment]
if you are satisfied please close the issue.

**Comment by MauroLuque** [comment]
yes! many thanks for the rapid response and the fix!
