### ISSUE TITLE
Keyup and cursor problem

### ISSUE THREAD

**Issue by arafsan** [BobKnothe/autoNumeric#295]
Hi,

First of all thank you for the plugin. It really works great. But I have a little problem.
I get the value entered in a field and print it in a different field in real time. I have to use "keyup" to do this dynamically, but when I press each key, the cursor goes to the end and prevents it from writing. Could it be a solution for that?

**Comment by AlexandreBonneau** [comment]
Hello @arafsan , could you please create a codepen showing the problem, the steps to reproduce it, and what you expect exactly?

If you enter a character key (like `a`), autoNumeric will prevent the input, this is the normal behavior. On the other hand, entering a number should pose no problem.
On my end, I already used Vue.js to do what you describe, without any hiccup.

**Comment by arafsan** [comment]
Hi, 
First of all thank you for your reply.
I prepared you two simple examples to explain the problem.
The first one was prepared with a different plugin.
The second was prepared with your plugin.

1 - https://jsfiddle.net/3Lscdfjf/
2 - https://jsfiddle.net/e89vttuh/

As the writing process continues, the cursor moves to the right and prevents writing.
Could it be a solution for that?

**Comment by AlexandreBonneau** [comment]
@arafsan Thank you for your interest into autoNumeric.
We try to make it as usable as possible and welcome any ideas to improve the user experience.

Regarding your problem, it's in your code, where you force an settings update on each `keyup` event.
If you remove this line : `$('#firstField, #secondField').autoNumeric('update', priceFormatOptions);`, everything works fine (I tested with the latest autoNumeric version in the `next` branch).

Here is the corrected [jsfiddle](https://jsfiddle.net/e89vttuh/1/).

**Comment by arafsan** [comment]
Thanks for your answer.
In version 1.9.46, there was a problem with mathematical operations if I did not give the 'value' value by default. For example, I was not able to collect the value of two fields. And I definitely needed to specify value = "0". I understand that we will not need it anymore in version 2.0. Please fix it if I'm wrong.

I think you have tried with version 2.0 and this version is currently in beta. Does it create any problems? Can I use it comfortably?
As far as I can see the latest version on GitHub is 1.9.46. Where can we track the new version?

**Comment by AlexandreBonneau** [comment]
Well, since it's a beta, things are bound to be broken, so do not use it in production.

On the other hand, we strive to commit only when all the tests are green so you should be pretty safe using it.
Our tests coverage though still does not include user interaction (which is the next big work for us), so, again, do not use it in production!

From now on, all development is done in the [`next` branch](https://github.com/BobKnothe/autoNumeric/tree/next), while `master` will only have the releases and hotfixes.
