### ISSUE TITLE
With `leadingZero: 'deny'`, it's not possible to enter '0.0' in an input

### ISSUE THREAD

**Issue by AlexandreBonneau** [BobKnothe/autoNumeric#306]
Using this simple option object `{ leadingZero: 'deny' }` :
- If the input is empty `|`, it's not possible to enter a single `0|`, the input is prevented and nothing else happens.
- if the input is empty `|`, you can enter a dot ('.'), which will result in `0.|`, but then you cannot input another `0` to obtain `0.0|`.

This means a user cannot enter `0.000246` in such an input.

The `leadingZero` option set to `deny` should only prevent entering zeroes on the left side of the integer part.

**Comment by BobKnothe** [comment]
please test the fix at this codepen 

http://codepen.io/RJ_Knothe/full/KNbNeQ/

**Comment by AlexandreBonneau** [comment]
Looks good to me (cf. updated [codepen](http://codepen.io/AnotherLinuxUser/pen/BQEwNM?editors=1010))

**Comment by BobKnothe** [comment]
please close if you are statisfied

**Comment by AlexandreBonneau** [comment]
Unfortunately, the issue is not completely resolved.

Using your last codepen, I edited it [here](http://codepen.io/AnotherLinuxUser/pen/JbqXKW?editors=1010) to allow for 5 decimal places.

- If in the first input you clear everything, then write `0,00000`, it works.
- Then if you move the caret (with the keyboard arrows) here `0,|0000`, then type `12345`, it still works and you get `0,12345`
- Then if you move the caret again here `0,|12345`, then type `00000`, you also get the right result `0,00000|`
- The problem arise now, if you move the caret anywhere in the input (ie. `|0,00000`, `0|,00000`, `0,|00000`, `0,0|0000`, `0,00|000`, `0,000|00` or `0,0000|0`), you cannot enter another `0` to 'move' the caret anymore.
For instance, having `0,000|00`, a user could want to enter `0,00024`. This is not possible now.

**Comment by AlexandreBonneau** [comment]
Also, without having to change anything from the first input, if you put the caret here `50.000,|00` or here `50.000,0|0`, you cannot input the `0` character too.
