### ISSUE TITLE
Using '9999,999' in `minimumValue` or `maximumValue` make the aN initialization fail silently

### ISSUE THREAD

**Issue by AlexandreBonneau** [BobKnothe/autoNumeric#311]
Everything is in the title!
Whenever a user use an invalid number like `'9999,999'` (instead of `'9999.999'`) for either the `minimumValue` or `maximumValue` option, autoNumeric initialization fails silently without any error.

**Comment by BobKnothe** [comment]
I see that an error in thrown if either the min/max value have the following formatt 'nnnn,nn'

Should there be a modification of should this issue be closed?

**Comment by AlexandreBonneau** [comment]
Ok, I checked again against Firefox `52.0a2 (2017-01-03)` and Chromium `55.0.2883.75` and I can now see the error message, as you are supposed too.
