### ISSUE TITLE
Namespace the jQuery functions

### ISSUE THREAD

**Issue by AlexandreBonneau** [BobKnothe/autoNumeric#314]
Currently, the `next` branch provides those functions via the jQuery `$.fn` object :
- `autoNumeric`,
- `autoFormat`,
- `autoUnformat`, and
- `validate`

This can be a problem as somebody reported in this [comment](https://github.com/BobKnothe/autoNumeric/issues/248#issuecomment-259026531) in issue #248.
To prevent name clashing with other plugins which also do not namespace their functions. we must namespace ours with `auto`.

Hence, `validate` will become `autoValidate`, and you'll be able to use `$.fn.autoValidate()`.

**Comment by AlexandreBonneau** [comment]
This has been pushed via PR https://github.com/BobKnothe/autoNumeric/pull/315

**Comment by bjunc** [comment]
Works for me, thanks for jumping on it so fast!
