### ISSUE TITLE
Use `event.key` instead of `event.keyCode` and `event.which` since those two attributes are deprecated

### ISSUE THREAD

**Issue by AlexandreBonneau** [BobKnothe/autoNumeric#320]
`event.keyCode` and `event.which` have always been hard to work with since depending on the type of event (ie. `keypress`), those two can have different value for the same trigger key.

Both `keyCode` and `which` have been deprecated for some time now, and it's recommended to not use those anymore (cf. [this doc](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) and [this one](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which)).

[`event.key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) is the new shinny attribute that will bind them all, we should use that instead of the deprecated attributes.

The related key list is described [here](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values) as well.

**Comment by BobKnothe** [comment]
Yes this is a change that should be made - first we need to determine browser support.

I did some testing here: https://w3c.github.io/uievents/tools/key-event-viewer.html

Try a andriod mobile device - and you can see why there are problems, no codes and keypress event.

**Comment by AlexandreBonneau** [comment]
Note: `event.key` are currently not currently set by the geckodriver used by Selenium (see this [issue](https://github.com/mozilla/geckodriver/issues/440)).

To solve this problem, I [created](https://github.com/BobKnothe/autoNumeric/commit/538139cae12f82c520443dc9018333f54d697c46#diff-c657689185e339bb9234662ebefc85e9R979) a `character(event)` function that check if `event.key` return an `Unidentified` string.

**Comment by AlexandreBonneau** [comment]
Another problem is that `String.fromCharCode(keyCode)` returns nonsensical characters when the key code is not a printable character.

For instance:
```js
const what = String.fromCharCode(46);  // 46 === Delete
what === '.'; // true
```
