### ISSUE TITLE
Allows more international decimal characters and grouping separators

### ISSUE THREAD

**Issue by AlexandreBonneau** [BobKnothe/autoNumeric#321]
The Arabic decimal character `'٫'`, the dot-above `'˙'`, as well as many other decimal characters and grouping separators are currently unsupported by autoNumeric.
Those *special* characters as defined in https://en.wikipedia.org/wiki/Decimal_mark should be supported.

**Comment by BobKnothe** [comment]
Agree - this will only make aN better

**Comment by AlexandreBonneau** [comment]
This [commit](https://github.com/AlexandreBonneau/autoNumeric/commit/e5309e395579597fcd4c4532dd9a48af333df593) modify autoNumeric so that `digitGroupSeparator` now accepts one of those values :
```
[
            ',',      // Comma
            '.',      // Dot
            ' ',      // Normal space
            '\u2009', // Thin-space
            '\u202f', // Narrow no-break space
            '\u00a0', // No-break space
            '',       // No separator
            "'",      // Apostrophe
            '٬',      // Arabic thousands separator
            '˙',      // Dot above
]
```

and `decimalCharacter` now accepts one of those options :
```
[
            ',', // Comma
            '.', // Dot
            '·', // Middle-dot
            '٫', // Arabic decimal separator
            '⎖', // Decimal separator key symbol
]
```
