### ISSUE TITLE
Setup continuous integration testing

### ISSUE THREAD

**Issue by AlexandreBonneau** [BobKnothe/autoNumeric#345]
To make sure autoNumeric is always well tested, we need to setup an automatic and continuous integration testing.

I'm currently looking at [Travis](https://travis-ci.org) for now.

**Comment by jlaustill** [comment]
I use Travis.  It's a great choice!

**Comment by AlexandreBonneau** [comment]
I'm also looking at [Codeship](https://codeship.com/) and [Circle CI](https://circleci.com).
They all look promising!

For info, a related [article](https://www.itcentralstation.com/product_reviews/travis-ci-review-32073-by-ben-dougherty) that compare both (and others).

**Comment by AlexandreBonneau** [comment]
Travis CI it is, but it was a close call!
