### ISSUE TITLE
autonumeric init not getting applied

### ISSUE THREAD

**Issue by topagarwal** [BobKnothe/autoNumeric#368]
I am pasted my code here  - https://jsfiddle.net/qrvmmh7x/
In the browser if I do fieldname.autonumeric('set',10) it sets to $10. However upon form load with default values, it is not showing '$' sign.

**Comment by AlexandreBonneau** [comment]
Hello @topagarwal, thank you for taking the time to report a bug.

In the jsfiddle you linked, there are no external link to the autoNumeric not jQuery libraries, which means autoNumeric cannot work!

Even though there was, you are using `.autoNumeric('set',{aSign: "$"});` which is not how the `set` method should be used ;
If you want to update the settings, first use `update`, then you can set the value with `set`.
Lastly, before being able to set a value, you need to `init` the input field once (cf. the [documentation](https://github.com/BobKnothe/autoNumeric#jquery-plugin-calls)).

**Comment by topagarwal** [comment]
Yea..sorry about jsFiddle. However, I realized that autoNumeric init works only with input fields and non-number fields. I changes the field type from IntegerInput to CharField and it worked.

**Comment by AlexandreBonneau** [comment]
Nice to hear! 🎉
