### ISSUE TITLE
Not Set automatically when populate form

### ISSUE THREAD

**Issue by cyberzilla** [BobKnothe/autoNumeric#369]
AutoNumeric run normally, but when i populate the form, the data still non-formatted, how to fix this?
```js
function populateForm(frm, dataJSON)
{
	data = $.parseJSON(dataJSON);
	$.each(data, function(key, value) {
		var $ctrl = $("#"+frm).find('[id='+key+']');
		if ($ctrl.is('select')){
			$('option', $ctrl).each(function() {
				if (this.value == value)
					this.selected = true;
			});
		}
		else if ($ctrl.is('textarea')) {
			var id = $ctrl[0].id;
			for(id in CKEDITOR.instances){
				CKEDITOR.instances[id].setData(value);
			}
			$ctrl.val(value);
		}
		else {
			switch($ctrl.attr("type")) {
				case "email":
				case "text":
				case "hidden":
					$ctrl.val(value);
					break;
				case "checkbox":
					if (value == 'on')
						$ctrl.prop('checked', true);
					else
						$ctrl.prop('checked', false);
					break;
			}
		}
	});
	$(".autonumeric").autoNumeric("init");
}
```

**Comment by AlexandreBonneau** [comment]
Hi @cyberzilla, which version of autoNumeric are you using?
*(We recommend using the latest 2.0.0 version)*

autoNumeric has a `formatOnPageLoad` option that is set to `true` by default that format the input on init.

The code snippet you pasted taken out of its context unfortunately does not show any useful information. Do you see any error message?
A codepen where you can narrow the problem down would help us help you greatly.

**Comment by AlexandreBonneau** [comment]
Due to inactivity, I'm closing this issue considering it resolved.

If that's not the case, feel free to re-open it!
