### ISSUE TITLE
Possibility to format numbers without input

### ISSUE THREAD

**Issue by eisbehr-** [BobKnothe/autoNumeric#370]
Hi,

I came across a usecase where it would be neat to use the plugin to format a number by the same configuration passed to the initalization, but without the need of an input field. Maybe there is a possibility I don't know yet ...

**For example:**
I use the plugin to calculate the row amount of a price. In the last column the calculated row amount will be shown.

```
+--------+     +-------+
| Amount |  *  | Price |  =  Calculated Price
+--------+     +-------+
  ^ input        ^ input     ^ just text
```

Now it would be nice to have a text output just with the same options like the price input field. Maybe there could be an public accessible option on the object. Something like this:

```JS
$(".price").autoNumeric("init", {
    digitGroupSeparator: ",", 
    decimalCharacter: ".", 
    currencySymbol: " $", 
    currencySymbolPlacement: "s"
});

// ...

var price = $(".price").autoNumeric("get"); // 1234.56
var amount = $(".amount").autoNumeric("get"); // 5
var calculatedPrice = $(".price").autoNumeric("getFormatted", price * amount); // 6,172.8 $
```

Actually I'll do the same with the need of a hidden field. It does the same thing, but it feels a bit _hacky_. 😉 

```HTML
<input type="hidden" id="formatter">
```

```JS
var formatter = $("#formatter").autoNumeric("init", autoNumericConfig);
formatter.autoNumeric("set", price * amount); // 1234.56 * 5
var calculatedPrice = formatter.val(); // 6,172.8 $
```

Maybe there already is a way I didn't found. If not, that would be a nice little feature. I think the basic functionality is already there, it just needs a public function to work with ...

**Comment by BobKnothe** [comment]
Eisbehr,

With the just release 2.0 version this functionality if built in - please look at the following:

$(someSelector).autoFormat('1234.56', {options});

$(someSelector).autoUnFormat('1.234,56 €', {options});

If this meets your needs please close the issue.

Thanks for using autoNumeric.

**Comment by eisbehr-** [comment]
Hello @BobKnothe,

thank you for your hint. It works as you said!

A little idea to improve this:
Actually it seems to be needed, to add the `options` again with every `autoFormat`. This seems a bit redundant to me, because the `selector` already have options set. So the second parameter should be optionally, and if not set, it should use the `options` set on init. If set, it should override the option from `init`, and not the defaults. This would reduce the overhead and you will keep any possibilities working ...

But this is just an additional idea. Feel free to close this here otherwise ...

**Comment by BobKnothe** [comment]
Thanks for the suggest - we will keep that in mind for future releases

**Comment by AlexandreBonneau** [comment]
@eisbehr- for reference, this as been discussed on https://github.com/BobKnothe/autoNumeric/issues/245, and is detailed in the readme [here](https://github.com/BobKnothe/autoNumeric#jquery-plugin-calls) and [there](https://github.com/BobKnothe/autoNumeric#es6-module-calls).

The next major version of autoNumeric will see great improvements on how you'll be able to use those format/unformat functions (without having to keep a reference to the options for instance)!

**Comment by eisbehr-** [comment]
Thanks for your addition. Looking forward to the shorter version! 😉
