### ISSUE TITLE
The currency symbol is not removed on blur with the default `emptyInputBehavior` value `focus`

### ISSUE THREAD

**Issue by eisbehr-** [BobKnothe/autoNumeric#371]
Hello,

I have some strange behavior with input fields. Whenever I click inside an input field, with `autoNumeric` initialized on, the currency symbol will show up. If I don't input anything and click somewhere outside the field, the curreny symbol will be staing in there. So far it's ok.

But when I now only move the mouse over some of the input fields, the currency symbol will be removed again. 

That is a bit strange to me. If the currency symbol would stay there _forever_, it would be okay. Or when the currency symbol would be removed instantly when leaving the field, it would be fine too. But the mix of this is unlucky.

I made a [**jsfiddle**](https://jsfiddle.net/4skdsr3o/) with a working example of this ...

**Comment by BobKnothe** [comment]
Can you post a codepen? That will help us understand.

**Comment by eisbehr-** [comment]
Isn't a fiddle just the same as a codepen?

**Comment by eisbehr-** [comment]
But here you go, the same again as [codepen](http://codepen.io/anon/pen/WRXQwQ) ...

**Comment by eisbehr-** [comment]
Another addition to the behavior:

When you add a number into the input (_like "1"_) and click outside again, the value of the field will be `1 €`. So far, so good. When you now move the mouse over the field the value change automatically to `1,00 €`. That is strange too. It should add the `,00` directly on `blur` or don't do anything when moving the mouse on it ...

**Comment by BobKnothe** [comment]
I am using windows 10 and chrome 55 and it works as expected.

I do see the behavior you are referring to on FF.

what OS & browser are you using?

**Comment by eisbehr-** [comment]
I've tested it with FF too.

**Comment by AlexandreBonneau** [comment]
I tested on Firefox Dev 52.0a2, and Chrome 55 and it works fine.

However, on Firefox ESR 45.6.0 the currency symbol does not get removed when the input lose focus ; this is not normal and needs to be fixed.

**Comment by AlexandreBonneau** [comment]
This is now corrected on Firefox 45.6. on `master` and `next`.

Could you please test if that solve your problem on your end?
If it does not, feel free to reopen this issue.

**Comment by eisbehr-** [comment]
Just to let you know, I've tested this with version 2.0.2 and everything looks fine now. Devinitly solved!
Thanks!

**Comment by AlexandreBonneau** [comment]
Nice!
