### ISSUE TITLE
`npm install` for version 2.0.4 does not work on Windows machines

### ISSUE THREAD

**Issue by jsmarsch** [BobKnothe/autoNumeric#384]
running npm install autonumeric --save yields a post install script error on windows machines:

```
223 error Tell the author that this fails on your system:
223 error     test -e node_modules/phantomjs-prebuilt/install.js && node node_modules/phantomjs-prebuilt/install.js; true

```
The problem probably occurs because "test" is a bash command that is not available from the windows command interpreter.

**Comment by jsmarsch** [comment]
Well, I tried executing npm install from a bash command shell on windows, and I still get the same error, so I don't think the problem is that the "test" bash command is missing.  I even tried installing phantomjs as a dev dependency (npm install --save-dev)

At this point, I'm stuck.  Even a work-around that would allow me to pull it down would be much appreciated.

**Comment by AlexandreBonneau** [comment]
For reference, this issue is linked to https://github.com/BobKnothe/autoNumeric/issues/367, except it happens only on Windows.

**Comment by jsmarsch** [comment]
Hi Alexandre:

I'm on a Windows machine, so I tried your tests 2 ways:  once with the Windows Command interpreter (cmd.exe), and once with gitbash, which is a bash console installed with git for windows.

In both cases, I got the same error.  Here's what I got:

```
427 error Windows_NT 6.1.7601
428 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jmarsch\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "autonumeric"
429 error node v6.9.4
430 error npm  v4.1.2
431 error code ELIFECYCLE
432 error autonumeric@2.0.4 postinstall: `test -e node_modules/phantomjs-prebuilt/install.js && node node_modules/phantomjs-prebuilt/install.js; true`
432 error Exit status 1
433 error Failed at the autonumeric@2.0.4 postinstall script 'test -e node_modules/phantomjs-prebuilt/install.js && node node_modules/phantomjs-prebuilt/install.js; true'.
433 error Make sure you have the latest version of node.js and npm installed.
433 error If you do, this is most likely a problem with the autonumeric package,
433 error not with npm itself.
433 error Tell the author that this fails on your system:
433 error     test -e node_modules/phantomjs-prebuilt/install.js && node node_modules/phantomjs-prebuilt/install.js; true
433 error You can get information on how to open an issue for this project with:
433 error     npm bugs autonumeric
433 error Or if that isn't available, you can get their info via:
433 error     npm owner ls autonumeric
433 error There is likely additional logging output above.
434 verbose exit [ 1, true ]
```

**Edit:  I found some additional info in the log**
I found this in the npm-debug.log, immeditaely preceding the information above:

```
418 warn test-an@1.0.0 No description
419 verbose If you need help, you may report this error at:
419 verbose     <https://github.com/npm/npm/issues>
420 warn test-an@1.0.0 No repository field.
421 verbose If you need help, you may report this error at:
421 verbose     <https://github.com/npm/npm/issues>
422 warn Error: EPERM: operation not permitted, rmdir 'c:\temp\test-an\node_modules'
422 warn     at Error (native)
422 warn  { Error: EPERM: operation not permitted, rmdir 'c:\temp\test-an\node_modules'
422 warn     at Error (native)
422 warn   errno: -4048,
422 warn   code: 'EPERM',
422 warn   syscall: 'rmdir',
422 warn   path: 'c:\\temp\\test-an\\node_modules' }
423 verbose Please try running this command again as root/Administrator.
424 verbose stack Error: autonumeric@2.0.4 postinstall: `test -e node_modules/phantomjs-prebuilt/install.js && node node_modules/phantomjs-prebuilt/install.js; true`
424 verbose stack Exit status 1
424 verbose stack     at EventEmitter.<anonymous> (C:\Users\jmarsch\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
424 verbose stack     at emitTwo (events.js:106:13)
424 verbose stack     at EventEmitter.emit (events.js:191:7)
424 verbose stack     at ChildProcess.<anonymous> (C:\Users\jmarsch\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
424 verbose stack     at emitTwo (events.js:106:13)
424 verbose stack     at ChildProcess.emit (events.js:191:7)
424 verbose stack     at maybeClose (internal/child_process.js:877:16)
424 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
425 verbose pkgid autonumeric@2.0.4
426 verbose cwd c:\temp\test-an
```

**Comment by jsmarsch** [comment]
One additional note on the error info above:  I did run as an admin, and, at least after running the commands, there was no node_modules folder , so either the rmdir command succeeded, or the directory never got created.

**Comment by AlexandreBonneau** [comment]
The log says that :
```sh
test -e node_modules/phantomjs-prebuilt/install.js && node node_modules/phantomjs-prebuilt/install.js; true
```
return an exit code value of `1`, which is not possible since `true` always return `0` by definition.
This is really odd.

I'm not sure how it's possible, a windows/bash bug? That exit code is sent out before trying to execute this `postinstall` script?

In the detailled `npm-debug.log` file you pasted, it mention a call to `rmdir`, but autoNumeric do not `rm` anything, perhaps it's for the phantomjs install script.
When running as administrator, did you saw the exact same error?

**Comment by jsmarsch** [comment]
Yes -- I have Windows UAC turned off, it was all running as admin.  For what it's worth, a windows developer might not be running bash, but could be using the windows command interpreter instead (which does not have a TEST command).  Is there a way to execute that check without using test -- a node function, or something?

**Comment by AlexandreBonneau** [comment]
I haven't used windows for more than a decade, so I could not say.
I *(painfully)* managed to setup a virtual machine to get the error message myself, and I'm really confused by what I see when running basic commands :
![bug_windows_npm_autonumeric](https://cloud.githubusercontent.com/assets/7248877/22446998/dbde6d9c-e6f3-11e6-874d-06d9536fcfa8.png)

Any windows user here could enlighten us why this fails?

**Comment by jsmarsch** [comment]
I got nothing.  That's pretty much what saw as well.

**Comment by AlexandreBonneau** [comment]
Ok, I hacked a pure node.js script to run the `install.js` file if it exists, without having to rely on shell commands.
I tested in my virtual machine and it seem to work.

Could you please test v2.0.7 on your side @jsmarsch ?

**Comment by jsmarsch** [comment]
@AlexandreBonneau Good news and bad news:
The good:  the npm installation worked!!

The bad:  I'm running into build problems (see #386)  I had hoped that updating to 2.x would fix it, but no joy.  The first issue was the same typescript issue you will see in the above-mentioned ticket.  
After removing the typings reference from package.json, I get the following error during the browserify build:

(this is gulp executing browserify):
Process terminated with code 1.
events.js:160
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Unexpected token (51:4) while parsing C:\git\Idi.Marketplace\Idi.Marketplace.Web\node_modules\autonumeric\src\autoNumeric.js while parsing file: C:\git\Idi.Marketplace\Idi.Marketplace.Web\node_modules\autonumeric\src\autoNumeric.js
    at DestroyableTransform.end [as _flush] (C:\git\Idi.Marketplace\Idi.Marketplace.Web\node_modules\insert-module-globals\index.js:96:21)
    at DestroyableTransform.<anonymous> (C:\git\Idi.Marketplace\Idi.Marketplace.Web\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at prefinish (C:\git\Idi.Marketplace\Idi.Marketplace.Web\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:465:12)
    at finishMaybe (C:\git\Idi.Marketplace\Idi.Marketplace.Web\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:473:7)
    at endWritable (C:\git\Idi.Marketplace\Idi.Marketplace.Web\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:485:3)
    at DestroyableTransform.Writable.end (C:\git\Idi.Marketplace\Idi.Marketplace.Web\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:455:41)
    at DestroyableTransform.onend (C:\git\Idi.Marketplace\Idi.Marketplace.Web\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:495:10)

**Comment by AlexandreBonneau** [comment]
@jsmarsch good to hear! I'll close this issue then.

About the browserify problem, please open a new issue so we can keep different problems cleanly separated.
Feel free to edit your last comment to post the relevant information to that other issue.

**Comment by jsmarsch** [comment]
@AlexandreBonneau Thanks Alexandre!  Nice work!  I have opened additional issues for the build problems.
