### ISSUE TITLE
npm package for 1.9.46 does not work with browserify / commonjs

### ISSUE THREAD

**Issue by jsmarsch** [BobKnothe/autoNumeric#386]
There is an issue that is blocking me from updating to autoNumeric 2.x (#384), so I tried using version 1.9.46.  I'm running into problems with that version using browserify:

We code with typescript modules (using commonjs format).  We use browserify with the typescriptify plugin to compile our typescript and to adapt the commonjs modules to work on the browser.

When I tried using the npm package for 1.9.46, I encountered 2 errors:
The first one occurred at build time (from browserify):
"typescript: error Exported external package typings file (path to the autonumeric d.ts file) is not a module.

For what we are doing, the typings file is not critical, so I edited the package.json file -- removed the 'typings' entry.

Afterdoing so, I get a successful compile, but at runtime, the autoNumeric() extension method is not available on any elements.  What do I need to do to ensure that autoNumeric initializes?

**Comment by BobKnothe** [comment]
1.9.46 will continue to be supported while we transition to version 2.0 & 3.0

If you are in need of help with version 1.9.46 please let ,e know the errors you are encountering so I can help

**Comment by jsmarsch** [comment]
@BobKnothe The typescript error that we get is exactly the same one that we get with the 2.0.7 package, described in issue #389 

If I remove the typings entry on the 1.9.46 package, I don't get any build errors, but autonumeric never seems to initialize -- the autonumeric extension method is not present on any of the elements.

**Comment by BobKnothe** [comment]
Are any errors being thrown?

Is autoNumeric present in the sources?

**Comment by jsmarsch** [comment]
autoNumeric is present in the sources.  The error being thrown is element.autoNumeric is not a function, where element is my element.  When I open up the debug console in chrome, I can see that there is no autoNumeric function on the input box.

**Comment by BobKnothe** [comment]
This is odd aN1.9.46 has been unchanged for a couple months

Can you post codepen?

**Comment by jsmarsch** [comment]
This one is user error -- sorry.  I had been trying to use it with Angular, and I just noticed that there were some require's for angular files that appeared before the require for jquery (so angular was using jqlite instead of jquery).  Once I got that fixed, it worked.  Issue #389 is still a problem though -- where typescript definition file causes a tsify build error.

**Comment by jsmarsch** [comment]
@BobKnothe 

I did run into one weird problem though, even after I fixed the load-order issue (sorry I didn't mention this in the closing comment -- been a long, tough day):

I had to shim browserify to get autonumeric to work.  It looked like the code for autonumeric was package-aware, but it would not initialize (there was not .autoNumeric() function available at runtime) until I added the following code:

```
// typescript
declare var global: any; // global is a variable that is created by browserify
import jQuery = require('jquery');
global.jQuery = jQuery;
import "autonumeric";
```
which compiles to this javascript:
```
var jQuery = require('jquery');
global.jQuery = jQuery;
require("autonumeric");
```

**Comment by AlexandreBonneau** [comment]
@jsmarsch this looks ok since in order to work, autoNumeric <= version 2 rely on jQuery (this will change in v3, normally).

So you first need to load jQuery, then autoNumeric (cf. the [doc](https://github.com/BobKnothe/autoNumeric#how-to-use)).

Glad you solved your problem though :)
