### ISSUE TITLE
Add an option `modifyValueOnWheel` that allow the user to use mouse wheel to increment/decrement the element value

### ISSUE THREAD

**Issue by AlexandreBonneau** [BobKnothe/autoNumeric#393]
To improve the user experience, we should add an option `modifyValueOnWheel` (accepting the boolean values `true` and `false`) for using the mouse wheelup and wheeldown to respectively increment and decrement the current input value.

A second option `wheelStep` would allow to define the step, either :
- fixed like `'100'`, or
- `'progressive'`, which means you calculate the number of numbers in the integer part (ie. `9.999.999` -> `7`, and add/substract 7-1 = 6th places : `9.999.999 - 100.000`)

Warning: if the inputs are big, that can prevent the user to scroll the page or make him increment a wrong input close to the initial one.
To work around that potential problem :
- Allow the user to hold `Shift` while scrolling to ignore the input and just scroll the page (useful on small screen where some badly configured inputs could use all the available space)
- better yet, add a small `timeout` on mouse hover to make sure it won't be followed by a `mouseout` event (because you do not want to scroll in an input by accident just when it come under the mouse cursor that is currently scrolling the page)

Lastly, make sure the user cannot use that `wheel` event to go past the min and max values. If those are attained, then drop the `wheel` event to not scroll the page.

**Comment by AlexandreBonneau** [comment]
Bonus behavior written the comments!

**Comment by wc-matteo** [comment]
> Warning: if the inputs are big, that can prevent the user to scroll the page or make him increment a wrong input close to the initial one.

ehm... the wheel should work when an input has focus, just like `<input type="number">` in Chrome. With normal sized input and a large browser window I was scrolling the page and modifying inputs at the same time. This is bad.

**Comment by AlexandreBonneau** [comment]
I guess I'm guilty of using the default Linux behavior for decades now, where you can wheel away on anything without ever losing focus, which is pretty handy!

In that regard, I'm not really eager to change that behavior, but I can see a use case here.

Should we change the default value of the `modifyValueOnWheel` option so that the `wheel` event listener is not activated?
Any other ideas how we could do that in a better way? (we welcome any PR too ;P)

**Comment by wc-matteo** [comment]
Well the Linux behaviour you describe seems to be pretty bad for a general UX. I'm thinking of the average user here.

In my opinion the default behaviour should be that of the native `<input type="number">` as seen in Chrome (and others) on Windows (and MacOs, I immagine). With an option to disable the focus constraint (making it as it is now). If the implementation of the focus constraint is not feasible at the moment, I would suggest to change `modifyValueOnWheel `'s default value.

At the moment I don't have time for PRs but maybe in the future I'd like to contribute. I find this module really useful.

**Comment by AlexandreBonneau** [comment]
That would be our pleasure :)

Right now I do not have time to tackle this with the soon to be released `v4`, so if you want to keep track of that request, perhaps you could create a specific issue for it so we could consider what to do with it when available?
I'm not promising anything but commenting on already closed issues usually ends up lost at some point.

**Comment by wc-matteo** [comment]
Thanks. I'll do that then.
