### ISSUE TITLE
Decimal format not working in IE 11

### ISSUE THREAD

**Issue by jaffarsharp** [BobKnothe/autoNumeric#394]
Hi Team
In IE 11 browser autonumeric not working for decimal values field
<input name="fvalue" class="form-control ng-valid ng-dirty ng-valid-parse ng-touched ng-not-empty" type="text" ng-model="vm.fvalue" cr-numeric="{ aSep: ',', aDec: '.', vMax: '99999999999.99', vMin: '0.00' }">
i couldn't delete value using backspace key as well as not able to enter decimal value.
please reply me if anyone got the same issue..

**Comment by AlexandreBonneau** [comment]
Hello @jaffarsharp, which version of autoNumeric are you using?
Do you see any error message?
Could you please submit a codepen so we could try to reproduce the error?
Thank you!

**Comment by BobKnothe** [comment]
Hello @jaffarsharp, 

I create a quick codepen and it functions under IE10 - http://codepen.io/RJ_Knothe/full/YNLOog/.

As @AlexandreBonneau suggested please create a codepen to replicate your issue.

Bob

**Comment by AlexandreBonneau** [comment]
For info, I tested Bob's codepen on both IE10 and IE11 (via virtual machines) and it worked as intended.

The problem must come from your angular code.

**Comment by AlexandreBonneau** [comment]
Feel free to reopen that issue if you feel the error is on autoNumeric side.
