### ISSUE TITLE
Decimal key from numpad doesn't work in IE11

### ISSUE THREAD

**Issue by pheru** [BobKnothe/autoNumeric#401]
Hello.

Using Internet Explorer 11, the decimal key from numpad doesn't do anything in the current version of the master-branch:
https://jsfiddle.net/x7e5mccq/1/

With autoNumeric Version 1.9, it works:
https://jsfiddle.net/cad3cLgq/2/

Using Chrome, both versions work.

**Comment by AlexandreBonneau** [comment]
Thanks for reporting this bug, and providing live example @pheru, this really helps!
We'll look into it as soon as possible.

**Comment by BobKnothe** [comment]
@phero,

Please check this http://codepen.io/RJ_Knothe/pen/EWxBqe?editors=1010. 

if you could test and report back it would be appreciated

**Comment by AlexandreBonneau** [comment]
I tested on my end, and everything is fine now.

Thanks Robert!

**Comment by phero** [comment]
@BobKnothe Hi, you missed spell of @pheru 😄

**Comment by pheru** [comment]
@BobKnothe 
Example looks good, thanks!
