### ISSUE TITLE
The `scale*` option is broken when using a scale divisor inferior to zero

### ISSUE THREAD

**Issue by ducman** [BobKnothe/autoNumeric#403]
I'm using the below setting:
```js
var setting = {
  scaleDecimalPlaces: 2,
  scaleDivisor: 0.01,
  scaleSymbol: '%'
}
```

For a 0.25 value from the database, it shows up as 25.00% which is correct. But when I hover over the input and hover out, it takes the current value and multiple it by the `scaleDivisor` and it keep getting larger and larger with each hover in and out.

Am I using the `scale...` settings correctly or what is the correct way to setup a percentage input?

**Comment by BobKnothe** [comment]
Thanks for the catch. I will need to dig into this and get back with you. I

**Comment by BobKnothe** [comment]
ducman,

here is a link to the proposed fix http://codepen.io/RJ_Knothe/pen/EWxBqe?editors=1010. 

If you could test and report back it would be appreciated

**Comment by ducman** [comment]
I was able to play with the pen and this looks fixed. Good job!!
