### ISSUE TITLE
Validation don't work with ASP.NET MVC jQuery validation

### ISSUE THREAD

**Issue by hemalrathod** [BobKnothe/autoNumeric#405]
Following is my js code for autoNumeric
```js
$("input:text[class*='digits']").autoNumeric("init", { aSep: ''});
```

Following is my razor code for a form group 'Brokerage'
```html
<div class="form-group">
    @Html.LabelFor(model => model.Invoice.BROKERAGE, htmlAttributes: new { @class = "control-label col-md-4" })
    <div class="col-md-8">
        @Html.EditorFor(model => model.Invoice.BROKERAGE, new { htmlAttributes = new { @class = "form-control text-right digits" } })
        @Html.ValidationMessageFor(model => model.Invoice.BROKERAGE, "", new { @class = "text-danger" })
    </div>
</div>
```

Still, when I type 0.00 or 0 in Brokerage filed, it gives me following error

> Please enter only digtis.

Can you help me?

**Comment by AlexandreBonneau** [comment]
Hi, we have no such `'Please enter only digtis.'` error message in our source code.
This must come from the other library/framework you are using?

Keep in mind that autoNumeric only managed strings in input, [not real numbers](https://github.com/BobKnothe/autoNumeric/#on-which-elements-can-it-be-used).

Could that be the problem?

**Comment by AlexandreBonneau** [comment]
Hi, we have no such `'Please enter only digtis.'` error message in our source code.
This must come from the other library/framework you are using?

Keep in mind that autoNumeric only managed strings in input, [not real numbers](https://github.com/BobKnothe/autoNumeric/#on-which-elements-can-it-be-used).

Could that be the problem?

**Comment by hemalrathod** [comment]
I get it but why it is interfering if it did.

I just wanted to insert digits and that's why I connected autoNumeric.

So why MVC validation library, that is jquery.validate.js, is not recognising 0.00 in the textbox that is connected with autoNumeric?

**Comment by AlexandreBonneau** [comment]
I unfortunately do not know *asp.net* nor *jquery.validate.js*, which means I cannot tell you exactly why those behave like they do. I only know that as far as I checked, we tried to make AutoNumeric as transparent as possible event-wise so that it does not interfere with other libraries.

That said, since you are initializing AutoNumeric on those `<input>` elements, couldn't you drop the `digits` string, since you are sure AutoNumeric will take care of masking those?

**Comment by hemalrathod** [comment]
Ok let me check that. I will post the progress afterwards. Thank you for reply.

**Comment by AlexandreBonneau** [comment]
Hey @hemalrathod, did you fixed your problem?
If that's the case, please close this issue, thanks!

**Comment by AlexandreBonneau** [comment]
Thanks @hemalrathod, have a nice day!
