### ISSUE TITLE
Error thrown in PhantomJS 2.1.1 on Linux under CI Environment

### ISSUE THREAD

**Issue by rposborne** [BobKnothe/autoNumeric#417]
Currently seeing this in out test suit when attempting to use capybara to fill_in a field that uses autoNumeric. 

`undefined is not an object (evaluating 'this.keyCodeNumber')`

This was not present in 2.07, and is being thrown in 2.0.9.  Error appears to be from this commit https://github.com/BobKnothe/autoNumeric/commit/aa76e1b8574792859ecd28bd9688140a2bb1d606#diff-c657689185e339bb9234662ebefc85e9R993

I sadly do not have steps to reproduce as I was not able to even repeat locally outside of our CI.

**Comment by AlexandreBonneau** [comment]
@rposborne Could you please try with the latest 2.0.10 version and close that issue if your problem has been resolved?

Thanks!

**Comment by rposborne** [comment]
The issue appears to be resolved in 2.0.10.  Thank you for the quick turn around.  Your management of this project is inspiring.

**Comment by AlexandreBonneau** [comment]
Thanks ;P
