### ISSUE TITLE
Adding sum of multiple numeric fields

### ISSUE THREAD

**Issue by coda-apps** [BobKnothe/autoNumeric#421]
Form some reason, when i want to calculate the snum of a number of feilds that have autoNumeric applied to them, i get weird results.

HTML:

```
<input type="text" name="ss" class="comma">
<input type="text" name="ss4" class="comma">
<input type="text" name="ss42" class="comma">
<button class="go">go</button>
```

JS:

```
<script type="text/javascript">
$(document).ready(function(){	

	// $(".comma").autoNumeric('init');
	 
	 $(".go").click(function(){
		 var sum = 0;
		 
	 $('.comma').each(function() {
				sum += Number($(this).val());
				alert($(this).val());
		});
		alert(sum);
	 });
});
</script>
```

When i leave the `// $(".comma").autoNumeric('init');` commented out - it all behaves properly.
but as soon as i enable that line - things go wonky.
Would love to get to the bottom of this.

Thanks!

**Comment by AlexandreBonneau** [comment]
Well, you are effectively trying to add `string` values which contains dots, group separators and/or currency symbols ; this won't work!

If you want to sum, then you need to retrieve the *numeric* values, not the formatted strings.

With the latest stable, you can get it with `$(".comma").autoNumeric('get');`.
With the upcoming 4.0.0, you'll get it with `anElement.getNumber()`.

**Comment by coda-apps** [comment]
Thank you!
I guess i assumed that the number format would be recognizable.
