### ISSUE TITLE
`leadingZero` set to `keep` does not keep the leading zeros under Chrome

### ISSUE THREAD

**Issue by jarodljohnson** [BobKnothe/autoNumeric#423]
### Expected behavior
When typing a leading zero in a numeric field (like a zip code), I expect the leading zero to stay after the field looses focus.

### Actual behavior
If I click or hover over the text field, or if I click elsewhere on the form, the input is reformatted without the leading zero.

### Steps to reproduce the problem
1. Using autoNumeric `2.0.10` and the browser Firefox version 52 or the browser Chrome version 56 on Windows 8.1,
2. I used the options `lZero: 'keep'`, `aSep: ''`, `vMax: '99999'`, `mDec: '0'`, `aPad: 'false'`, and 
3. Initialized my AutoNumeric object with the call `$('#q5').autoNumeric({lZero: 'keep', aSep: '', vMax: '99999', mDec: '0', aPad: 'false'});`
4. I entered the zip code `"01234"`.   The leading zero stays in while I'm focused on the input, But after the input looses focus, the leading zero disappears.  Also, if I type `012345`, it removes the leading zero (the maxlength of the input is 5).

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
https://jsfiddle.net/a1sye06f/

**Comment by AlexandreBonneau** [comment]
Hi @jarodljohnson, thank you for reporting a bug.

Unfortunately, I cannot reproduce the bug which drops the leading zeros, under Firefox 45.8.0 nor 54.0a2. I'm on Linux though.
@BobKnothe can you?

I also cannot in your jsfiddle enter `012345`.

On Chrome 57 though, I experience the bug you are describing.
The exact step to reproduce it are:
1. Enter `01234` inside the input
2. Focus out by clicking outside of it (at that point, the input value is still `01234`)
3. **mouseover** the input, and its value is wrongly changed to `1234`

Note; under Chrome if you enter `01234|`, then `5`, the result is `12345|`, which is normal.

**Comment by AlexandreBonneau** [comment]
Note to self ; the behavior when entering `00123|`, then other numbers is different between Firefox and Chrome ; it should not.
I'll create another issue about this when this bug is closed.

**Comment by AlexandreBonneau** [comment]
For info, the options can be written this way now:

```js
new AutoNumeric('#issue_423', {
        leadingZero: AutoNumeric.options.leadingZero.keep,
        digitGroupSeparator: AutoNumeric.options.digitGroupSeparator.noSeparator,
        maximumValue: '99999',
        decimalPlacesOverride: 0,
        allowDecimalPadding: AutoNumeric.options.allowDecimalPadding.noPadding,
});
```
