### ISSUE TITLE
`autoUnformat()` converts `digitGroupSeparator` set to `.` as the decimal character

### ISSUE THREAD

**Issue by tagorejl** [BobKnothe/autoNumeric#427]
### Expected behavior
`autoUnFormat` method should unformat values using configuration properties.

### Actual behavior
No uses configuration supplied. When detects it's a number simply returns.

### Steps to reproduce the problem
```js
var value = $.fn.autoUnformat('4.000',
{
        digitGroupSeparator: '.', // Separador miles
        decimalCharacter: ',', // Separador decimales
        maximumValue: '9999.99', // Número max. negativo permitido
        minimumValue: '0'
});
```
In the example returns 4 currently. But, `digitGroupSeparator` is set as `'.'` so the `'4.000'` value , should return `4000`.

**Comment by BobKnothe** [comment]
Thank you for the notice.

Quick testing firms your issue. The offending code in version 2 is

``` javascript
        // Giving an unformatted value should return the same unformatted value, whatever the options passed as a parameter
        if (isNumber(value)) {
            return Number(value);
        }
```
If you comment out the return in your local copy it should work as you expected. We will post a fix update this weekend

**Comment by AlexandreBonneau** [comment]
Well, thanks again @tagorejl, because your issue uncovered many underlying bugs in the `AutoNumeric.unformat()` function.

The number of decimal places, the negative brackets, rounding and the suffix text options were not correctly taken into account when unformatting.

That's now the case on `next`!

**Comment by tagorejl** [comment]
Thanks for fixing so fast.

**Comment by AlexandreBonneau** [comment]
You're welcome!
