### ISSUE TITLE
Allow select all from keyboard

### ISSUE THREAD

**Issue by sformisano** [BobKnothe/autoNumeric#59]
When autonumeric is applied to a text field, the CMD + A keyboard combo brings the cursor at the beginning of the input rather than simply allowing to select the full value.

It would be rad to make sure the plugin does not override the expected CMD + A behaviour.

I would imagine this is an issue on windows as well with CTRL + A but I have no machine to test this on.

**Comment by vemv** [comment]
Would be great to have this issue closed :)

**Comment by BobKnothe** [comment]
Victory,

This was fixed in version 2.0.

Bob
