### ISSUE TITLE
Fields with autoNumeric do not trigger `input` events.

### ISSUE THREAD

**Issue by denilsonsa** [BobKnothe/autoNumeric#98]
How to reproduce:

1. Open http://www.decorplanit.com/plugin/
2. Add a simple `oninput` handler to all text boxes:

        $('input[type="text"]').on('input', function(ev){console.log(ev);});

3. Open JavaScript console.
4. Put focus on any autoNumeric input box and try typing some keys. BUG! Nothing show up in the JavaScript console.
5. Try removing autoNumeric from the boxes:

        $('input[type="text"]').autoNumeric('destroy');

6. Try typing anything. Now our `oninput` handler gets called and events get printed into the console.

I believe this happens due to the way autoNumeric handles key presses events.

As a side node, if I input a number using mouse (middle-click to paste, on Linux, or right-click→Paste on any system), then autoNumeric does not format the number until the focus changes (and my handler gets called). This implies that autoNumeric does not handle the `input` event if it happens due to an non-keyboard action.

**Comment by jdlib** [comment]
I tried the following to make autonumeric fields issue input events: Within the keydown-, keypress- and keyup handlers trigger an input event after every call to formatQuick() 
```
holder.formatQuick();
$this.trigger('input'); // patch
```

Seems to work.

**Comment by BobKnothe** [comment]
Johannas,

Thanks for the suggestion - great idea.

Why do you suggest apply to all three key event? potentially the input 
event would fire three times?

Bob

**Comment by jdlib** [comment]
Hi Bob,

yes, firing three times would be too much. Did not analyse it in depth, but as far as I can see the flags holder.processed and holder.formatted cause that formatQuick()  is only called one time from the three key-handler.

Johannes

**Comment by peruzzo** [comment]
+1

**Comment by diegoag64** [comment]
Was the first issue addressed? I am having issues with the input 'change' function. I need to get the value of an autoNumeric controlled input whenever it changes and pass it to another hidden input field but whenever I try to use the 'change' event to detect whenever the input changes nothing happens.

Please help!

**Comment by BobKnothe** [comment]
The change event fires only on focusout if the value has changed. 

Try using the keyup event and test if the value has changed. 



 
Robert (Bob) Knothe

**Comment by diegoag64** [comment]
Yeah that worked, and another question, is there any way to get a raw float without commas of whatever is in the autoNumeric input? Like if the input has $ 1,200,000.00 to get only 1200000.00

**Comment by BobKnothe** [comment]
Yes! In 1.9.39 use autoNumeric's "get" methodvar rawValue = $(selector).autoNumeric('get'); Please note that the "get" does not pad and would return the following //1,200,000.00 => 1200000//1,200,000.10 => 1200000.1//1,200,000.01 => 1200000.01//1,200,000.11 => 1200000.11Bob


-------- Original Message --------
Subject: Re: [autoNumeric] Fields with autoNumeric do not trigger
`input` events. (#98)

**Comment by BobKnothe** [comment]
added to version 2 

https://github.com/BobKnothe/autoNumeric/tree/master/autoNumeric-2.0
